unpackaged/main/default/objects/Partnerships__c/Partnerships__c.object-meta.xml
<CustomObject>
    <label>Partnership</label>
    <nameField>
        <label>Partnership</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnerships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Partnerships__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partnerships</relationshipLabel>
    <relationshipName>Partnerships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Referral__c/Referral__c.object-meta.xml
<CustomObject>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF- {0}</displayFormat>
        <label>Referral name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Referral__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to the partner account</description>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referrals (Partner Account)</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Referral__c/fields/Partnership__c.field-meta.xml
<CustomField>
    <fullName>Partnership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partnership</label>
    <referenceTo>Partnerships__c</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Partners</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Referral__c/fields/Payments_Enterprise_Account__c.field-meta.xml
<CustomField>
    <fullName>Payments_Enterprise_Account__c</fullName>
    <label>Payments Enterprise Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>True</fullName>
            </value>
            <value>
                <fullName>False</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/UpdateReferralsHandler.cls
public with sharing class UpdateReferralsHandler {

    @Future
    public static void UpdateReferralsHandler(String account_id, String picklist_value) {

        // Get Referral Records
        system.debug('Referral Search Parameters: ' + account_id + ' ' + picklist_value);
        List<Referral__c> update_ref = new List<Referral__c>();
        for(Referral__c r : [SELECT Id, Payments_Enterprise_Account__c FROM Referral__c WHERE Partnership__r.Partner_Account__c = : account_id]){
            r.Payments_Enterprise_Account__c = picklist_value;
            update_ref.add(r);
        }
        update update_ref;
    }
}