unpackaged/main/default/objects/GIdentifyEntityInformation__c/GIdentifyEntityInformation__c.object-meta.xml
<CustomObject>
    <label>GIdentifyEntityInformation</label>
    <nameField>
        <label>GIdentifyEntityInformation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GIdentifyEntityInformations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GIdentifyEntityInformation__c/fields/AddressValidationStatus__c.field-meta.xml
<CustomField>
    <fullName>AddressValidationStatus__c</fullName>
    <label>Address Validation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GIdentifyEntityInformation__c/fields/DOB_Status__c.field-meta.xml
<CustomField>
    <fullName>DOB_Status__c</fullName>
    <description>R1811288</description>
    <label>DOB Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GIdentifyEntityInformation__c/fields/Fraud_Activity_Found__c.field-meta.xml
<CustomField>
    <fullName>Fraud_Activity_Found__c</fullName>
    <defaultValue>false</defaultValue>
    <description>R1917612</description>
    <label>Fraud Activity Found</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/GIdentifyEntityInformation__c/fields/GIACTIdentifyResponse__c.field-meta.xml
<CustomField>
    <fullName>GIACTIdentifyResponse__c</fullName>
    <label>GIACT Identify Response</label>
    <referenceTo>GIACTIdentifyResponses__c</referenceTo>
    <relationshipLabel>GIdentifyEntityInformations</relationshipLabel>
    <relationshipName>GIdentifyEntityInformations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/GIdentifyEntityInformation__c/fields/GIdentifyAdvanceRequest__c.field-meta.xml
<CustomField>
    <fullName>GIdentifyAdvanceRequest__c</fullName>
    <label>GIdentifyAdvance Request</label>
    <length>100768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/GIdentifyEntityInformation__c/fields/GIdentifyAdvanceResponse__c.field-meta.xml
<CustomField>
    <fullName>GIdentifyAdvanceResponse__c</fullName>
    <label>GIdentifyAdvance Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/GIdentifyEntityInformation__c/fields/gIdentifyRequestText__c.field-meta.xml
<CustomField>
    <fullName>gIdentifyRequestText__c</fullName>
    <label>gIdentify Request Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/GIdentifyEntityInformation__c/fields/gIdentifyResponseCode__c.field-meta.xml
<CustomField>
    <fullName>gIdentifyResponseCode__c</fullName>
    <label>gIdentify Response Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Null</fullName>
            </value>
            <value>
                <fullName>CA01</fullName>
            </value>
            <value>
                <fullName>CA11</fullName>
            </value>
            <value>
                <fullName>CA21</fullName>
            </value>
            <value>
                <fullName>CA22</fullName>
            </value>
            <value>
                <fullName>CA23</fullName>
            </value>
            <value>
                <fullName>CA24</fullName>
            </value>
            <value>
                <fullName>CA25</fullName>
            </value>
            <value>
                <fullName>CA30</fullName>
            </value>
            <value>
                <fullName>CI01</fullName>
            </value>
            <value>
                <fullName>CI02</fullName>
            </value>
            <value>
                <fullName>CI11</fullName>
            </value>
            <value>
                <fullName>CI21</fullName>
            </value>
            <value>
                <fullName>CI22</fullName>
            </value>
            <value>
                <fullName>CI23</fullName>
            </value>
            <value>
                <fullName>CI24</fullName>
            </value>
            <value>
                <fullName>CI25</fullName>
            </value>
            <value>
                <fullName>CI30</fullName>
            </value>
            <value>
                <fullName>ND02</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GIdentifyEntityInformation__c/fields/gIdentifyResponseReason__c.field-meta.xml
<CustomField>
    <fullName>gIdentifyResponseReason__c</fullName>
    <label>gIdentify Response Reason</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GIdentifyEntityInformation__c/fields/gIdentifyResponseText__c.field-meta.xml
<CustomField>
    <fullName>gIdentifyResponseText__c</fullName>
    <label>gIdentify Response Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/GIdentifyEntityInformation__c/fields/NameValidationStatus__c.field-meta.xml
<CustomField>
    <fullName>NameValidationStatus__c</fullName>
    <label>Name Validation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GIdentifyEntityInformation__c/fields/NumberofBankruptcies__c.field-meta.xml
<CustomField>
    <fullName>NumberofBankruptcies__c</fullName>
    <label># of Bankruptcies</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GIdentifyEntityInformation__c/fields/NumberOfJudgements__c.field-meta.xml
<CustomField>
    <fullName>NumberOfJudgements__c</fullName>
    <label># of Judgements</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GIdentifyEntityInformation__c/fields/NumberofLiens__c.field-meta.xml
<CustomField>
    <fullName>NumberofLiens__c</fullName>
    <label># of Liens</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GIdentifyEntityInformation__c/fields/OFACInformation__c.field-meta.xml
<CustomField>
    <fullName>OFACInformation__c</fullName>
    <label>OFAC Information</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/GIdentifyEntityInformation__c/fields/RegistrationType__c.field-meta.xml
<CustomField>
    <fullName>RegistrationType__c</fullName>
    <label>Registration Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GIdentifyEntityInformation__c/fields/RequestUniqueId__c.field-meta.xml
<CustomField>
    <fullName>RequestUniqueId__c</fullName>
    <label>Request Unique Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GIdentifyEntityInformation__c/fields/SECStatus__c.field-meta.xml
<CustomField>
    <fullName>SECStatus__c</fullName>
    <label>SEC Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GIdentifyEntityInformation__c/fields/SSNTaxIdValidationStatus__c.field-meta.xml
<CustomField>
    <fullName>SSNTaxIdValidationStatus__c</fullName>
    <label>SSN/Tax Id Validation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GIdentifyEntityInformation__c/recordTypes/Business.recordType-meta.xml
<RecordType>
    <fullName>Business</fullName>
    <active>true</active>
    <label>Business</label>
</RecordType>

unpackaged/main/default/objects/GIdentifyEntityInformation__c/recordTypes/Individual.recordType-meta.xml
<RecordType>
    <fullName>Individual</fullName>
    <active>true</active>
    <label>Individual</label>
</RecordType>

unpackaged/main/default/classes/GIdentifyEntity.cls
/*
* Test Class: GiactVerifyServiceTest
*/
public with sharing class GIdentifyEntity {

	public class GIdentifyEntityException extends Exception {}

	public Boolean isBusinessRecord {get; set;}
	public Id ParentId {get; set;}
	public Id vPlusId {get; set;}


	public String Name {get; set;}

	public String gIDAdvancedRawRequest {get; set;}
	public String gIDAdvancedRawResponse {get; set;}

	public String gIDBasicRawRequest {get; set;}
	public String gIDBasicRawResponse {get; set;}

	public String responseReasonCode {get; set;}
	public String responseReason {get; set;}

	public String nameValidationStatus {get; set;}
	public String dobValidationStatus {get; set;}	
	public String addressValidationStatus {get; set;}
	public String taxIdValidationStatus {get; set;}

	public String numberOfBankruptcies {get; set;}
	public String numberOfLeins {get; set;}
	public String numberOfJudgements {get; set;}

	public String ofacInformation {get; set;}
	public String registrationType {get; set;}
	public String secStatus {get; set;}	

	public String uniqueId {get; set;}

	public List<Attachment> entityAttachments {get; set;}

	GIdentifyEntityInformation__c entityDBRecord {get; set;}

	public GIdentifyEntity() {
		entityAttachments =  new List<Attachment> ();
		entityDBRecord = new GIdentifyEntityInformation__c ();

		nameValidationStatus = 'N/A';
		dobValidationStatus = 'N/A';
		addressValidationStatus = 'N/A';
		taxIdValidationStatus = 'N/A';

		numberOfBankruptcies = 'N/A';
		numberOfLeins = 'N/A';
		numberOfJudgements = 'N/A';

		secStatus = 'N/A';
	}

	public GIdentifyEntity(Id valuePlus, Boolean isBusiness) {
		this.vPlusId = valuePlus;
		this.isBusinessRecord = isBusiness; 
		entityAttachments =  new List<Attachment> ();
		entityDBRecord = new GIdentifyEntityInformation__c ();
	}

	public void updateDataOnDBRecord () {
		if (isBusinessRecord) {
    		entityDBRecord.RecordTypeId = Schema.SObjectType.GIdentifyEntityInformation__c.getRecordTypeInfosByName().get('Business').getRecordTypeId();
    	} else {
    		entityDBRecord.RecordTypeId = Schema.SObjectType.GIdentifyEntityInformation__c.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
    	}

		entityDBRecord.Name = name;
		Integer maxLength1 = GIdentifyEntityInformation__c.GIdentifyAdvanceResponse__c.getDescribe().getLength();
		entityDBRecord.GIdentifyAdvanceRequest__c = gIDAdvancedRawRequest;
		if (!String.isEmpty(gIDAdvancedRawResponse)){
			entityDBRecord.GIdentifyAdvanceResponse__c = gIDAdvancedRawResponse.length() > maxLength1 ? gIDAdvancedRawResponse.substring(0, maxLength1-5) : gIDAdvancedRawResponse;
		}

		Integer maxLength2 = GIdentifyEntityInformation__c.gIdentifyResponseText__c.getDescribe().getLength();
		entityDBRecord.gIdentifyRequestText__c = gIDBasicRawRequest;
		if (!String.isEmpty(gIDBasicRawResponse)){
			entityDBRecord.gIdentifyResponseText__c = gIDBasicRawResponse.length() > maxLength2 ? gIDBasicRawResponse.substring(0, maxLength2-5) : gIDBasicRawResponse;
		}

		List<String> fraudString = System.Label.GIACT_Keyword_List.split(',');
		for (String fraud : fraudString) {
			if ((!String.isEmpty(gIDAdvancedRawResponse) && gIDAdvancedRawResponse.containsIgnoreCase(fraud)) || 
				(!String.isEmpty(gIDBasicRawResponse) && gIDBasicRawResponse.containsIgnoreCase(fraud))){
				entityDBRecord.Fraud_Activity_Found__c = true;
				break;
			}
		}

		entityDBRecord.gIdentifyResponseCode__c = responseReasonCode;
		entityDBRecord.gIdentifyResponseReason__c = responseReason;

		entityDBRecord.NameValidationStatus__c = nameValidationStatus;
		entityDBRecord.DOB_Status__c = dobValidationStatus;
		entityDBRecord.AddressValidationStatus__c = addressValidationStatus;
		entityDBRecord.SSNTaxIdValidationStatus__c = taxIdValidationStatus;


		entityDBRecord.NumberofBankruptcies__c = (!String.isEmpty(numberOfBankruptcies)) ? Integer.valueOf(numberOfBankruptcies) : null;
		entityDBRecord.NumberofLiens__c = (!String.isEmpty(numberOfLeins)) ? Integer.valueOf(numberOfLeins) : null;
		entityDBRecord.NumberOfJudgements__c = (!String.isEmpty(numberOfJudgements)) ? Integer.valueOf(numberOfJudgements) : null;

		System.debug(entityDBRecord.NumberofBankruptcies__c + ' ----- ' + ((String.isEmpty(numberOfBankruptcies)==false) ? Integer.valueOf(numberOfBankruptcies) : null));

		entityDBRecord.OFACInformation__c = ofacInformation;
		entityDBRecord.RegistrationType__c = ((String.isEmpty(registrationType)||registrationType.equals('null'))? 'N/A' : registrationType);		
		entityDBRecord.SECStatus__c = ((String.isEmpty(secStatus)||secStatus.equals('null'))? 'N/A' : secStatus);
		entityDBRecord.RequestUniqueId__c = uniqueId;
		entityDBRecord.GIACTIdentifyResponse__c = ParentId;

		System.debug(entityDBRecord.NumberofBankruptcies__c + ' ----- ' + ((String.isEmpty(numberOfBankruptcies)==false) ? Integer.valueOf(numberOfBankruptcies) : null));
	}

	public void  insertEntity () {

		updateDataOnDBRecord ();

		try {
			if (ParentId==null) {
				throw new GIdentifyEntityException ('Parent Id is not updated. Please update the parent Id. This happens when GIDResponse insert has failed.');
			}

			insert entityDBRecord;

			for (Attachment att : entityAttachments) {
				att.parentId = entityDBRecord.Id;
			}

			if (!entityAttachments.isEmpty()) {
				insert entityAttachments; 
			}
		} catch (Exception ex) {
			SystemExceptionLogger.insertSystemExceptionLogEntry(ex, 
										 							'GIACT Identify',  
										 							'InsertEntity : InsertEntity', 
										 							SystemExceptionLogger.EXCEPTION_LEVEL_CRITICAL,
										 							'Error while inserting the Entity Result in Database.',
										 							'ValuePlus',
													 				vPlusId,
										 							true);
		}
	}

}