unpackaged/main/default/objects/Account/fields/Account_DBA_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_DBA_Name__c</fullName>
    <description>updated per R1710014</description>
    <formula>IF(NOT(ISBLANK(  Full_Company_Name_DBA__c  )) &amp;&amp; LOWER(Full_Company_Name_DBA__c) != &#39;n/a&#39; &amp;&amp; LOWER(Full_Company_Name_DBA__c) != &#39;na&#39;, Full_Company_Name_DBA__c, IF(CONTAINS(Name, &quot;DBA&quot;), RIGHT(Name, LEN(Name)-FIND(&quot;DBA &quot;, Name)-3),  Account_Legal_Name__c ))</formula>
    <label>Account DBA Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <description>For capturing and tracking accounts that aren&#39;t a customer, partner or competitor</description>
    <label>Other</label>
</RecordType>

unpackaged/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000000}</displayFormat>
        <label>Bank Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bank_Account__c/fields/Account_Label__c.field-meta.xml
<CustomField>
    <fullName>Account_Label__c</fullName>
    <label>Account Label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/AccountNo__c.field-meta.xml
<CustomField>
    <fullName>AccountNo__c</fullName>
    <label>Account #</label>
    <length>17</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/LID__c.field-meta.xml
<CustomField>
    <fullName>LID__c</fullName>
    <label>LID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Location_Add_Status__c.field-meta.xml
<CustomField>
    <fullName>Location_Add_Status__c</fullName>
    <inlineHelpText>Submitted - ProfitStars is processing the request
Approved - ProfitStars approved the request and provided LID
Completed - LID updated to APM</inlineHelpText>
    <label>Location Add Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/RoutingNo__c.field-meta.xml
<CustomField>
    <fullName>RoutingNo__c</fullName>
    <label>Routing #</label>
    <length>9</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/ValuePlus__c.field-meta.xml
<CustomField>
    <fullName>ValuePlus__c</fullName>
    <label>Value+</label>
    <referenceTo>ValuePlus__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/ValuePlus__c.object-meta.xml
<CustomObject>
    <label>Value+</label>
    <nameField>
        <displayFormat>VAS{000000}</displayFormat>
        <label>Value+</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ValuePlus</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ValuePlus__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Value+</relationshipLabel>
    <relationshipName>Value</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Account_DBA_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_DBA_Name__c</fullName>
    <formula>Account__r.Account_DBA_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account DBA Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/OnBoardingStatus__c.field-meta.xml
<CustomField>
    <fullName>OnBoardingStatus__c</fullName>
    <label>On-Boarding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initial Review</fullName>
            </value>
            <value>
                <fullName>Welcome Scheduled</fullName>
            </value>
            <value>
                <fullName>Inspection Ordered</fullName>
            </value>
            <value>
                <fullName>Collecting Documents</fullName>
            </value>
            <value>
                <fullName>Documents Received</fullName>
            </value>
            <value>
                <fullName>Escalated to Compliance</fullName>
            </value>
            <value>
                <fullName>Merchant App Sent</fullName>
            </value>
            <value>
                <fullName>Merchant App Received</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Pending Peer Review</fullName>
            </value>
            <value>
                <fullName>Sent to Underwriting</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Underwritten</fullName>
            </value>
            <value>
                <fullName>Peer Review Rejected</fullName>
            </value>
            <value>
                <fullName>Ready to transmit</fullName>
            </value>
            <value>
                <fullName>Transmitted</fullName>
            </value>
            <value>
                <fullName>Ready to Go Live</fullName>
            </value>
            <value>
                <fullName>Ready for APM</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Apm data pull failure</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Pending Compliance Review</fullName>
            </value>
            <value>
                <fullName>Compliance Review Rejected</fullName>
            </value>
            <value>
                <fullName>Welcome Missed</fullName>
            </value>
            <value>
                <fullName>Pending Data Ver</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Outbound_MID__c.field-meta.xml
<CustomField>
    <fullName>Outbound_MID__c</fullName>
    <description>Created by R152610
Updated By  R163828</description>
    <label>Outbound MID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Outbound_On_Boarding_Status__c.field-meta.xml
<CustomField>
    <fullName>Outbound_On_Boarding_Status__c</fullName>
    <label>Outbound On-Boarding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initial Review</fullName>
            </value>
            <value>
                <fullName>Welcome Scheduled</fullName>
            </value>
            <value>
                <fullName>Inspection Ordered</fullName>
            </value>
            <value>
                <fullName>Collecting Documents</fullName>
            </value>
            <value>
                <fullName>Documents Received</fullName>
            </value>
            <value>
                <fullName>Merchant App Sent</fullName>
            </value>
            <value>
                <fullName>Merchant App Received</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Pending Peer Review</fullName>
            </value>
            <value>
                <fullName>Sent to Underwriting</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Underwritten</fullName>
            </value>
            <value>
                <fullName>Peer Review Rejected</fullName>
            </value>
            <value>
                <fullName>Ready to transmit</fullName>
            </value>
            <value>
                <fullName>Transmitted</fullName>
            </value>
            <value>
                <fullName>Ready to Go Live</fullName>
            </value>
            <value>
                <fullName>Ready for APM</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Apm data pull failure</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/PMT_ProfitStars_On_Boarding_Status__c.field-meta.xml
<CustomField>
    <fullName>PMT_ProfitStars_On_Boarding_Status__c</fullName>
    <label>ProfitStars On-Boarding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initial Review</fullName>
            </value>
            <value>
                <fullName>Collecting Documents</fullName>
            </value>
            <value>
                <fullName>Pending Peer Review</fullName>
            </value>
            <value>
                <fullName>Peer Review Approved</fullName>
            </value>
            <value>
                <fullName>Sent to ProfitStars</fullName>
            </value>
            <value>
                <fullName>Transmitted</fullName>
            </value>
            <value>
                <fullName>Ready for APM</fullName>
            </value>
            <value>
                <fullName>Ready to Go Live</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Peer Review Rejected</fullName>
            </value>
            <value>
                <fullName>APM Data Pull Failure</fullName>
            </value>
            <value>
                <fullName>Ready to Transmit</fullName>
            </value>
            <value>
                <fullName>Documents Received</fullName>
            </value>
            <value>
                <fullName>ProfitStars Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/ProfitStars_Merchant_ID__c.field-meta.xml
<CustomField>
    <fullName>ProfitStars_Merchant_ID__c</fullName>
    <label>ProfitStars Merchant ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sold/Not Started</fullName>
            </value>
            <value>
                <fullName>KOC Confirmed</fullName>
                <label>Questionnaire Received</label>
            </value>
            <value>
                <fullName>Sold/Not Ready</fullName>
            </value>
            <value>
                <fullName>On-Boarding</fullName>
            </value>
            <value>
                <fullName>KOC Scheduled</fullName>
            </value>
            <value>
                <fullName>KOC Complete</fullName>
            </value>
            <value>
                <fullName>Build In Progress</fullName>
            </value>
            <value>
                <fullName>Site Presentation</fullName>
            </value>
            <value>
                <fullName>Site Delivered/Final Changes</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Additional Communication (O)</fullName>
            </value>
            <value>
                <fullName>Agreement Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Content Acquisition</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Deferred-Built</fullName>
            </value>
            <value>
                <fullName>Deferred-Canceled</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Final Changes</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Left APM</fullName>
            </value>
            <value>
                <fullName>Left IM</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Live-Free Trial</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Lost During Pilot</fullName>
            </value>
            <value>
                <fullName>Lost In Onboarding</fullName>
            </value>
            <value>
                <fullName>Multi Site Deffered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/PS_BatchGetMidLidTest.cls
/******************************************************************************************************
* copyright © 2016
*
* File		: PS_BatchGetMidLidTest.cls
*
* Purpose	: This is a batch class for other(any) Update. Thi class identified the records for other update 
*				and instanciates the service class to send the request to profitstars
*
* Test class for the PS_BatchGetMidLid class.
*-----------------------------------------------------------------------------
*
*Release Date		Request 	Updated By			Description
*----------------------------------------------------------------------------------------------------------------------
*					Nill							Initial Creation
*
*09/13/2016			R163756		Rohit Kumar Malik	Create a batch to update MID and LIDs (GET Request) from ProfitStars
*09/13/2016			R164098		Rohit Kumar Malik	MYCase
*
** Latest Changes 09/19/2016
*/
@isTest
public class PS_BatchGetMidLidTest{

	//Creates test data that is used by the unit tests in this class.
    @TestSetup
    public static void createTestData(){
    	TestDataFactory.createCustomSettings();

    	TestDataFactory.DataModel dm = new TestDataFactory.DataModel(1, false);
		//insert accounts
		// dm.accountList[0].RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('MyCase Account').getRecordTypeId();
		INSERT(dm.accountList);
		
		//insert valuePlus
		dm.valueplusList[0].Account__c = dm.accountList[0].Id;
		dm.valueplusList[0].RecordTypeId = Schema.SObjectType.ValuePlus__c.getRecordTypeInfosByName().get('MyCase Payments').getRecordTypeId();
		dm.valueplusList[0].Stage__c = 'Sold/Not Started';
		dm.valueplusList[0].OnBoardingStatus__c = 'Transmitted';
		dm.valueplusList[0].Outbound_On_Boarding_Status__c = 'Transmitted';
		INSERT(dm.valuePlusList[0]);

		//insert bank accounts
		dm.bankAccountList[0].ValuePlus__c = dm.valueplusList[0].Id;
		dm.bankAccountList[0].RoutingNo__c = '053000196';
		dm.bankAccountList[0].AccountNo__c = '1234567891';
		INSERT(dm.bankAccountList[0]);
    }

    static testmethod void batchInboundTest(){

    	TestUtils.genTestSettings(true);

    	ValuePlus__c vp = [Select Id, Account_DBA_Name__c from ValuePlus__c where Account__r.Name = 'Test Account0' limit 1];

    	String validCallJson = '{"GetAllMerchants":{"GetAllMerchantsResult":{"WSMerchant":[{"BoardingRefId":"' + vp.Id +'","CreationDateTime":"2019-04-23T10:33:13Z","CustServProviderId":"1234567890","EntityId":"591849","MerchantEnabled":true,"MerchantName":"' + vp.Account_DBA_Name__c +'","Locations":{"WSMerchantLocation":[{"LocationEnabled":true,"LocationId":"4154369","LocationName":"Test Bank Account0"}]}}]}},"HTTPStatusCode":"200"}';

		Test.setMock(HttpCalloutMock.class, new RestClientCalloutMockFactory(200, 'Success', validCallJson, null));
								 
		Test.startTest();
		PS_BatchGetMidLid batchJob = new PS_BatchGetMidLid();
		ID batchprocessid = Database.executeBatch(batchJob);
		Test.stopTest();

		ValuePlus__c vplus = [Select Id, ProfitStars_Merchant_ID__c, OnBoardingStatus__c, PMT_ProfitStars_On_Boarding_Status__c from ValuePlus__c where Account__r.Name = 'Test Account0' limit 1];
		System.assertEquals('Approved', vplus.PMT_ProfitStars_On_Boarding_Status__c);
		System.assertEquals('591849', vplus.ProfitStars_Merchant_ID__c);

		Bank_Account__c bank = [Select Id, LID__c, Location_Add_Status__c from Bank_Account__c where Account_Label__c = 'Test Bank Account0'];
		System.assertEquals('Approved', bank.Location_Add_Status__c);
		System.assertEquals('4154369', bank.LID__c);
	}

	static testmethod void batchOutboundTest(){

    	TestUtils.genOutboundTestSettings(true);

    	ValuePlus__c vp = [Select Id, Account_DBA_Name__c  from ValuePlus__c where Account__r.Name = 'Test Account0' limit 1];

    	String validCallJson = '{"GetAllMerchants":{"GetAllMerchantsResult":{"WSMerchant":[{"BoardingRefId":"' + vp.Id +'","CreationDateTime":"2019-04-23T10:33:13Z","CustServProviderId":"1234567890","EntityId":"591850","MerchantEnabled":true,"MerchantName":"' + vp.Account_DBA_Name__c  +'","Locations":{"WSMerchantLocation":[{"LocationEnabled":true,"LocationId":"4154370","LocationName":"Test Bank Account0"}]}}]}},"HTTPStatusCode":"200"}';

		Test.setMock(HttpCalloutMock.class, new RestClientCalloutMockFactory(200, 'Success', validCallJson, null));
								 
		Test.startTest();
		PS_BatchGetMidLid batchJob = new PS_BatchGetMidLid();
		ID batchprocessid = Database.executeBatch(batchJob);
		Test.stopTest();

		ValuePlus__c vplus = [Select Id, Outbound_MID__c, Outbound_On_Boarding_Status__c from ValuePlus__c where Account__r.Name = 'Test Account0' limit 1];
		// System.assertEquals('Approved', vplus.Outbound_On_Boarding_Status__c);
		// System.assertEquals('591850', vplus.Outbound_MID__c);

		Bank_Account__c bank = [Select Id, Outbound_LID__c, Outbound_Location_Add_Status__c from Bank_Account__c where Account_Label__c = 'Test Bank Account0'];
		// System.assertEquals('Approved', bank.Outbound_Location_Add_Status__c);
		// System.assertEquals('4154370', bank.Outbound_LID__c);
	}

	static testmethod void batchMyCaseTest(){

    	TestUtils.genMyCaseInboundTestSettings(true);

		Test.startTest();
    	Account acc = [Select Id, RecordTypeId from Account where Name = 'Test Account0' limit 1];
    	// acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('MyCase Account').getRecordTypeId();
    	update acc;

    	ValuePlus__c vp = [Select Id, RecordTypeId, Account_DBA_Name__c , PMT_ProfitStars_On_Boarding_Status__c from ValuePlus__c where Account__r.Name = 'Test Account0' limit 1];
    	vp.PMT_ProfitStars_On_Boarding_Status__c = 'Transmitted';
    	vp.RecordTypeId = Schema.SObjectType.ValuePlus__c.getRecordTypeInfosByName().get('MyCase Payments').getRecordTypeId();
    	update vp;

    	String validCallJson = '{"GetAllMerchants":{"GetAllMerchantsResult":{"WSMerchant":[{"BoardingRefId":"' + vp.Id +'","CreationDateTime":"2019-04-23T10:33:13Z","CustServProviderId":"1234567890","EntityId":"591849","MerchantEnabled":true,"MerchantName":"' + vp.Account_DBA_Name__c  +'","Locations":{"WSMerchantLocation":[{"LocationEnabled":true,"LocationId":"4154369","LocationName":"Test Bank Account0"}]}}]}},"HTTPStatusCode":"200"}';

		Test.setMock(HttpCalloutMock.class, new RestClientCalloutMockFactory(200, 'Success', validCallJson, null));
								 
		
		PS_BatchGetMidLid batchJob = new PS_BatchGetMidLid();
		ID batchprocessid = Database.executeBatch(batchJob);
		Test.stopTest();

		ValuePlus__c vplus = [Select Id, ProfitStars_Merchant_ID__c, PMT_ProfitStars_On_Boarding_Status__c from ValuePlus__c where Account__r.Name = 'Test Account0' limit 1];
		System.assertEquals('Approved', vplus.PMT_ProfitStars_On_Boarding_Status__c);
		System.assertEquals('591849', vplus.ProfitStars_Merchant_ID__c);

		Bank_Account__c bank = [Select Id, LID__c, Location_Add_Status__c from Bank_Account__c where Account_Label__c = 'Test Bank Account0'];
		System.assertEquals('Approved', bank.Location_Add_Status__c);
		System.assertEquals('4154369', bank.LID__c);
	}
}