unpackaged/main/default/objects/Account/fields/Account_DBA_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_DBA_Name__c</fullName>
    <description>updated per R1710014</description>
    <formula>IF(NOT(ISBLANK(  Full_Company_Name_DBA__c  )) &amp;&amp; LOWER(Full_Company_Name_DBA__c) != &#39;n/a&#39; &amp;&amp; LOWER(Full_Company_Name_DBA__c) != &#39;na&#39;, Full_Company_Name_DBA__c, IF(CONTAINS(Name, &quot;DBA&quot;), RIGHT(Name, LEN(Name)-FIND(&quot;DBA &quot;, Name)-3),  Account_Legal_Name__c ))</formula>
    <label>Account DBA Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Add_On_Batch__c/Add_On_Batch__c.object-meta.xml
<CustomObject>
    <label>Bank Account Add-On Batch</label>
    <nameField>
        <displayFormat>AO{000000}</displayFormat>
        <label>Bank Account Add-On Batch</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Account Add-On Batches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Add_On_Batch__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client Requested</fullName>
            </value>
            <value>
                <fullName>Bank Auth Form Sent</fullName>
            </value>
            <value>
                <fullName>Ready for Cybersource</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>No Response</fullName>
            </value>
            <value>
                <fullName>Request Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Add_On_Batch__c/fields/ValuePlus__c.field-meta.xml
<CustomField>
    <fullName>ValuePlus__c</fullName>
    <label>Value+</label>
    <referenceTo>ValuePlus__c</referenceTo>
    <relationshipLabel>Bank Account Add-On Batches</relationshipLabel>
    <relationshipName>Bank_Account_Add_On_Batches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000000}</displayFormat>
        <label>Bank Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bank_Account__c/fields/Account_Label__c.field-meta.xml
<CustomField>
    <fullName>Account_Label__c</fullName>
    <label>Account Label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/AccountNo__c.field-meta.xml
<CustomField>
    <fullName>AccountNo__c</fullName>
    <label>Account #</label>
    <length>17</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Bank_Account_Add_On_Batch__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Add_On_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account Add-On Batch</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Add_On_Batch__c.ValuePlus__c</field>
            <operation>equals</operation>
            <valueField>$Source.ValuePlus__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Add_On_Batch__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/LID__c.field-meta.xml
<CustomField>
    <fullName>LID__c</fullName>
    <label>LID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/ps_LocationUpdateRequired__c.field-meta.xml
<CustomField>
    <fullName>ps_LocationUpdateRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Location Update Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Ready_for_push_to_ProfitStars__c.field-meta.xml
<CustomField>
    <fullName>Ready_for_push_to_ProfitStars__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ready for push to ProfitStars</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/RoutingNo__c.field-meta.xml
<CustomField>
    <fullName>RoutingNo__c</fullName>
    <label>Routing #</label>
    <length>9</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/ValuePlus__c.field-meta.xml
<CustomField>
    <fullName>ValuePlus__c</fullName>
    <label>Value+</label>
    <referenceTo>ValuePlus__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/ValuePlus__c.object-meta.xml
<CustomObject>
    <label>Value+</label>
    <nameField>
        <displayFormat>VAS{000000}</displayFormat>
        <label>Value+</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ValuePlus</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ValuePlus__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Value+</relationshipLabel>
    <relationshipName>Value</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Account_DBA_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_DBA_Name__c</fullName>
    <formula>Account__r.Account_DBA_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account DBA Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/ACH_Type__c.field-meta.xml
<CustomField>
    <fullName>ACH_Type__c</fullName>
    <description>This is the ACH type used by ProfitStars.  1 = ACH Credit, 2 = ACH Debit, 3 = ACH Refund.  The only supported value at this time is ACH Credit.</description>
    <inlineHelpText>This is the ACH type used by ProfitStars.  1 = ACH Credit, 2 = ACH Debit, 3 = ACH Refund.  The only supported value at this time is ACH Credit.</inlineHelpText>
    <label>ACH Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
                <default>true</default>
                <label>2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Number_of_Locations__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Locations__c</fullName>
    <label>Number of Locations</label>
    <summaryFilterItems>
        <field>Bank_Account__c.Status__c</field>
        <operation>notEqual</operation>
        <value>Inactive</value>
    </summaryFilterItems>
    <summaryForeignKey>Bank_Account__c.ValuePlus__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Period_Amount__c.field-meta.xml
<CustomField>
    <fullName>Period_Amount__c</fullName>
    <defaultValue>IF($RecordType.Name = &#39;MyCase Payments&#39;, 68000, NULL)</defaultValue>
    <description>Updated per R152784</description>
    <inlineHelpText>APM Only: Auto calculates to: &#39;Total Rent Roll x 2&#39; when Record Type = APM Payments &amp; Outbound On-Boarding Status=Pending Peer Review. Auto updates only one time upon meeting criteria &amp; can be manually updated before/after auto update.</inlineHelpText>
    <label>Period Amount</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/ps_LocationUpdateRequired__c.field-meta.xml
<CustomField>
    <fullName>ps_LocationUpdateRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ProfitStars Location Update Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sold/Not Started</fullName>
            </value>
            <value>
                <fullName>KOC Confirmed</fullName>
                <label>Questionnaire Received</label>
            </value>
            <value>
                <fullName>Sold/Not Ready</fullName>
            </value>
            <value>
                <fullName>On-Boarding</fullName>
            </value>
            <value>
                <fullName>KOC Scheduled</fullName>
            </value>
            <value>
                <fullName>KOC Complete</fullName>
            </value>
            <value>
                <fullName>Build In Progress</fullName>
            </value>
            <value>
                <fullName>Site Presentation</fullName>
            </value>
            <value>
                <fullName>Site Delivered/Final Changes</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Additional Communication (O)</fullName>
            </value>
            <value>
                <fullName>Agreement Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Content Acquisition</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Deferred-Built</fullName>
            </value>
            <value>
                <fullName>Deferred-Canceled</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Final Changes</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Left APM</fullName>
            </value>
            <value>
                <fullName>Left IM</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Live-Free Trial</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Lost During Pilot</fullName>
            </value>
            <value>
                <fullName>Lost In Onboarding</fullName>
            </value>
            <value>
                <fullName>Multi Site Deffered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Successfully_Enrolled_in_Profit_Stars_at__c.field-meta.xml
<CustomField>
    <fullName>Successfully_Enrolled_in_Profit_Stars_at__c</fullName>
    <description>This field, when populated signifies that the record has been successfully enrolled in profit stars.</description>
    <label>Successfully Enrolled in Profit Stars at</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/PS_BatchLocationUpdatesTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class PS_BatchLocationUpdatesTest {
	
	private Static String validCallJson = '{"san_list":{"NameValue":[{"name":"message","value":"success"},{"name":"GUID","value":"MR-148D2AF4158-117F7368"},{"name":"code","value":"201"}]}}';

    static testmethod void batchLocationUpdateTest(){
		List<Account> a = new List<Account>();
		for (Integer i=0;i<10;i++){
			Account acct = new Account(Name = 'TestAccount' + i);
			a.add(acct);
		}
		insert a;
		system.debug('first account id'+a[0].Id);
		
		ValuePlus__c valuePlus = new ValuePlus__c(Account__c=a[0].Id, ps_LocationUpdateRequired__c = true,
																		Successfully_Enrolled_in_Profit_Stars_at__c=System.today(), recordTypeId = TestUtils.getRecordTypeIdFromSObjectAndName('ValuePlus__c', 'MyCase Payments'));
		insert valuePlus;
		
		Add_On_Batch__c addOnBatch = new Add_On_Batch__c(ValuePlus__c=valuePlus.Id, Stage__c='Ready for Profitstars');
		insert addOnBatch;
		
		Bank_Account__c bankAccount = new Bank_Account__c(ValuePlus__c=valuePlus.Id, Bank_Account_Add_On_Batch__c=addOnBatch.Id, RoutingNo__c='123456789',
																AccountNo__c='12345678912345678',Ready_for_push_to_ProfitStars__c=true);
		insert bankAccount;
		TestUtils.genTestSettings(true);
		
		Test.setMock(HttpCalloutMock.class,
								 new RestClientCalloutMockFactory(200, 'Success', PS_BatchLocationUpdatesTest.validCallJson, null));
		TestUtils.addRequiredFieldToCustomSetting('Location', 'number_of_locations', 'Number_of_Locations__c', true);
		TestUtils.addRequiredFieldToCustomSetting('Location', 'customer_name', 'Account__r.Account_DBA_Name__c', true);
		TestUtils.addRequiredFieldToCustomSetting('Location', 'id', 'id', true);
		TestUtils.addRequiredFieldToCustomSetting('Location', 'location_id', 'Bank_Account__c.LID__c', true, true);
		TestUtils.addRequiredFieldToCustomSetting('Location', 'max_period_amount', 'Period_Amount__c', true);
		TestUtils.addRequiredFieldToCustomSetting('Location', 'max_period_count', 'Number_of_Locations__c', true);
		TestUtils.addRequiredFieldToCustomSetting('Location', 'max_single_day_amount', 'Number_of_Locations__c', true);
		TestUtils.addRequiredFieldToCustomSetting('Location', 'max_single_day_count', 'Number_of_Locations__c', true);
		TestUtils.addRequiredFieldToCustomSetting('Location', 'max_single_trans_amount', 'Number_of_Locations__c', true);
		TestUtils.addRequiredFieldToCustomSetting('Location', 'settlement_type', 'Number_of_Locations__c', '1', true);
		TestUtils.addRequiredFieldToCustomSetting('Location', 'Location settings', 'ACH_Type__c', true);
		TestUtils.addRequiredFieldToCustomSetting('Location', 'routing_number', 'Bank_Account__r.RoutingNo__c', true, false);
		TestUtils.addRequiredFieldToCustomSetting('Location', 'location_name', 'Bank_Account__r.Account_Label__c', true, false);
		
		Test.startTest();
		PS_BatchLocationUpdates l = new PS_BatchLocationUpdates();
		ID batchprocessid = Database.executeBatch(l);
		Test.stopTest();
	}

	static testmethod void batchLocationUpdateExceptionTest(){
		List<Account> a = new List<Account>();
		for (Integer i=0;i<10;i++){
			Account acct = new Account(Name = 'TestAccount' + i);
			a.add(acct);
		}
		insert a;
		system.debug('first account id'+a[0].Id);
		
		ValuePlus__c valuePlus = new ValuePlus__c(Account__c=a[0].Id, ps_LocationUpdateRequired__c = true,
																		Successfully_Enrolled_in_Profit_Stars_at__c=System.today(), recordTypeId = TestUtils.getRecordTypeIdFromSObjectAndName('ValuePlus__c', 'MyCase Payments'));
		insert valuePlus;
		
		Add_On_Batch__c addOnBatch = new Add_On_Batch__c(ValuePlus__c=valuePlus.Id, Stage__c='Ready for Profitstars');
		insert addOnBatch;
		
		Bank_Account__c bankAccount = new Bank_Account__c(ValuePlus__c=valuePlus.Id, Bank_Account_Add_On_Batch__c=addOnBatch.Id, RoutingNo__c='123456789',
																AccountNo__c='12345678912345678',Ready_for_push_to_ProfitStars__c=true);
		// insert bankAccount;
		TestUtils.genTestSettings(true);
		
		Test.setMock(HttpCalloutMock.class,
								 new RestClientCalloutMockFactory(200, 'Success', PS_BatchLocationUpdatesTest.validCallJson, null));
		TestUtils.addRequiredFieldToCustomSetting('Location', 'number_of_locations', 'Number_of_Locations__c', true);
		// TestUtils.addRequiredFieldToCustomSetting('Location', 'customer_name', 'Account__r.Account_DBA_Name__c', true);
		TestUtils.addRequiredFieldToCustomSetting('Location', 'id', 'id', true);
		TestUtils.addRequiredFieldToCustomSetting('Location', 'location_id', 'Bank_Account__c.LID__c', true, true);
		TestUtils.addRequiredFieldToCustomSetting('Location', 'max_period_amount', 'Period_Amount__c', true);
		TestUtils.addRequiredFieldToCustomSetting('Location', 'max_period_count', 'Number_of_Locations__c', true);
		TestUtils.addRequiredFieldToCustomSetting('Location', 'max_single_day_amount', 'Number_of_Locations__c', true);
		TestUtils.addRequiredFieldToCustomSetting('Location', 'max_single_day_count', 'Number_of_Locations__c', true);
		TestUtils.addRequiredFieldToCustomSetting('Location', 'max_single_trans_amount', 'Number_of_Locations__c', true);
		TestUtils.addRequiredFieldToCustomSetting('Location', 'settlement_type', 'Number_of_Locations__c', '1', true);
		TestUtils.addRequiredFieldToCustomSetting('Location', 'Location settings', 'ACH_Type__c', true);
		TestUtils.addRequiredFieldToCustomSetting('Location', 'routing_number', 'Bank_Account__r.RoutingNo__c', true, false);
		TestUtils.addRequiredFieldToCustomSetting('Location', 'location_name', 'Bank_Account__r.Account_Label__c', true, false);
		
		Test.startTest();
		PS_BatchLocationUpdates l = new PS_BatchLocationUpdates();
		ID batchprocessid = Database.executeBatch(l);
		Test.stopTest();
	}
}