unpackaged/main/default/objects/Account/fields/Credit_Card_Stage__c.field-meta.xml
<CustomField>
    <fullName>Credit_Card_Stage__c</fullName>
    <label>Credit Card Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credentialing Complete</fullName>
            </value>
            <value>
                <fullName>Ready to Transmit to Wells Fargo</fullName>
            </value>
            <value>
                <fullName>Transmitted to Wells Fargo</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/ProfitStars_Update_Field__c.field-meta.xml
<CustomField>
    <fullName>ProfitStars_Update_Field__c</fullName>
    <label>ProfitStars Update Field</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Name</fullName>
            </value>
            <value>
                <fullName>Tax ID</fullName>
            </value>
            <value>
                <fullName>Ownership</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Tax_ID__c.field-meta.xml
<CustomField>
    <fullName>Tax_ID__c</fullName>
    <label>Tax ID</label>
    <length>10</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>Used to capture and track customer accounts; if customer is a partner as well, use the Partner record type</description>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000000}</displayFormat>
        <label>Bank Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bank_Account__c/fields/Account_Label__c.field-meta.xml
<CustomField>
    <fullName>Account_Label__c</fullName>
    <label>Account Label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/LID__c.field-meta.xml
<CustomField>
    <fullName>LID__c</fullName>
    <label>LID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Location_Add_Status__c.field-meta.xml
<CustomField>
    <fullName>Location_Add_Status__c</fullName>
    <inlineHelpText>Submitted - ProfitStars is processing the request
Approved - ProfitStars approved the request and provided LID
Completed - LID updated to APM</inlineHelpText>
    <label>Location Add Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Outbound_LID__c.field-meta.xml
<CustomField>
    <fullName>Outbound_LID__c</fullName>
    <description>Created by R163828</description>
    <label>Outbound LID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Outbound_Location_Add_Status__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Location_Add_Status__c</fullName>
    <label>Outbound Location Add Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready To Transmit</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/ps_LocationUpdateRequired__c.field-meta.xml
<CustomField>
    <fullName>ps_LocationUpdateRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Location Update Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Ready_for_push_to_ProfitStars__c.field-meta.xml
<CustomField>
    <fullName>Ready_for_push_to_ProfitStars__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ready for push to ProfitStars</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/ValuePlus__c.field-meta.xml
<CustomField>
    <fullName>ValuePlus__c</fullName>
    <label>Value+</label>
    <referenceTo>ValuePlus__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ProfitStarsIntegration__c/ProfitStarsIntegration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains the needed information to integrate with Profit stars</description>
    <label>Profitstars Integration</label>
</CustomObject>

unpackaged/main/default/objects/PS_Audit_Log__c/PS_Audit_Log__c.object-meta.xml
<CustomObject>
    <label>ProfitStars Callout Audit Log</label>
    <nameField>
        <displayFormat>AuditLog-{000000}</displayFormat>
        <label>ProfitStars Callout Audit Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProfitStars Callout Audit Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PS_Audit_Log__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ProfitStars Callout Audit Logs</relationshipLabel>
    <relationshipName>ProfitStars_Callout_Audit_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PS_Audit_Log__c/fields/BankAccount__c.field-meta.xml
<CustomField>
    <fullName>BankAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>ProfitStars Callout Audit Logs</relationshipLabel>
    <relationshipName>ProfitStars_Callout_Audit_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PS_Audit_Log__c/fields/Call_Type__c.field-meta.xml
<CustomField>
    <fullName>Call_Type__c</fullName>
    <description>What type of call generated this audit log</description>
    <label>Call Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Velocity</fullName>
            </value>
            <value>
                <fullName>Guid</fullName>
            </value>
            <value>
                <fullName>Field Update</fullName>
            </value>
            <value>
                <fullName>Bank Account</fullName>
            </value>
            <value>
                <fullName>Location</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/PS_Audit_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>Api returned the following Error message</description>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/PS_Audit_Log__c/fields/Raw_Json__c.field-meta.xml
<CustomField>
    <fullName>Raw_Json__c</fullName>
    <description>Holds the raw json result of the callout</description>
    <label>Raw Json</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/PS_Audit_Log__c/fields/Value_Plus__c.field-meta.xml
<CustomField>
    <fullName>Value_Plus__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Value+</label>
    <referenceTo>ValuePlus__c</referenceTo>
    <relationshipLabel>ProfitStars Callout Audit Logs</relationshipLabel>
    <relationshipName>ProfitStars_Callout_Audit_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/ValuePlus__c.object-meta.xml
<CustomObject>
    <label>Value+</label>
    <nameField>
        <displayFormat>VAS{000000}</displayFormat>
        <label>Value+</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ValuePlus</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ValuePlus__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Value+</relationshipLabel>
    <relationshipName>Value</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/ActiveDate__c.field-meta.xml
<CustomField>
    <fullName>ActiveDate__c</fullName>
    <label>Active Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Outbound_MID__c.field-meta.xml
<CustomField>
    <fullName>Outbound_MID__c</fullName>
    <description>Created by R152610
Updated By  R163828</description>
    <label>Outbound MID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/ProfitStars_Merchant_ID__c.field-meta.xml
<CustomField>
    <fullName>ProfitStars_Merchant_ID__c</fullName>
    <label>ProfitStars Merchant ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/ps_LocationUpdateRequired__c.field-meta.xml
<CustomField>
    <fullName>ps_LocationUpdateRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ProfitStars Location Update Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sold/Not Started</fullName>
            </value>
            <value>
                <fullName>KOC Confirmed</fullName>
                <label>Questionnaire Received</label>
            </value>
            <value>
                <fullName>Sold/Not Ready</fullName>
            </value>
            <value>
                <fullName>On-Boarding</fullName>
            </value>
            <value>
                <fullName>KOC Scheduled</fullName>
            </value>
            <value>
                <fullName>KOC Complete</fullName>
            </value>
            <value>
                <fullName>Build In Progress</fullName>
            </value>
            <value>
                <fullName>Site Presentation</fullName>
            </value>
            <value>
                <fullName>Site Delivered/Final Changes</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Additional Communication (O)</fullName>
            </value>
            <value>
                <fullName>Agreement Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Content Acquisition</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Deferred-Built</fullName>
            </value>
            <value>
                <fullName>Deferred-Canceled</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Final Changes</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Left APM</fullName>
            </value>
            <value>
                <fullName>Left IM</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Live-Free Trial</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Lost During Pilot</fullName>
            </value>
            <value>
                <fullName>Lost In Onboarding</fullName>
            </value>
            <value>
                <fullName>Multi Site Deffered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Tax_ID__c.field-meta.xml
<CustomField>
    <fullName>Tax_ID__c</fullName>
    <description>Created for request R151946</description>
    <label>Tax ID</label>
    <length>10</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/classes/ProfitStarsUtils_Tests.cls
/*
* Test class for the ProfitStarsUtils class.
*/
@isTest
private class ProfitStarsUtils_Tests{

	// static String validCallJson = '{"CaseNumber": "00001720", "Success": "true"}';
	// static String validLocByLocNameCallJson = '{"HTTPStatusCode":"200","GetLocationByLocationName":{"GetLocationByLocationNameResult":{"AccountNumberLast4":"7891","AccountType":"Checking","CustServProviderId":"654321","CustomerLocationNumber":"true","EntityId":"589885","LocationEnabled":true,"LocationId":"4140829","LocationName":"Test Bank Account0","MerchantName":"Test Account0-a1l4D00000074qDQAQ","RoutingNumber":"053000196"}}}';
	// static String exceptionLocByLocNameCallJson = '{"HTTPStatusCode":null,"GetLocationByLocationName":{"GetLocationByLocationNameResult":{"AccountNumberLast4":"7891","AccountType":"Checking","CustServProviderId":"654321","CustomerLocationNumber":"true","EntityId":"589885","LocationEnabled":true,"LocationId":"4140829","LocationName":"Test Bank Account0","MerchantName":"Test Account0-a1l4D00000074qDQAQ","RoutingNumber":"053000196"}}}';
	// static String emptyJson = '{}';

	// @TestSetup
    // public static void createTestData(){
    // 	TestDataFactory.createCustomSettings();
    // }

	// static testmethod void test_getConfig_Positive(){
	// 	ProfitStarsIntegration__c a = TestUtils.genTestSettings(true);
		
	// 	Test.startTest();
	// 	ProfitStarsIntegration__c config = ProfitStarsUtils.getConfig('APM Payments', null);
	// 	Test.stopTest();
	// 	System.assertNotEquals(config, null, 'Expected to find a valid ProfitStarsIntegration__c object');
	// }

	// static testmethod void test_getConfig_Negative(){
	// 	ProfitStarsIntegration__c a = TestUtils.genTestSettings(true);
		
	// 	Test.startTest();
	// 	ProfitStarsIntegration__c config = ProfitStarsUtils.getConfig('', null);
	// 	Test.stopTest();
	// 	System.assertEquals(config, null, 'Expected to not find a valid ProfitStarsIntegration__c object');
	// }

	// static testmethod void test_ensureTrailingSlash(){
	// 	Test.startTest();
	// 	String withSlash = ProfitStarsUtils.ensureTrailingSlash('this is a test/');
	// 	String withoutSlash = ProfitStarsUtils.ensureTrailingSlash('this is a test');
	// 	Test.stopTest();

	// 	System.assertEquals(withSlash, 'this is a test/');
	// 	System.assertEquals(withoutSlash, 'this is a test/');
	// }

	// static testmethod void test_createAuditLogInRealtime(){
	// 	// going to need valuePlus object, and the object json
	// 	Account a = TestUtils.genAccount(true);
	// 	ValuePlus__c vp = TestUtils.genValuePlus(true, a.id);
	// 	//ps_KeyValueResponse response = ps_KeyValueResponse.parse(ps_KeyValueResp_Tests.json);

	// 	Test.startTest();
	// 	ProfitStarsUtils.createAuditLogInRealtime('velocity', vp.id, JSON.serialize(validCallJson), 'success', 'APM Payments');
	// 	Test.stopTest();

	// 	List<PS_Audit_Log__c> logs = [SELECT Id, Call_type__c, Raw_Json__c, Value_Plus__c, Error_Message__c FROM PS_Audit_Log__c WHERE Value_Plus__c = :vp.id];

	// 	System.assertEquals(1, logs.size());
	// 	TestUtils.assertEqualsCaseIndifferent('Velocity', logs[0].Call_type__c, 'Expected to see calltype of velocity');
	// 	System.assertEquals(vp.id, logs[0].Value_Plus__c, 'Log not properly linked to the value+ object');
	// }

	// static testmethod void test_generateAuditLogForValuePlus(){
		
	// 	Account a = TestUtils.genAccount(true);
	// 	ValuePlus__c vp = TestUtils.genValuePlus(true, a.id);

	// 	Test.startTest();
	// 	PS_Audit_Log__c log = ProfitStarsUtils.generateAuditLogForValuePlus('velocity', 'success', JSON.serialize(validCallJson), vp.Id, 'APM Payments');
	// 	insert log;
	// 	Test.stopTest();

	// 	List<PS_Audit_Log__c> logs = [SELECT Id, Call_type__c, Raw_Json__c, Value_Plus__c, Error_Message__c FROM PS_Audit_Log__c WHERE Value_Plus__c = :vp.id];

	// 	System.assertEquals(1, logs.size());
	// 	TestUtils.assertEqualsCaseIndifferent('Velocity', logs[0].Call_type__c, 'Expected to see calltype of velocity');
	// 	System.assertEquals(vp.id, logs[0].Value_Plus__c, 'Log not properly linked to the value+ object');
	// }

	// static testmethod void test_generateAuditLogForBankAccount(){
		
	// 	Account a = TestUtils.genAccount(true);
	// 	ValuePlus__c vp = TestUtils.genValuePlus(true, a.id);
	// 	Bank_Account__c bank = TestUtils.genBankAccount(true, vp.Id);
	// 	TestUtils.genTestSettings(true);

	// 	Bank_Account__c bankRec = [Select Id, ValuePlus__r.recordType.Name, ValuePlus__r.Account__r.Name from Bank_Account__c where Account_Label__c = 'Test Bank Account0'];

	// 	Test.startTest();
	// 	PS_Audit_Log__c log = ProfitStarsUtils.generateAuditLogForBankAccount('Bank update', 'success', JSON.serialize(validCallJson), bank.Id, 'APM Payments');
	// 	insert log;

	// 	ProfitStarsUtils.sendAddOnErrorEmail(bankRec, 'Bank update', 'success', '200', null);
	// 	Test.stopTest();

	// 	List<PS_Audit_Log__c> logs = [SELECT Id, Call_type__c, Raw_Json__c, BankAccount__c, Error_Message__c FROM PS_Audit_Log__c WHERE BankAccount__c = :bank.id];

	// 	System.assertEquals(1, logs.size());
	// 	TestUtils.assertEqualsCaseIndifferent('Bank update', logs[0].Call_type__c, 'Expected to see calltype of Bank update');
	// 	System.assertEquals(bank.id, logs[0].BankAccount__c, 'Log not properly linked to the bank object');
	// }

	// static testmethod void test_generateAuditLogForAccount(){
		
	// 	Account a = TestUtils.genAccount(true);

	// 	Test.startTest();
	// 	PS_Audit_Log__c log = ProfitStarsUtils.generateAuditLogForAccount('Field Update', 'success', JSON.serialize(validCallJson), a.Id, 'Address', 'APM Payments');
	// 	insert log;
	// 	Test.stopTest();

	// 	List<PS_Audit_Log__c> logs = [SELECT Id, Call_type__c, Raw_Json__c, Account__c, Error_Message__c FROM PS_Audit_Log__c WHERE Account__c = :a.id];

	// 	System.assertEquals(1, logs.size());
	// 	TestUtils.assertEqualsCaseIndifferent('Field Update', logs[0].Call_type__c, 'Expected to see calltype of Bank update');
	// 	System.assertEquals(a.id, logs[0].Account__c, 'Log not properly linked to the account object');
	// }

	// static testmethod void test_createAuditLog(){
		
	// 	Account a = TestUtils.genAccount(true);
	// 	ValuePlus__c vp = TestUtils.genValuePlus(true, a.id);
	// 	TestUtils.genTestSettings(true);

	// 	ValuePlus__c vpRec = [Select Id, recordType.Name, Account__r.Name from ValuePlus__c where Account__r.Name = 'Test Account0' limit 1];

	// 	Test.startTest();
	// 	ProfitStarsUtils.createAuditLog('velocity', vp.Id, 'success', '200', 'APM Payments');
	// 	ProfitStarsUtils.sendErrorEmail(vpRec, 'velocity', 'success', '200', null);
	// 	Test.stopTest();

	// 	List<PS_Audit_Log__c> logs = [SELECT Id, Call_type__c, Raw_Json__c, Value_Plus__c, Error_Message__c FROM PS_Audit_Log__c WHERE Value_Plus__c = :vp.id];

	// 	System.assertEquals(1, logs.size());
	// 	TestUtils.assertEqualsCaseIndifferent('Velocity', logs[0].Call_type__c, 'Expected to see calltype of velocity');
	// 	System.assertEquals(vp.id, logs[0].Value_Plus__c, 'Log not properly linked to the value+ object');
	// }

	// static testmethod void test_sanitizeJson(){
	// 	Test.startTest();
	// 	String sanitized = ProfitStarsUtils.sanitizeJson(ps_KeyValueResp_Tests.json);
	// 	Test.stopTest();

	// 	System.assertNotEquals(sanitized, ps_KeyValueResp_Tests.json, 'Failed to find matching sanitized json');
	// 	System.assert(sanitized.contains('san_'), 'Failed to find sanitization prefix in string representation of json');
	// }

	// static testmethod void test_getRequiredFieldsForCall_valid(){
	// 	TestUtils.addRequiredFieldToCustomSetting('velocity');
	// 	TestUtils.addRequiredFieldToCustomSetting('bank account');
	// 	TestUtils.addRequiredFieldToCustomSetting('location');
	// 	TestUtils.addRequiredFieldToCustomSetting('enrollment');
	// 	Test.startTest();
	// 	Map<String, sObject> reqFieldsVel = ProfitStarsUtils.getRequiredFieldsForCall('velocity');
	// 	Map<String, sObject> reqFieldsBank = ProfitStarsUtils.getRequiredFieldsForCall('bank account');
	// 	Map<String, sObject> reqFieldsLoc = ProfitStarsUtils.getRequiredFieldsForCall('location');
	// 	Map<String, sObject> reqFieldsEnroll = ProfitStarsUtils.getRequiredFieldsForCall('enrollment');
	// 	Test.stopTest();

	// 	System.assert(reqFieldsVel.keyset().size() > 0, 'Failed to acquire fieldset members. Fieldset exists?');
	// 	System.assert(reqFieldsBank.keyset().size() > 0, 'Failed to acquire fieldset members. Fieldset exists?');
	// 	System.assert(reqFieldsLoc.keyset().size() > 0, 'Failed to acquire fieldset members. Fieldset exists?');
	// 	System.assert(reqFieldsEnroll.keyset().size() > 0, 'Failed to acquire fieldset members. Fieldset exists?');
	// }

	// static testmethod void test_getRequiredFieldsForCall_invalid(){
	// 	Boolean didPass = false;
	// 	Test.startTest();
	// 	try {
	// 		Map<String, sObject> reqFields = ProfitStarsUtils.getRequiredFieldsForCall('FOOBAR');
	// 	} catch (ProfitStarsUtils.PSUtilsException e) {
	// 		didPass = true;
	// 	}
	// 	Test.stopTest();

	// 	System.assert(didPass, 'Failed to catch NullPointerException');
	// }

	// static testmethod void test_extractRelatedField_validRelatedField(){
	// 	Account a = TestUtils.genAccount(true);
	// 	ValuePlus__c vp = TestUtils.genValuePlus(true, a.id);
	// 	TestUtils.addRequiredFieldToCustomSetting('velocity');
	// 	Map<String, sObject> reqFields = ProfitStarsUtils.getRequiredFieldsForCall('velocity');
	// 	ValuePlus__c vp2 = ProfitStarsRequestBuilder.getRecord(vp.id, reqFields, 'velocity', null);

	// 	Test.startTest();
	// 	for(String fsm : reqFields.keyset()){
	// 		sObject x = reqFields.get(fsm);
	// 		String results = ProfitStarsUtils.extractRelatedField((String) x.get('Field_Path__c'), vp2, null);
	// 		system.assertNotEquals(null, results, 'Failed to extract the field ' + fsm);
	// 	}
	// 	Test.stopTest();
	// }

	// static testmethod void test_extractRelatedField_echeck(){
	// 	Account a = TestUtils.genAccount(false);
	// 	a.ProfitStars_Update_Field__c = 'Name';
	// 	insert a;

	// 	ValuePlus__c vp = TestUtils.genValuePlus(false, a.id);
	// 	vp.ProfitStars_Merchant_ID__c = '345678';
	// 	vp.Outbound_MID__c = '876543';
	// 	insert vp;

	// 	TestUtils.genOutboundTestSettings(true);
    //     TestUtils.genEcheckFieldsTestSettings(true);
    //     TestUtils.genFieldCustomSetting();

	// 	Map<String, sObject> reqFields = ProfitStarsUtils.getRequiredFieldsForCall('field update');
	// 	ValuePlus__c vp2 = ProfitStarsRequestBuilder.getRecord(vp.id, reqFields, 'field update', 'echeck');

	// 	Test.startTest();
	// 	for(String fsm : reqFields.keyset()){
	// 		sObject x = reqFields.get(fsm);
	// 		if((Boolean) x.get('Required__c')){
	// 			String results = ProfitStarsUtils.extractRelatedField((String) x.get('Field_Path__c'), vp2, 'echeck');
	// 			system.assertNotEquals(null, results, 'Failed to extract the field ' + fsm);
	// 		}
	// 	}
	// 	Test.stopTest();
	// }

	// static testmethod void test_extractRelatedField_InValidRelatedField(){
	// 	Boolean didPass = false;
	// 	Account a = TestUtils.genAccount(true);
	// 	ValuePlus__c vp = TestUtils.genValuePlus(true, a.id);
	// 	TestUtils.addRequiredFieldToCustomSetting('velocity');
	// 	Map<String, sObject> reqFields = ProfitStarsUtils.getRequiredFieldsForCall('velocity');
	// 	ValuePlus__c vp2 = ProfitStarsRequestBuilder.getRecord(vp.id, reqFields, 'velocity', null);

	// 	Test.startTest();
	// 	try {
	// 		String results = ProfitStarsUtils.extractRelatedField('account__r.foobar__c', vp2, null);
	// 	} catch (SObjectException e) {
	// 		didPass = true;
	// 	}
	// 	Test.stopTest();
	// 	System.assert(didPass, 'Expected an NPE to be thrown by extractRelatedField');
	// }

	// static testmethod void test_extractRelatedField_validDirectField(){
	// 	Account a = TestUtils.genAccount(true);
	// 	ValuePlus__c vp = TestUtils.genValuePlus(true, a.id);
	// 	TestUtils.addRequiredFieldToCustomSetting('velocity');
	// 	Map<String, sObject> reqFields = ProfitStarsUtils.getRequiredFieldsForCall('velocity');
	// 	ValuePlus__c vp2 = ProfitStarsRequestBuilder.getRecord(vp.id, reqFields, 'velocity', null);

	// 	Test.startTest();
	// 	String results = ProfitStarsUtils.extractRelatedField('id', vp2, null);
	// 	Test.stopTest();

	// 	system.assertNotEquals(null, results);
	// }

	// static testmethod void test_formatSSN(){
	// 	String ssn = '555112222';
	// 	String formatted = ProfitStarsUtils.formatSSN(ssn);
	// 	System.assertEquals(formatted, '555-11-2222', 'expected a properly formatted ssn');
	// }

	// static testmethod void test_formatTaxId(){
	// 	String d = '445-55-2525 abc';
	// 	String formatted = ProfitStarsUtils.formatTaxId(d);
	// 	system.assertEquals('445552525', formatted, 'expected a properly formatted taxid - just numbers');
	// }

	// static testmethod void test_formatDate(){
	// 	String d = '2014-01-01 17:00:00';
	// 	String formatted = ProfitStarsUtils.formatDate(d);
	// 	system.assertEquals(formatted, '2014-01-01', 'expected a properly formatted date');
	// }

	// static testmethod void test_formatWebsiteurl(){
	// 	String website = 'http://www.google.com';
	// 	String formatted = ProfitStarsUtils.formatWebsiteUrl(website);
	// 	system.assertEquals('google.com', formatted , 'expected formated url');
	// }

	// static testmethod void test_formatWebsiteurlWithoutProtocol(){
	// 	String website = 'www.google.com';
	// 	String formatted = ProfitStarsUtils.formatWebsiteUrl(website);
	// 	system.assertEquals('google.com', formatted , 'expected formated url');
	// }

	// static testmethod void test_formatCustomerNameLongerThan50Chars(){
	// 	String cname = 'Customer Name longer than 50 characters of doom and ruin';
	// 	String formatted = ProfitStarsUtils.formatCustomerName(cname);
	// 	system.assertEquals('Customer Name longer than 50 characters of doom a', formatted , 'expected formated url');
	// }

	// static testmethod void test_formatPhoneNumber(){
	// 	List<String> PhoneNumbers = new List<String>();
	// 	PhoneNumbers.add('9195555555');
	// 	PhoneNumbers.add('919.555.5555');
	// 	PhoneNumbers.add('919 555 5555');
	// 	PhoneNumbers.add('(919) 555-5555');
	// 	PhoneNumbers.add('919-555-5555');

	// 	for (String phoneNum : PhoneNumbers){
	// 		System.assertEquals(ProfitStarsUtils.formatPhoneNumber(phoneNum), '919-555-5555', 'Expected a properly formatted phone #');
	// 	}
	// }

	// static testmethod void test_formatBoolean(){
	// 	List<String> b = new List<String>();
	// 	b.add('TRUE');
	// 	b.add('True');
	// 	b.add('true');

	// 	for (String x : b){
	// 		System.assertEquals(ProfitStarsUtils.formatBoolean(x), '1');
	// 	}

	// 	b = new List<String>();
	// 	b.add('false');
	// 	b.add('False');
	// 	b.add('FALSE');

	// 	for (String x : b){
	// 		System.assertEquals(ProfitStarsUtils.formatBoolean(x), '0');
	// 	}
	// }
	
	// static testmethod void test_profitStarsFormat1(){

	// 	Account acct = TestUtils.genAccount(false);
	// 	acct.Credit_Card_Stage__c = 'Credentialing Complete';
	// 	acct.Tax_ID__c = '123456789';
	// 	insert acct;

	// 	ValuePlus__c valuePlus = TestUtils.genValuePlus(false, acct.id);
	// 	valuePlus.ActiveDate__c = Date.today();
	// 	insert valuePlus;
		
	// 	ValuePlus__c vp = [select Id, Account__r.Tax_ID__c, Stage__c from ValuePlus__c LIMIT 1];
		
	// 	System.assertEquals(ProfitStarsUtils.profitStarsFormat('description', 'Account__r.Tax_ID__c', vp, null), acct.Tax_ID__c);
	// 	System.assertEquals(ProfitStarsUtils.profitStarsFormat('Stage__c', vp.Stage__c, vp, null), valuePlus.Stage__c);
	// }
	
	// static testmethod void test_profitStarsFormat(){
	// 	Map<String, String> data = new Map<String, String>();
	// 	Map<String, String> results = new Map<String, String>();
	// 	data.put('state', 'Alabama');
	// 	data.put('PhoneNumber', '9193817128');
	// 	data.put('FaxNumber', '9193817128');
	// 	data.put('CustomerServicePhoneNumber', '9193817128');
	// 	data.put('websiteUrl', 'http://www.google.com');
	// 	data.put('PrimaryOfficerSSN', '222114444');
	// 	data.put('SecondaryOfficerSSN', '222114444');
	// 	data.put('ApplicationCertificationAgreement', 'true');
	// 	data.put('PrimaryOfficerDOB', '2014-01-01 17:00:00');
	// 	data.put('SecondaryOfficerDOB', '2013-01-01 17:00:00');

	// 	results.put('state', 'Al');
	// 	results.put('PhoneNumber', '919-381-7128');
	// 	results.put('FaxNumber', '919-381-7128');
	// 	results.put('CustomerServicePhoneNumber', '919-381-7128');
	// 	results.put('websiteUrl', 'google.com');
	// 	results.put('PrimaryOfficerSSN', '222-11-4444');
	// 	results.put('SecondaryOfficerSSN', '222-11-4444');
	// 	results.put('ApplicationCertificationAgreement', '1');
	// 	results.put('PrimaryOfficerDOB', '2014-01-01');
	// 	results.put('SecondaryOfficerDOB', '2013-01-01');

	// 	for (String key : data.keySet()){
	// 		System.assertEquals(
	// 			ProfitStarsUtils.profitStarsFormat(key, data.get(key)),
	// 			results.get(key),
	// 			'Failed to find a properly formatted string!');
	// 	}
	// }

	// static testmethod void fetchBankAccountToUpdateTest(){
	// 	Account a = TestUtils.genAccount(true);
	// 	ValuePlus__c vp = TestUtils.genValuePlus(true, a.id);
	// 	Bank_Account__c bank = TestUtils.genBankAccount(true, vp.Id);

	// 	Bank_Account__c bankRec = [Select Id, Location_Add_Status__c, LID__c, ps_LocationUpdateRequired__c, Ready_for_push_to_ProfitStars__c from Bank_Account__c where Account_Label__c = 'Test Bank Account0'];

	// 	Test.startTest();
	// 	ProfitStarsUtils.fetchBankAccountToUpdate(bankRec, validLocByLocNameCallJson);
	// 	Test.stopTest();

	// 	System.assertEquals('Approved', bankRec.Location_Add_Status__c);
	// }

	// static testmethod void fetchBankAccountToUpdateExceptionTest(){
	// 	Account a = TestUtils.genAccount(true);
	// 	ValuePlus__c vp = TestUtils.genValuePlus(true, a.id);
	// 	Bank_Account__c bank = TestUtils.genBankAccount(true, vp.Id);
	// 	Boolean didPass = false;

	// 	Bank_Account__c bankRec = [Select Id, Location_Add_Status__c, LID__c, ps_LocationUpdateRequired__c, Ready_for_push_to_ProfitStars__c from Bank_Account__c where Account_Label__c = 'Test Bank Account0'];

	// 	Test.startTest();
	// 	try{
	// 		ProfitStarsUtils.fetchBankAccountToUpdate(bankRec, exceptionLocByLocNameCallJson);
	// 	} catch(Exception ex){
	// 		didPass = true;
	// 	}
	// 	Test.stopTest();

	// 	System.assert(didPass, 'Expected an exception to be thrown!');
	// }

	// static testmethod void fetchBankAccountToUpdateEmptyExceptionTest(){
	// 	Account a = TestUtils.genAccount(true);
	// 	ValuePlus__c vp = TestUtils.genValuePlus(true, a.id);
	// 	Bank_Account__c bank = TestUtils.genBankAccount(true, vp.Id);
	// 	Boolean didPass = false;

	// 	Bank_Account__c bankRec = [Select Id, Location_Add_Status__c, LID__c, ps_LocationUpdateRequired__c, Ready_for_push_to_ProfitStars__c from Bank_Account__c where Account_Label__c = 'Test Bank Account0'];

	// 	Test.startTest();
	// 	try{
	// 		ProfitStarsUtils.fetchBankAccountToUpdate(bankRec, emptyJson);
	// 	} catch(Exception ex){
	// 		didPass = true;
	// 	}
	// 	Test.stopTest();

	// 	System.assert(didPass, 'Expected an exception to be thrown!');
	// }

	// static testmethod void fetchBankAccountToUpdateOBTest(){
	// 	Account a = TestUtils.genAccount(true);
	// 	ValuePlus__c vp = TestUtils.genValuePlus(true, a.id);
	// 	Bank_Account__c bank = TestUtils.genBankAccount(true, vp.Id);

	// 	Bank_Account__c bankRec = [Select Id, Outbound_Location_Add_Status__c, Outbound_LID__c from Bank_Account__c where Account_Label__c = 'Test Bank Account0'];

	// 	Test.startTest();
	// 	ProfitStarsUtils.fetchBankAccountToUpdateOutbound(bankRec, validLocByLocNameCallJson);
	// 	Test.stopTest();

	// 	System.assertEquals('Approved', bankRec.Outbound_Location_Add_Status__c);
	// }

	// static testmethod void fetchBankAccountToUpdateOBExceptionTest(){
	// 	Account a = TestUtils.genAccount(true);
	// 	ValuePlus__c vp = TestUtils.genValuePlus(true, a.id);
	// 	Bank_Account__c bank = TestUtils.genBankAccount(true, vp.Id);
	// 	Boolean didPass = false;

	// 	Bank_Account__c bankRec = [Select Id, Outbound_Location_Add_Status__c, Outbound_LID__c from Bank_Account__c where Account_Label__c = 'Test Bank Account0'];

	// 	Test.startTest();
	// 	try{
	// 		ProfitStarsUtils.fetchBankAccountToUpdateOutbound(bankRec, exceptionLocByLocNameCallJson);
	// 	} catch(Exception ex){
	// 		didPass = true;
	// 	}
	// 	Test.stopTest();

	// 	System.assert(didPass, 'Expected an exception to be thrown!');
	// }

	// static testmethod void fetchBankAccountToUpdateOBEmptyExceptionTest(){
	// 	Account a = TestUtils.genAccount(true);
	// 	ValuePlus__c vp = TestUtils.genValuePlus(true, a.id);
	// 	Bank_Account__c bank = TestUtils.genBankAccount(true, vp.Id);
	// 	Boolean didPass = false;

	// 	Bank_Account__c bankRec = [Select Id, Outbound_Location_Add_Status__c, Outbound_LID__c from Bank_Account__c where Account_Label__c = 'Test Bank Account0'];

	// 	Test.startTest();
	// 	try{
	// 		ProfitStarsUtils.fetchBankAccountToUpdateOutbound(bankRec, emptyJson);
	// 	} catch(Exception ex){
	// 		didPass = true;
	// 	}
	// 	Test.stopTest();

	// 	System.assert(didPass, 'Expected an exception to be thrown!');
	// }

	/*static testmethod void PSBatchSchedulable_OmnibusTest(){

		Test.startTest();
		PSBatchSchedulable_Omnibus.start();
		Test.stopTest();

		List<CronTrigger> ctList = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger];
		System.assertNotEquals(0, ctList.size());
	}*/
}