unpackaged/main/default/objects/Account/fields/Key_Account__c.field-meta.xml
<CustomField>
    <fullName>Key_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This account has been identified as one of Morgan&#39;s strategic accounts.</inlineHelpText>
    <label>Strategic Account</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/RPM__c.field-meta.xml
<CustomField>
    <fullName>RPM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>RPM</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Suspicious_Account__c.field-meta.xml
<CustomField>
    <fullName>Suspicious_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Suspicious Account</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>Used to capture and track customer accounts; if customer is a partner as well, use the Partner record type</description>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/objects/Asset/fields/Customer_APM_Version__c.field-meta.xml
<CustomField>
    <fullName>Customer_APM_Version__c</fullName>
    <description>PM; R1814517, R2026455; Edited: Users</description>
    <label>Customer APM Version</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APM</fullName>
            </value>
            <value>
                <fullName>APM+</fullName>
            </value>
            <value>
                <fullName>APM+ Product Only</fullName>
            </value>
            <value>
                <fullName>APM+ Service Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Dedicated_Success_Manager__c.field-meta.xml
<CustomField>
    <fullName>Dedicated_Success_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PM, IM; R1915756, R1917381; Edited: Auto, Users</description>
    <label>Dedicated Success Manager</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot add community user to dedicated success manager field</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>notContain</operation>
            <value>HelpCenter, Communit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Assets_DedicatedSuccessManager</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Key_Account__c.field-meta.xml
<CustomField>
    <fullName>Key_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PM; R1917381, Edited: users</description>
    <label>Key Account</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Strategic_Relationship_Manager__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Relationship_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PM; R1916244; Edited: users</description>
    <label>Strategic Relationship Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assets_Strategic_Relationship_Manager</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Database__c.field-meta.xml
<CustomField>
    <fullName>Database__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prod Database</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Database MUST be production and MUST be for Property Manager.  If one does not exist, please populate Non-Prod Database Field or check No Database Exists checkbox.</errorMessage>
        <filterItems>
            <field>Database__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Database__c.Type__c</field>
            <operation>equals</operation>
            <value>Production</value>
        </filterItems>
        <filterItems>
            <field>Database__c.Application_Name__c</field>
            <operation>equals</operation>
            <value>property</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Database__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Risk.recordType-meta.xml
<RecordType>
    <fullName>Risk</fullName>
    <active>true</active>
    <businessProcess>Risk</businessProcess>
    <description>Case Record Type to track risky behavior</description>
    <label>Risk</label>
</RecordType>

unpackaged/main/default/objects/Database__c/Database__c.object-meta.xml
<CustomObject>
    <label>Database</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Databases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Database__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Databases</relationshipLabel>
    <relationshipName>Databases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Database__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <description>Created for R1814517; Modified for R1915156; Modified for R1916668, R1922477</description>
    <label>Asset</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Asset.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Databases</relationshipLabel>
    <relationshipName>Databases</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/GIACTIdentifyResponses__c/GIACTIdentifyResponses__c.object-meta.xml
<CustomObject>
    <label>GIACT Identify Response</label>
    <nameField>
        <displayFormat>GID-{0000}</displayFormat>
        <label>GIACT Identify Responses Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GIACT Identify Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GIACTIdentifyResponses__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GIACTIdentifyResponses__c/fields/ValuePlus__c.field-meta.xml
<CustomField>
    <fullName>ValuePlus__c</fullName>
    <label>Value+</label>
    <referenceTo>ValuePlus__c</referenceTo>
    <relationshipLabel>GIACT Identify Responses</relationshipLabel>
    <relationshipName>GIACT_Identify_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/GIdentifyEntityInformation__c/GIdentifyEntityInformation__c.object-meta.xml
<CustomObject>
    <label>GIdentifyEntityInformation</label>
    <nameField>
        <label>GIdentifyEntityInformation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GIdentifyEntityInformations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GIdentifyEntityInformation__c/fields/Fraud_Activity_Found__c.field-meta.xml
<CustomField>
    <fullName>Fraud_Activity_Found__c</fullName>
    <defaultValue>false</defaultValue>
    <description>R1917612</description>
    <label>Fraud Activity Found</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/GIdentifyEntityInformation__c/fields/GIACTIdentifyResponse__c.field-meta.xml
<CustomField>
    <fullName>GIACTIdentifyResponse__c</fullName>
    <label>GIACT Identify Response</label>
    <referenceTo>GIACTIdentifyResponses__c</referenceTo>
    <relationshipLabel>GIdentifyEntityInformations</relationshipLabel>
    <relationshipName>GIdentifyEntityInformations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/System_Exception_Log__c/System_Exception_Log__c.object-meta.xml
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <label>System Exception Log</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ValuePlus__c/ValuePlus__c.object-meta.xml
<CustomObject>
    <label>Value+</label>
    <nameField>
        <displayFormat>VAS{000000}</displayFormat>
        <label>Value+</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ValuePlus</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ValuePlus__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Value+</relationshipLabel>
    <relationshipName>Value</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/classes/CustomerAlertsTest.cls
/*
* Test class for the CustomerAlerts class.
*/
@isTest
private class CustomerAlertsTest{

    @TestSetup
    private static void createTestData(){
        TestDataFactory.createCustomSettings();

        TestDataFactory.DataModel dm = new TestDataFactory.DataModel(1, false);
        //insert accounts
        // dm.accountList[0].RecordTypeId = InformationStrings.accountPropertyManagementId;
        dm.accountList[0].Name = 'TestAcct';
        INSERT(dm.accountList);

        //insert asset
        dm.assetList[0].AccountId = dm.accountList[0].Id;
        INSERT(dm.assetList);

        //insert database
        dm.databaseList[0].Account__c = dm.accountList[0].Id;
        dm.databaseList[0].Asset__c = dm.assetList[0].Id;
        INSERT(dm.databaseList);

        TestDataFactory.createEntitlements(dm.accountList[0].Id, true);
    }

    static testMethod void testAccountWithCaseRTC(){
       
       Account newAcct = [Select Id, RecordTypeId from Account where name = 'TestAcct' limit 1];
       
       Database__c database = [Select Id from Database__c where Account__c = :newAcct.id limit 1];
		
       Case ca1 = new Case(
                AccountId = newAcct.Id,
                RecordTypeId = InformationStrings.caseRiskId,
                Origin = 'Email',
                Status = 'New',
                Reason = 'Implementation Expectations',
                Case_Sub_Reason__c = 'Expect a Specific GL Date',
                Database__c = database.Id,
                Priority = 'Normal'
         	);
        
        Case ca2 = new Case(
                AccountId = newAcct.Id,
                RecordTypeId = InformationStrings.caseRiskId,
                Origin = 'Email',
                Status = 'New',
                Reason = 'Implementation Expectations',
                Case_Sub_Reason__c = 'Expect a Specific GL Date',
                Database__c = database.Id,
                Priority = 'Request to Cancel'
         	);
         
        List<Case> listCases = new List<Case>{ca1, ca2};
        insert listCases;
        
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(newAcct);
        CustomerAlerts ca = new CustomerAlerts(sc);
        System.assert(ca.warningMessages != null && ca.warningMessages.size() > 0);
        System.assert(ca.warningMessages[0].containsIgnoreCase('requested to cancel'));
        Test.stopTest();
    }
    
    static testMethod void testAccountWithMultipleOpenCases(){

       Account newAcct = [Select Id, RecordTypeId from Account where name = 'TestAcct' limit 1];
       
       Database__c database = [Select Id from Database__c where Account__c = :newAcct.id limit 1];
		
       Case ca1 = new Case(
                AccountId = newAcct.Id,
                RecordTypeId = InformationStrings.caseRiskId,
                Origin = 'Email',
                Status = 'New',
                Reason = 'Implementation Expectations',
                Case_Sub_Reason__c = 'Expect a Specific GL Date',
                Database__c = database.Id,
                Priority = 'Normal'
         	);
        
        Case ca2 = new Case(
                AccountId = newAcct.Id,
                RecordTypeId = InformationStrings.caseRiskId,
                Origin = 'Email',
                Status = 'New',
                Reason = 'Implementation Expectations',
                Case_Sub_Reason__c = 'Expect a Specific GL Date',
                Database__c = database.Id,
                Priority = 'Low'
         	);
         
        List<Case> listCases = new List<Case>{ca1, ca2};
        insert listCases;
        
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(newAcct);
        CustomerAlerts ca = new CustomerAlerts(sc);
        System.assert(ca.warningMessages != null && ca.warningMessages.size() == 1);
        System.assert(ca.warningMessages[0].containsIgnoreCase('open risk case'));
        Test.stopTest();
    }
    
    static testMethod void testVPWithCaseRTC(){

       Account newAcct = [Select Id, RecordTypeId from Account where name = 'TestAcct' limit 1];
       
       Database__c database = [Select Id from Database__c where Account__c = :newAcct.id limit 1];
		
	   ValuePlus__c valuePlus = TestDataFactory.createValuePlusList(1, newAcct.Id, true)[0];
		
       Case ca1 = new Case(
                AccountId = newAcct.Id,
                RecordTypeId = InformationStrings.caseRiskId,
                Origin = 'Email',
                Status = 'New',
                Reason = 'Implementation Expectations',
                Case_Sub_Reason__c = 'Expect a Specific GL Date',
                Database__c = database.Id,
                Priority = 'Normal'
         	);
        
        Case ca2 = new Case(
                AccountId = newAcct.Id,
                RecordTypeId = InformationStrings.caseRiskId,
                Origin = 'Email',
                Status = 'New',
                Reason = 'Implementation Expectations',
                Case_Sub_Reason__c = 'Expect a Specific GL Date',
                Database__c = database.Id,
                Priority = 'Request to Cancel'
         	);
         
        List<Case> listCases = new List<Case>{ca1, ca2};
        insert listCases;
        
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(valuePlus);
        CustomerAlerts ca = new CustomerAlerts(sc);
        System.assert(ca.warningMessages != null && ca.warningMessages.size() > 0);
        System.assert(ca.warningMessages[0].containsIgnoreCase('requested to cancel'));
        Test.stopTest();
    }
    
    static testMethod void testVPWithMultipleOpenCases(){

       Account newAcct = [Select Id, RecordTypeId from Account where name = 'TestAcct' limit 1];
       
       Database__c database = [Select Id from Database__c where Account__c = :newAcct.id limit 1];
        
       ValuePlus__c valuePlus = TestDataFactory.createValuePlusList(1, newAcct.Id, true)[0];
        
       Case ca1 = new Case(
                AccountId = newAcct.Id,
                RecordTypeId = InformationStrings.caseRiskId,
                Origin = 'Email',
                Status = 'New',
                Reason = 'Implementation Expectations',
                Case_Sub_Reason__c = 'Expect a Specific GL Date',
                Database__c = database.Id,
                Priority = 'Normal'
         	);
        
        Case ca2 = new Case(
                AccountId = newAcct.Id,
                RecordTypeId = InformationStrings.caseRiskId,
                Origin = 'Email',
                Status = 'New',
                Reason = 'Implementation Expectations',
                Case_Sub_Reason__c = 'Expect a Specific GL Date',
                Database__c = database.Id,
                Priority = 'Noral'
         	);
         
        List<Case> listCases = new List<Case>{ca1, ca2};
        insert listCases;
        
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(valuePlus);
        CustomerAlerts ca = new CustomerAlerts(sc);
        System.assert(ca.warningMessages != null && ca.warningMessages.size() == 1);
        System.assert(ca.warningMessages[0].containsIgnoreCase('open risk case'));
        Test.stopTest();
    }
    
    static testMethod void testCasesWithCaseRTC(){

       Account newAcct = [Select Id, RecordTypeId from Account where name = 'TestAcct' limit 1];
       
       Database__c database = [Select Id from Database__c where Account__c = :newAcct.id limit 1];
		
       Case ca1 = new Case(
                AccountId = newAcct.Id,
                RecordTypeId = InformationStrings.caseRiskId,
                Origin = 'Email',
                Status = 'New',
                Reason = 'Implementation Expectations',
                Case_Sub_Reason__c = 'Expect a Specific GL Date',
                Database__c = database.Id,
                Priority = 'Normal'
         	);
        
        Case ca2 = new Case(
                AccountId = newAcct.Id,
                RecordTypeId = InformationStrings.caseRiskId,
                Origin = 'Email',
                Status = 'New',
                Reason = 'Implementation Expectations',
                Case_Sub_Reason__c = 'Expect a Specific GL Date',
                Database__c = database.Id,
                Priority = 'Request to Cancel'
         	);
         
        List<Case> listCases = new List<Case>{ca1, ca2};
        insert listCases;
        
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(ca1);
        CustomerAlerts ca = new CustomerAlerts(sc);
        System.assert(ca.warningMessages != null && ca.warningMessages.size() > 0);
        System.assert(ca.warningMessages[0].containsIgnoreCase('requested to cancel'));
        Test.stopTest();
    }
    
    static testMethod void testCasesWithMultipleOpenCases(){

       Account newAcct = [Select Id, RecordTypeId from Account where name = 'TestAcct' limit 1];
       
       Database__c database = [Select Id from Database__c where Account__c = :newAcct.id limit 1];
        
       Case ca1 = new Case(
                AccountId = newAcct.Id,
                RecordTypeId = InformationStrings.caseRiskId,
                Origin = 'Email',
                Status = 'New',
                Reason = 'Implementation Expectations',
                Case_Sub_Reason__c = 'Expect a Specific GL Date',
                Database__c = database.Id,
                Priority = 'Normal'
         	);
        
        Case ca2 = new Case(
                AccountId = newAcct.Id,
                RecordTypeId = InformationStrings.caseRiskId,
                Origin = 'Email',
                Status = 'New',
                Reason = 'Implementation Expectations',
                Case_Sub_Reason__c = 'Expect a Specific GL Date',
                Database__c = database.Id,
                Priority = 'Low'
         	);
         
        List<Case> listCases = new List<Case>{ca1, ca2};
        insert listCases;
        
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(ca1);
        CustomerAlerts ca = new CustomerAlerts(sc);
        System.assert(ca.warningMessages != null && ca.warningMessages.size() == 1);
        System.assert(ca.warningMessages[0].containsIgnoreCase('open risk case'));
        Test.stopTest();
    }

    static testMethod void testMyCaseAccount(){

        Account newAcct = TestDataFactory.createAccountList(1, false)[0];
        newAcct.RecordTypeId = InformationStrings.accountCustomerId;
        newAcct.Name = 'TestMyCaseAcct';
        newAcct.Suspicious_Account__c = true;
        insert newAcct;

        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(newAcct);
        CustomerAlerts ca = new CustomerAlerts(sc);
        // System.assertEquals(true, ca.isMyCaseRecord);
        Test.stopTest();
    }

    static testMethod void testMyCaseValuePlus(){

        Account newAcct = TestDataFactory.createAccountList(1, false)[0];
        newAcct.RecordTypeId = InformationStrings.accountCustomerId;
        newAcct.Name = 'TestMyCaseAcct';
        insert newAcct;

        ValuePlus__c valuePlus = TestDataFactory.createValuePlusList(1, newAcct.Id, true)[0];

        ValuePlus__c valuePlusRec = [Select id, Account__c, Account__r.RecordTypeId from ValuePlus__c where id = :valuePlus.id];

        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(valuePlusRec);
        CustomerAlerts ca = new CustomerAlerts(sc);
        System.assertEquals(true, ca.isMyCaseRecord);
        Test.stopTest();
    }

    static testMethod void testMyCaseCases(){
        Account newAcct = [Select Id, RecordTypeId from Account where name = 'TestAcct' limit 1];
        newAcct.RecordTypeId = InformationStrings.accountCustomerId;
        update newAcct;

        Database__c database = [Select Id from Database__c where Account__c = :newAcct.id limit 1];

        Case c = new Case(
                AccountId = newAcct.Id,
                RecordTypeId = InformationStrings.caseRiskId,
                Origin = 'Email',
                Status = 'New',
                Reason = 'Implementation Expectations',
                Case_Sub_Reason__c = 'Expect a Specific GL Date',
                Database__c = database.Id,
                Priority = 'Normal'
        );
        insert c;

        Case caseRec = [Select id, Account.RecordTypeId from Case where id = :c.id];

        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(caseRec);
        CustomerAlerts ca = new CustomerAlerts(sc);
        System.assertEquals(true, ca.isMyCaseRecord);
        Test.stopTest();
    }

    static testMethod void testMyCaseOpportunity(){

        Account newAcct = [Select Id, RecordTypeId from Account where name = 'TestAcct' limit 1];
        newAcct.RecordTypeId = InformationStrings.accountCustomerId;
        update newAcct;

        Opportunity newOpp = new Opportunity(
                // RecordTypeId = InformationStrings.opportunityMyCaseValueId,
                StageName = 'Discovery',
                CloseDate = System.today() + 30,
                AccountId = newAcct.Id,
                Name = 'Test Opportunity'
        );
        insert newOpp;

        opportunity newOppRec = [Select id, RecordTypeId, StageName, AccountId, Account.RecordTypeId from Opportunity where id = :newOpp.id];

        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(newOppRec);
        CustomerAlerts ca = new CustomerAlerts(sc);
        System.assertEquals(true, ca.isMyCaseRecord);
        Test.stopTest();
    }

    static testMethod void testVPWithGiactFraudResponse(){

       Account newAcct = [Select Id, RecordTypeId from Account where name = 'TestAcct' limit 1];
       
       Database__c database = [Select Id from Database__c where Account__c = :newAcct.id limit 1];
        
       ValuePlus__c valuePlus = TestDataFactory.createValuePlusList(1, newAcct.Id, true)[0];

       GIACTIdentifyResponses__c gIdentifyResp = new GIACTIdentifyResponses__c(
                        ValuePlus__c = valuePlus.Id,
                        Message__c = 'Test'
       );
       insert gIdentifyResp;

       GIdentifyEntityInformation__c gEntityInfo = new GIdentifyEntityInformation__c(
                        GIACTIdentifyResponse__c = gIdentifyResp.Id,
                        Fraud_Activity_Found__c = true
       );
       insert gEntityInfo;
        
       Test.startTest();
       ApexPages.StandardController sc = new ApexPages.StandardController(valuePlus);
       CustomerAlerts ca = new CustomerAlerts(sc);
       System.assert(ca.fraudMsg != null);
       Test.stopTest();
    }

    static testMethod void testPlusClientonAccount(){
       
       User adUser = TestDataFactory.createAdminUser(true);

       Account newAcct = [Select Id, RecordTypeId from Account where name = 'TestAcct' limit 1];

       Asset ast = [Select Id from Asset where AccountId = :newAcct.Id limit 1];
    //    ast.RecordTypeId = InformationStrings.assetPropertyManagementId;
       ast.Status = 'Customer';
       ast.Customer_APM_Version__c = 'APM+';
       ast.Dedicated_Success_Manager__c = adUser.Id;
       ast.Strategic_Relationship_Manager__c = adUser.Id;
       update ast;

       Test.startTest();
       ApexPages.StandardController sc = new ApexPages.StandardController(newAcct);
       CustomerAlerts ca = new CustomerAlerts(sc);
       Test.stopTest();

       System.assert(ca.plusClientMsg != null);
       System.assert(ca.plusClientMsg.containsIgnoreCase('PLUS Client'));
    }

    static testMethod void testPlusClientonAsset(){
       
       User adUser = TestDataFactory.createAdminUser(true);

       Account newAcct = [Select Id, RecordTypeId from Account where name = 'TestAcct' limit 1];

       Asset ast = [Select Id from Asset where AccountId = :newAcct.Id limit 1];
    //    ast.RecordTypeId = InformationStrings.assetPropertyManagementId;
       ast.Status = 'Customer';
       ast.Customer_APM_Version__c = 'APM+';
       ast.Dedicated_Success_Manager__c = adUser.Id;
       ast.Strategic_Relationship_Manager__c = adUser.Id;
       update ast;

       Test.startTest();
       ApexPages.StandardController sc = new ApexPages.StandardController(ast);
       CustomerAlerts ca = new CustomerAlerts(sc);
       Test.stopTest();

    //    System.assert(ca.plusClientMsg != null);
    //    System.assert(ca.plusClientMsg.containsIgnoreCase('PLUS Client'));
    }

    static testMethod void testKeyAccountClientonAsset(){
       
        User adUser = TestDataFactory.createAdminUser(true);
 
        Account newAcct = [Select Id, RecordTypeId from Account where name = 'TestAcct' limit 1];
 
        Asset ast = [Select Id from Asset where AccountId = :newAcct.Id limit 1];
        // ast.RecordTypeId = InformationStrings.assetPropertyManagementId;
        ast.Key_Account__c = True;
        ast.Customer_APM_Version__c = 'APM';
        update ast;
 
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(newAcct);
        CustomerAlerts ca = new CustomerAlerts(sc);
        Test.stopTest();
 
        System.assert(ca.plusClientMsg != null);
        System.assert(ca.plusClientMsg.containsIgnoreCase('Key Account Client'));
     }


     static testMethod void testRPMClient(){
       
        User adUser = TestDataFactory.createAdminUser(true);
 
        Account newAcct = [Select Id, RecordTypeId from Account where name = 'TestAcct' limit 1];
        newAcct.RPM__c = True;
        update newAcct;

        Asset ast = [Select Id from Asset where AccountId = :newAcct.Id limit 1];
        // ast.RecordTypeId = InformationStrings.assetPropertyManagementId;
        ast.Status = 'Customer';
        ast.Customer_APM_Version__c = 'APM';
        update ast;
 
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(newAcct);
        CustomerAlerts ca = new CustomerAlerts(sc);
        Test.stopTest();
 
        System.assert(ca.plusClientMsg != null);
        System.assert(ca.plusClientMsg.containsIgnoreCase('RPM Client'));
     }

    private static testMethod void testExceptions(){

        Account newAcct = [Select Id, RecordTypeId from Account where name = 'TestAcct' limit 1];

        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(newAcct);
        CustomerAlerts ca = new CustomerAlerts(sc);
        ca.getAlertsforAccount(null);
        ca.getAlertsforValuePlus(null);
        ca.getAlertsforCase(null);
        ca.getAlertsforOpportunity(null);
        ca.getAlertsforAsset(null);
        Test.stopTest();

        System.assert([SELECT COUNT() FROM System_Exception_Log__c ] > 0);
    }
}