unpackaged/main/default/objects/Account/fields/Ownership_Type__c.field-meta.xml
<CustomField>
    <fullName>Ownership_Type__c</fullName>
    <description>Updated R1813846</description>
    <label>Ownership Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sole Proprietor</fullName>
            </value>
            <value>
                <fullName>Partnership</fullName>
            </value>
            <value>
                <fullName>Limited Liability Partnership</fullName>
            </value>
            <value>
                <fullName>Corporation</fullName>
            </value>
            <value>
                <fullName>LLC</fullName>
            </value>
            <value>
                <fullName>Single Member LLC</fullName>
            </value>
            <value>
                <fullName>S Corporation</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Trust</fullName>
            </value>
            <value>
                <fullName>Publicly Traded Corporation</fullName>
            </value>
            <value>
                <fullName>Non Profit</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Acquired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Principal_1_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Principal_1_First_Name__c</fullName>
    <label>Principal 1 First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Principal_1_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Principal_1_Last_Name__c</fullName>
    <label>Principal 1 Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Principal_1_Ownership__c.field-meta.xml
<CustomField>
    <fullName>Principal_1_Ownership__c</fullName>
    <label>Principal 1 Ownership</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Principal_1_SSN__c.field-meta.xml
<CustomField>
    <fullName>Principal_1_SSN__c</fullName>
    <label>Principal 1 SSN</label>
    <length>11</length>
    <maskChar>asterisk</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Principal_2_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Principal_2_First_Name__c</fullName>
    <label>Principal 2 First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Principal_2_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Principal_2_Last_Name__c</fullName>
    <label>Principal 2 Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Principal_2_Ownership__c.field-meta.xml
<CustomField>
    <fullName>Principal_2_Ownership__c</fullName>
    <label>Principal 2 Ownership</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Principal_2_SSN__c.field-meta.xml
<CustomField>
    <fullName>Principal_2_SSN__c</fullName>
    <label>Principal 2 SSN</label>
    <length>11</length>
    <maskChar>asterisk</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ProfitStars_Update_Field__c.field-meta.xml
<CustomField>
    <fullName>ProfitStars_Update_Field__c</fullName>
    <label>ProfitStars Update Field</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Name</fullName>
            </value>
            <value>
                <fullName>Tax ID</fullName>
            </value>
            <value>
                <fullName>Ownership</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/ps_UpdateRequired__c.field-meta.xml
<CustomField>
    <fullName>ps_UpdateRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Profit Stars Update Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000000}</displayFormat>
        <label>Bank Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bank_Account__c/fields/Account_Label__c.field-meta.xml
<CustomField>
    <fullName>Account_Label__c</fullName>
    <label>Account Label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>This is the bank account type.  0 = Checking, 1 = Savings.  Currently only Checking is supported.</description>
    <inlineHelpText>This is the bank account type.  0 = Checking, 1 = Savings.  Currently only Checking is supported.</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <default>true</default>
                <label>0</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/AccountNo__c.field-meta.xml
<CustomField>
    <fullName>AccountNo__c</fullName>
    <label>Account #</label>
    <length>17</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/LID__c.field-meta.xml
<CustomField>
    <fullName>LID__c</fullName>
    <label>LID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/ps_LocationUpdateRequired__c.field-meta.xml
<CustomField>
    <fullName>ps_LocationUpdateRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Location Update Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Ready_for_push_to_ProfitStars__c.field-meta.xml
<CustomField>
    <fullName>Ready_for_push_to_ProfitStars__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ready for push to ProfitStars</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Return_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Return_Account_Number__c</fullName>
    <description>Created for R1915805</description>
    <label>Return Account Number</label>
    <length>17</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/RoutingNo__c.field-meta.xml
<CustomField>
    <fullName>RoutingNo__c</fullName>
    <label>Routing #</label>
    <length>9</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/ValuePlus__c.field-meta.xml
<CustomField>
    <fullName>ValuePlus__c</fullName>
    <label>Value+</label>
    <referenceTo>ValuePlus__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/ValuePlus__c.object-meta.xml
<CustomObject>
    <label>Value+</label>
    <nameField>
        <displayFormat>VAS{000000}</displayFormat>
        <label>Value+</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ValuePlus</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ValuePlus__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Value+</relationshipLabel>
    <relationshipName>Value</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Ownership_Type__c.field-meta.xml
<CustomField>
    <fullName>Ownership_Type__c</fullName>
    <formula>TEXT( Account__r.Ownership_Type__c )</formula>
    <label>Ownership Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Principal_1_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Principal_1_First_Name__c</fullName>
    <formula>Account__r.Principal_1_First_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>APM - Principal 1 First Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Principal_1_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Principal_1_Last_Name__c</fullName>
    <formula>Account__r.Principal_1_Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>APM - Principal 1 Last Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Principal_1_Ownership__c.field-meta.xml
<CustomField>
    <fullName>Principal_1_Ownership__c</fullName>
    <formula>Account__r.Principal_1_Ownership__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>APM - Principal 1 Ownership</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Principal_2_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Principal_2_First_Name__c</fullName>
    <formula>Account__r.Principal_2_First_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>APM - Principal 2 First Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Principal_2_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Principal_2_Last_Name__c</fullName>
    <formula>Account__r.Principal_2_Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>APM - Principal 2 Last Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Principal_2_Ownership__c.field-meta.xml
<CustomField>
    <fullName>Principal_2_Ownership__c</fullName>
    <formula>Account__r.Principal_2_Ownership__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>APM - Principal 2 Ownership</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/ProfitStars_Merchant_ID__c.field-meta.xml
<CustomField>
    <fullName>ProfitStars_Merchant_ID__c</fullName>
    <label>ProfitStars Merchant ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/ps_LocationUpdateRequired__c.field-meta.xml
<CustomField>
    <fullName>ps_LocationUpdateRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ProfitStars Location Update Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/ps_UpdateRequired__c.field-meta.xml
<CustomField>
    <fullName>ps_UpdateRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Profit Stars Update Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sold/Not Started</fullName>
            </value>
            <value>
                <fullName>KOC Confirmed</fullName>
                <label>Questionnaire Received</label>
            </value>
            <value>
                <fullName>Sold/Not Ready</fullName>
            </value>
            <value>
                <fullName>On-Boarding</fullName>
            </value>
            <value>
                <fullName>KOC Scheduled</fullName>
            </value>
            <value>
                <fullName>KOC Complete</fullName>
            </value>
            <value>
                <fullName>Build In Progress</fullName>
            </value>
            <value>
                <fullName>Site Presentation</fullName>
            </value>
            <value>
                <fullName>Site Delivered/Final Changes</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Additional Communication (O)</fullName>
            </value>
            <value>
                <fullName>Agreement Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Content Acquisition</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Deferred-Built</fullName>
            </value>
            <value>
                <fullName>Deferred-Canceled</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Final Changes</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Left APM</fullName>
            </value>
            <value>
                <fullName>Left IM</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Live-Free Trial</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Lost During Pilot</fullName>
            </value>
            <value>
                <fullName>Lost In Onboarding</fullName>
            </value>
            <value>
                <fullName>Multi Site Deffered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ProfitStarsRequestBuilderTest.cls
/*
* Test class for the ProfitStarsRequestBuilder class.
*/
@isTest
private class ProfitStarsRequestBuilderTest{

	//Creates test data that is used by the unit tests in this class.
    @TestSetup
    public static void createTestData(){
    	TestDataFactory.createCustomSettings();

    	TestDataFactory.DataModel dm = new TestDataFactory.DataModel(1, false);
		//insert accounts
		// dm.accountList[0].RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('MyCase Account').getRecordTypeId();
		dm.accountList[0].ShippingStreet = '44th St S';
		dm.accountList[0].ShippingCity = 'Goleta';
		dm.accountList[0].Ownership_Type__c = null;
		dm.accountList[0].Principal_1_Ownership__c = 25;
		INSERT(dm.accountList);
		
		//insert valuePlus
		dm.valueplusList[0].Account__c = dm.accountList[0].Id;
		dm.valueplusList[0].RecordTypeId = Schema.SObjectType.ValuePlus__c.getRecordTypeInfosByName().get('MyCase Payments').getRecordTypeId();
		dm.valueplusList[0].Stage__c = 'Sold/Not Started';
		INSERT(dm.valuePlusList[0]);

		//insert bank accounts
		dm.bankAccountList[0].ValuePlus__c = dm.valueplusList[0].Id;
		dm.bankAccountList[0].RoutingNo__c = '053000196';
		dm.bankAccountList[0].AccountNo__c = '1234567891';
		dm.bankAccountList[0].Account_Type__c = '0';
		INSERT(dm.bankAccountList[0]);
    }

    static testmethod void createEnrollmentRequestTest(){

		TestUtils.genTestSettings(true);
		TestUtils.genEnrollmentCustomSettings();

		ValuePlus__c vp = [Select Id from ValuePlus__c where Account__r.Name = 'Test Account0' limit 1];
								 
		Test.startTest();
		ProfitStarsRequestBuilder.ProfitStarsRequest request = ProfitStarsRequestBuilder.createEnrollmentRequestFromActionAndRecordId(vp.Id, null);
		Test.stopTest();

		System.assertNotEquals(null, request);
	}

	static testmethod void createBankLocationVelocityReqTest(){

		TestUtils.genTestSettings(true);
		TestUtils.genVelocityCustomSetting();

		ValuePlus__c vp = [Select Id, ProfitStars_Merchant_ID__c from ValuePlus__c where Account__r.Name = 'Test Account0' limit 1];
		vp.ProfitStars_Merchant_ID__c = '343434';
		update vp;

		Bank_Account__c bank = [Select Id, LID__c from Bank_Account__c where Account_Label__c = 'Test Bank Account0'];
		bank.LID__c = '898989';
		Test.startTest();
		update bank;
								 
		Map<String, String> request = ProfitStarsRequestBuilder.createBankLocationVelocityReqFromActionAndRecordId('velocity', vp.Id, null, null);
		Test.stopTest();

		System.assertNotEquals(null, request);
	}

	static testmethod void createMultipleMaintenanceReqTest(){

		TestUtils.genTestSettings(true);
		TestUtils.genLocationCustomSetting();

		ValuePlus__c vp = [Select Id, ProfitStars_Merchant_ID__c from ValuePlus__c where Account__r.Name = 'Test Account0' limit 1];
		vp.ProfitStars_Merchant_ID__c = '343434';
		update vp;

		Bank_Account__c bank = [Select Id from Bank_Account__c where Account_Label__c = 'Test Bank Account0'];
		bank.ps_LocationUpdateRequired__c = true;
		bank.Ready_for_push_to_ProfitStars__c = true;
		Test.startTest();
		update bank;
								 
		Map<Id, Map<String, String>> request = ProfitStarsRequestBuilder.createMultipleMaintenanceReqFromActionAndRecordId('location', vp.Id, null);
		Test.stopTest();

		System.assertNotEquals(null, request);
	}

	static testmethod void createMaintOtherReqTest(){

		TestUtils.genTestSettings(true);
		TestUtils.genFieldCustomSetting();

		Account acc = [Select Id from Account where Name = 'Test Account0'];
		acc.ps_UpdateRequired__c = true;
		acc.ProfitStars_Update_Field__c = 'Name';
		update acc;

		Test.startTest();
		ValuePlus__c vp = [Select Id, ProfitStars_Merchant_ID__c from ValuePlus__c where Account__r.Name = 'Test Account0' limit 1];
		vp.ProfitStars_Merchant_ID__c = '343434';
		update vp;

		Bank_Account__c bank = [Select Id from Bank_Account__c where Account_Label__c = 'Test Bank Account0'];
		bank.ps_LocationUpdateRequired__c = true;
		bank.Ready_for_push_to_ProfitStars__c = true;
		update bank;
	
		Map<String, String> request = ProfitStarsRequestBuilder.createMaintOtherReqFromActionAndRecordId('field update', vp.Id, null);
		Test.stopTest();

		System.assertNotEquals(null, request);
	}

	static testmethod void createOwnershipUpdateReqTest(){

		TestUtils.genTestSettings(true);
		TestUtils.genFieldCustomSetting();

		Account acc = [Select Id from Account where Name = 'Test Account0'];
		acc.Principal_1_First_Name__c = 'POneFName';
		acc.Principal_1_Last_Name__c = 'POneLName';
		acc.Principal_1_SSN__c = '965777521';
		acc.Principal_1_Ownership__c = 50;
		acc.Principal_2_First_Name__c = 'PTwoFName';
		acc.Principal_2_Last_Name__c = 'PTwoLName';
		acc.Principal_2_SSN__c = '965666521';
		acc.Principal_2_Ownership__c = 50;
		acc.ps_UpdateRequired__c = true;
		acc.ProfitStars_Update_Field__c = 'Ownership';
		update acc;

		Test.startTest();
		ValuePlus__c vp = [Select Id, ProfitStars_Merchant_ID__c from ValuePlus__c where Account__r.Name = 'Test Account0' limit 1];
		vp.ProfitStars_Merchant_ID__c = '343434';
		update vp;
	
		Map<String, String> request = ProfitStarsRequestBuilder.createMaintOtherReqFromActionAndRecordId('ownership update', vp.Id, null);
		Test.stopTest();

		System.assertNotEquals(null, request);
	}

	static testmethod void createReturnOnlyBankReqTest(){

		ValuePlus__c vp = [Select Id, ProfitStars_Merchant_ID__c from ValuePlus__c where Account__r.Name = 'Test Account0' limit 1];
		vp.ProfitStars_Merchant_ID__c = '343434';
		update vp;

		Bank_Account__c bank = [Select Id from Bank_Account__c where Account_Label__c = 'Test Bank Account0'];
		bank.Return_Account_Number__c = '9877899876';
		bank.Return_Routing_Number__c = '009786545';
		bank.LID__c = '009545';
		update bank;
	
		Test.startTest();
		Map<String, String> request = ProfitStarsRequestBuilder.createReturnOnlyBankReqFromActionAndRecordId('return only', bank.Id, null);
		Test.stopTest();

		System.assertNotEquals(null, request);
	}
}