unpackaged/main/default/objects/Account/fields/Ownership_Type__c.field-meta.xml
<CustomField>
    <fullName>Ownership_Type__c</fullName>
    <description>Updated R1813846</description>
    <label>Ownership Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sole Proprietor</fullName>
            </value>
            <value>
                <fullName>Partnership</fullName>
            </value>
            <value>
                <fullName>Limited Liability Partnership</fullName>
            </value>
            <value>
                <fullName>Corporation</fullName>
            </value>
            <value>
                <fullName>LLC</fullName>
            </value>
            <value>
                <fullName>Single Member LLC</fullName>
            </value>
            <value>
                <fullName>S Corporation</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Trust</fullName>
            </value>
            <value>
                <fullName>Publicly Traded Corporation</fullName>
            </value>
            <value>
                <fullName>Non Profit</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Acquired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Principal_1_Ownership__c.field-meta.xml
<CustomField>
    <fullName>Principal_1_Ownership__c</fullName>
    <label>Principal 1 Ownership</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000000}</displayFormat>
        <label>Bank Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bank_Account__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>This is the bank account type.  0 = Checking, 1 = Savings.  Currently only Checking is supported.</description>
    <inlineHelpText>This is the bank account type.  0 = Checking, 1 = Savings.  Currently only Checking is supported.</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <default>true</default>
                <label>0</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/AccountNo__c.field-meta.xml
<CustomField>
    <fullName>AccountNo__c</fullName>
    <label>Account #</label>
    <length>17</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/ps_LocationUpdateRequired__c.field-meta.xml
<CustomField>
    <fullName>ps_LocationUpdateRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Location Update Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Ready_for_push_to_ProfitStars__c.field-meta.xml
<CustomField>
    <fullName>Ready_for_push_to_ProfitStars__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ready for push to ProfitStars</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/RoutingNo__c.field-meta.xml
<CustomField>
    <fullName>RoutingNo__c</fullName>
    <label>Routing #</label>
    <length>9</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/ValuePlus__c.field-meta.xml
<CustomField>
    <fullName>ValuePlus__c</fullName>
    <label>Value+</label>
    <referenceTo>ValuePlus__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/ValuePlus__c.object-meta.xml
<CustomObject>
    <label>Value+</label>
    <nameField>
        <displayFormat>VAS{000000}</displayFormat>
        <label>Value+</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ValuePlus</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ValuePlus__c/fields/Ownership_Type__c.field-meta.xml
<CustomField>
    <fullName>Ownership_Type__c</fullName>
    <formula>TEXT( Account__r.Ownership_Type__c )</formula>
    <label>Ownership Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Phone_Verified__c.field-meta.xml
<CustomField>
    <fullName>Phone_Verified__c</fullName>
    <label>Phone Verified</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Principal_1_Ownership__c.field-meta.xml
<CustomField>
    <fullName>Principal_1_Ownership__c</fullName>
    <formula>Account__r.Principal_1_Ownership__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>APM - Principal 1 Ownership</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/ProfitStars_Merchant_ID__c.field-meta.xml
<CustomField>
    <fullName>ProfitStars_Merchant_ID__c</fullName>
    <label>ProfitStars Merchant ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/ps_LocationUpdateRequired__c.field-meta.xml
<CustomField>
    <fullName>ps_LocationUpdateRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ProfitStars Location Update Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sold/Not Started</fullName>
            </value>
            <value>
                <fullName>KOC Confirmed</fullName>
                <label>Questionnaire Received</label>
            </value>
            <value>
                <fullName>Sold/Not Ready</fullName>
            </value>
            <value>
                <fullName>On-Boarding</fullName>
            </value>
            <value>
                <fullName>KOC Scheduled</fullName>
            </value>
            <value>
                <fullName>KOC Complete</fullName>
            </value>
            <value>
                <fullName>Build In Progress</fullName>
            </value>
            <value>
                <fullName>Site Presentation</fullName>
            </value>
            <value>
                <fullName>Site Delivered/Final Changes</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Additional Communication (O)</fullName>
            </value>
            <value>
                <fullName>Agreement Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Content Acquisition</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Deferred-Built</fullName>
            </value>
            <value>
                <fullName>Deferred-Canceled</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Final Changes</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Left APM</fullName>
            </value>
            <value>
                <fullName>Left IM</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Live-Free Trial</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Lost During Pilot</fullName>
            </value>
            <value>
                <fullName>Lost In Onboarding</fullName>
            </value>
            <value>
                <fullName>Multi Site Deffered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ProfitStarsRequestValidationTest.cls
/*
* Test class for the ProfitStarsRequestValidation class.
*/
@isTest
private class ProfitStarsRequestValidationTest {

	private static Account a;
	private static ValuePlus__c vp;
	private static Map<String, sObject> requiredFields;
	private static ValuePlus__c record;
	private static String action;

	@TestSetup
    public static void createTestData(){
    	TestDataFactory.createCustomSettings();
    }

	//Positive cases for velocity, fieldupdate, bank_account, location and enrollment
	static testmethod void validVelocityCallTest(){
		setup('velocity');

		Test.startTest();
		Boolean result = ProfitStarsRequestValidation.validate(record, requiredFields, action, null);
		Test.stopTest();
		system.assert(result, 'Expected this test to pass validation.');
	}

	static testmethod void validFieldUpdateCallTest(){
		setup('field update');

		Test.startTest();
		Boolean result = ProfitStarsRequestValidation.validate(record, requiredFields, action, null);
		Test.stopTest();
		system.assert(result, 'Expected this test to pass validation.');
	}

	static testmethod void validBankAccountCallTest(){
		setup('bank account');

		Test.startTest();
		Boolean result = ProfitStarsRequestValidation.validate(record, requiredFields, action, null);
		Test.stopTest();
		system.assert(result, 'Expected this test to pass validation.');
	}

	static testmethod void validLocationCallTest(){
		setup('Location');

		Test.startTest();
		Boolean result = ProfitStarsRequestValidation.validate(record, requiredFields, action, null);
		Test.stopTest();
		system.assert(result, 'Expected this test to pass validation.');
	}

	static testmethod void validEnrollmentCallTest(){
		setup('enrollment');

		Test.startTest();
		Boolean result = ProfitStarsRequestValidation.validate(record, requiredFields, action, null);
		Test.stopTest();
		system.assert(result, 'Expected this test to pass validation.');
	}

	static testmethod void completeEnrollWithoutBankCallTest(){
		TestUtils.genTestSettings(true);
		TestUtils.genEnrollmentCustomSettings();
		
		action = 'enrollment';
		a = TestUtils.genAccount(true);
		vp = TestUtils.genValuePlus(true, a.id);

		a.ShippingStreet = '44th St S';
		a.ShippingCity = 'Goleta';
		a.Ownership_Type__c = null;
		a.Principal_1_Ownership__c = 25;
		update a;

		vp.Stage__c = 'Sold/Not Started';
		update vp;

		List<Bank_Account__c> bankList = TestDataFactory.createBankAccountList(1, vp.Id, false);
		bankList[0].RoutingNo__c = '053000196';
		bankList[0].AccountNo__c = '1234567891';
		bankList[0].Account_Type__c = '0';
		insert bankList;

		requiredFields = ProfitStarsUtils.getRequiredFieldsForCall(action);
		record = ProfitStarsRequestBuilder.getRecord(vp.id, requiredFields, action, null);

		Test.startTest();
		Boolean result = ProfitStarsRequestValidation.validate(record, requiredFields, action, null);
		Test.stopTest();
		system.assert(result, 'Expected this test to pass validation.');
	}

	static testmethod void completeEnrollWithBankCallTest(){
		TestUtils.genTestSettings(true);
		TestUtils.genEnrollmentCustomSettings();
		
		action = 'enrollment';
		a = TestUtils.genAccount(true);
		vp = TestUtils.genValuePlus(true, a.id);

		a.ShippingStreet = '44th St S';
		a.ShippingCity = 'Goleta';
		a.Ownership_Type__c = null;
		a.Principal_1_Ownership__c = 25;
		update a;

		vp.Stage__c = 'Sold/Not Started';
		update vp;

		List<Bank_Account__c> bankList = TestDataFactory.createBankAccountList(1, vp.Id, false);
		bankList[0].RoutingNo__c = '053000196';
		bankList[0].AccountNo__c = '1234567891';
		bankList[0].Account_Type__c = '0';
		bankList[0].Ready_for_push_to_ProfitStars__c = true;
		bankList[0].ps_LocationUpdateRequired__c = true;
		insert bankList;

		requiredFields = ProfitStarsUtils.getRequiredFieldsForCall(action);
		record = ProfitStarsRequestBuilder.getRecord(vp.id, requiredFields, action, null);

		Test.startTest();
		Boolean result = ProfitStarsRequestValidation.validate(record, requiredFields, action, null);
		Test.stopTest();
		system.assert(result, 'Expected this test to pass validation.');
	}

	//Negative cases for velocity, fieldupdate, bank_account, location and enrollment
	static testmethod void errorVelocityCallTest(){
		Boolean didFail = false;
		setup('velocity');

		record.Phone_Verified__c = null;

		Test.startTest();

		try{
			Boolean result = ProfitStarsRequestValidation.validate(record, requiredFields, action, null);
		} catch(ProfitStarsRequestValidation.ProfitStarsValidationException e){
			didFail = true;
		}
		System.assert(didFail, 'Expected a validation error, but didn\'t get one');

		Test.stopTest();
	}

	static testmethod void errorFieldUpdateCallTest(){
		Boolean didFail = false;
		setup('field update');

		record.Phone_Verified__c = null;

		Test.startTest();

		try{
			Boolean result = ProfitStarsRequestValidation.validate(record, requiredFields, action, null);
		} catch(ProfitStarsRequestValidation.ProfitStarsValidationException e){
			didFail = true;
		}
		System.assert(didFail, 'Expected a validation error, but didn\'t get one');

		Test.stopTest();
	}

	static testmethod void errorBankAccountCallTest(){
		Boolean didFail = false;
		setup('bank account');

		record.Phone_Verified__c = null;

		Test.startTest();

		try{
			Boolean result = ProfitStarsRequestValidation.validate(record, requiredFields, action, null);
		} catch(ProfitStarsRequestValidation.ProfitStarsValidationException e){
			didFail = true;
		}
		System.assert(didFail, 'Expected a validation error, but didn\'t get one');

		Test.stopTest();
	}

	static testmethod void errorLocationCallTest(){
		Boolean didFail = false;
		setup('Location');

		record.Phone_Verified__c = null;

		Test.startTest();

		try{
			Boolean result = ProfitStarsRequestValidation.validate(record, requiredFields, action, null);
		} catch(ProfitStarsRequestValidation.ProfitStarsValidationException e){
			didFail = true;
		}
		System.assert(didFail, 'Expected a validation error, but didn\'t get one');

		Test.stopTest();
	}

	static testmethod void errorEnrollmentCallTest(){
		Boolean didFail = false;
		setup('enrollment');

		record.Phone_Verified__c = null;

		Test.startTest();

		try{
			Boolean result = ProfitStarsRequestValidation.validate(record, requiredFields, action, null);
		} catch(ProfitStarsRequestValidation.ProfitStarsValidationException e){
			didFail = true;
		}
		System.assert(didFail, 'Expected a validation error, but didn\'t get one');

		Test.stopTest();
	}

	static testmethod void invalidCustomSettingTest(){
		Boolean didFail = false;
		setup('enrollment');

		record.Phone_Verified__c = null;

		Test.startTest();

		try{
			Boolean result = ProfitStarsRequestValidation.validate(record, requiredFields, 'invalid', null);
		} catch(Exception e){
			didFail = true;
		}
		System.assert(didFail, 'Expected a validation error, but didn\'t get one');

		Test.stopTest();
	}

	static testmethod void requestTestsPSIS(){
		String validCallJson = '{"CaseNumber": "00001720", "Success": "true"}';
		Test.setMock(HttpCalloutMock.class, new RestClientCalloutMockFactory(200, 'Success', validCallJson, null));

		TestUtils.genTestSettings(true);
		a = TestUtils.genAccount(true);
		vp = TestUtils.genValuePlus(true, a.id);

		List<String> responses = new List<String>();
		ProfitStarsIntegrationService ps = new ProfitStarsIntegrationService();

		vp.ProfitStars_Merchant_ID__c = '234432';
		update vp;

		Test.startTest();

		responses.add(ps.makeGetAllLocationsRequest(vp.Id, null));
		responses.add(ps.makeGetLocationByLocationIdRequest(vp.Id, null));
		responses.add(ps.makeGetVelocitySettingsByLocationIdRequest(vp.Id, null));

		Test.stopTest();

		System.assertNotEquals(0, responses.size());
	}

	//Setup Helper method.
	private static void setup(String incomingAction){
		action = incomingAction;
		TestUtils.addRequiredFieldToCustomSetting(incomingAction);
		a = TestUtils.genAccount(true);
		vp = TestUtils.genValuePlus(true, a.id);
		requiredFields = ProfitStarsUtils.getRequiredFieldsForCall(incomingAction);
		record = ProfitStarsRequestBuilder.getRecord(vp.id, requiredFields, incomingAction, null);
	}
}