unpackaged/main/default/objects/Account/fields/Ownership_Type__c.field-meta.xml
<CustomField>
    <fullName>Ownership_Type__c</fullName>
    <description>Updated R1813846</description>
    <label>Ownership Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sole Proprietor</fullName>
            </value>
            <value>
                <fullName>Partnership</fullName>
            </value>
            <value>
                <fullName>Limited Liability Partnership</fullName>
            </value>
            <value>
                <fullName>Corporation</fullName>
            </value>
            <value>
                <fullName>LLC</fullName>
            </value>
            <value>
                <fullName>Single Member LLC</fullName>
            </value>
            <value>
                <fullName>S Corporation</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Trust</fullName>
            </value>
            <value>
                <fullName>Publicly Traded Corporation</fullName>
            </value>
            <value>
                <fullName>Non Profit</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Acquired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Tax_ID__c.field-meta.xml
<CustomField>
    <fullName>Tax_ID__c</fullName>
    <label>Tax ID</label>
    <length>10</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>Used to capture and track customer accounts; if customer is a partner as well, use the Partner record type</description>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>Internal or Fake Accounts</description>
    <label>Internal</label>
</RecordType>

unpackaged/main/default/objects/ValuePlus__c/ValuePlus__c.object-meta.xml
<CustomObject>
    <label>Value+</label>
    <nameField>
        <displayFormat>VAS{000000}</displayFormat>
        <label>Value+</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ValuePlus</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ValuePlus__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Value+</relationshipLabel>
    <relationshipName>Value</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/ACH_Type__c.field-meta.xml
<CustomField>
    <fullName>ACH_Type__c</fullName>
    <description>This is the ACH type used by ProfitStars.  1 = ACH Credit, 2 = ACH Debit, 3 = ACH Refund.  The only supported value at this time is ACH Credit.</description>
    <inlineHelpText>This is the ACH type used by ProfitStars.  1 = ACH Credit, 2 = ACH Debit, 3 = ACH Refund.  The only supported value at this time is ACH Credit.</inlineHelpText>
    <label>ACH Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
                <default>true</default>
                <label>2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Annual_CreditCard_Volume__c.field-meta.xml
<CustomField>
    <fullName>Annual_CreditCard_Volume__c</fullName>
    <defaultValue>IF($RecordType.Name = &#39;MyCase Payments&#39;, 50000, NULL)</defaultValue>
    <label>Annual CreditCard Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/CreditCard_Single_Trans_Amount__c.field-meta.xml
<CustomField>
    <fullName>CreditCard_Single_Trans_Amount__c</fullName>
    <defaultValue>IF($RecordType.Name = &#39;MyCase Payments&#39;, 50000, NULL)</defaultValue>
    <label>CreditCard Single Trans Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Has_Accepted_CreditCards__c.field-meta.xml
<CustomField>
    <fullName>Has_Accepted_CreditCards__c</fullName>
    <label>Has Accepted CreditCards</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/MC_Principal_1_City__c.field-meta.xml
<CustomField>
    <fullName>MC_Principal_1_City__c</fullName>
    <description>MC,IM; R151946, R2027302; Edited: Sertifi Integ, users</description>
    <label>MC/IM - Principal 1 City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/MC_Principal_1_DOB__c.field-meta.xml
<CustomField>
    <fullName>MC_Principal_1_DOB__c</fullName>
    <description>MC,IM; R151946, R2027302; Edited: Sertifi Integ, users</description>
    <label>MC/IM - Principal 1 DOB</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/MC_Principal_1_First_Name__c.field-meta.xml
<CustomField>
    <fullName>MC_Principal_1_First_Name__c</fullName>
    <description>MC,IM; R151946, R2027302; Edited: Sertifi Integ, users</description>
    <label>MC/IM - Principal 1 First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/MC_Principal_1_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>MC_Principal_1_Last_Name__c</fullName>
    <description>MC,IM; R151946, R2027302; Edited: Sertifi Integ, users</description>
    <label>MC/IM - Principal 1 Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/MC_Principal_1_SSN__c.field-meta.xml
<CustomField>
    <fullName>MC_Principal_1_SSN__c</fullName>
    <description>MC,IM; R151946; Edited: Sertifi Integ, users</description>
    <label>MC/IM - Principal 1 SSN</label>
    <length>11</length>
    <maskChar>asterisk</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/MC_Principal_1_State__c.field-meta.xml
<CustomField>
    <fullName>MC_Principal_1_State__c</fullName>
    <description>MC,IM; R151946, R2027302; Edited: Sertifi Integ, users</description>
    <label>MC/IM - Principal 1 State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/MC_Principal_1_Street__c.field-meta.xml
<CustomField>
    <fullName>MC_Principal_1_Street__c</fullName>
    <description>MC,IM; R151946, R2027302; Edited: Sertifi Integ, users</description>
    <label>MC/IM - Principal 1 Street</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/MC_Principal_1_Zip__c.field-meta.xml
<CustomField>
    <fullName>MC_Principal_1_Zip__c</fullName>
    <description>MC,IM; R151946, R2027302; Edited: Sertifi Integ, users</description>
    <label>MC/IM - Principal 1 Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Ownership_Type__c.field-meta.xml
<CustomField>
    <fullName>Ownership_Type__c</fullName>
    <formula>TEXT( Account__r.Ownership_Type__c )</formula>
    <label>Ownership Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Phone_Verified__c.field-meta.xml
<CustomField>
    <fullName>Phone_Verified__c</fullName>
    <label>Phone Verified</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Tax_ID__c.field-meta.xml
<CustomField>
    <fullName>Tax_ID__c</fullName>
    <description>Created for request R151946</description>
    <label>Tax ID</label>
    <length>10</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Vantiv_Enrolled_Date__c.field-meta.xml
<CustomField>
    <fullName>Vantiv_Enrolled_Date__c</fullName>
    <label>Vantiv Enrolled Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Vantiv_Legal_Entity_Id__c.field-meta.xml
<CustomField>
    <fullName>Vantiv_Legal_Entity_Id__c</fullName>
    <label>Vantiv Legal Entity Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Vantiv_Onboarding_Status__c.field-meta.xml
<CustomField>
    <fullName>Vantiv_Onboarding_Status__c</fullName>
    <label>Vantiv Onboarding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready To Transmit</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Manual Review</fullName>
            </value>
            <value>
                <fullName>Manual Review - Duplicate</fullName>
            </value>
            <value>
                <fullName>Manual Review - Background Check Error</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Collecting Documents</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Year_Established__c.field-meta.xml
<CustomField>
    <fullName>Year_Established__c</fullName>
    <formula>TEXT(MC_Year_Established__c) &amp; &quot;-01-01&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year Established</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/VantivLegalEntityStatusBatchTest.cls
@isTest
private class VantivLegalEntityStatusBatchTest {

    static testMethod void testSuccess() {
        Account account1 = VantivTestUtils.genAccount(true, 'MyCase Account');
        ValuePlus__c vp1 = new ValuePlus__c(
			Account__c = account1.Id,
			Phone_Verified__c = 'yes',
			Annual_CreditCard_Volume__c = 20000,
			//Has_Accepted_CreditCards__c = true,
			CreditCard_Single_Trans_Amount__c = 10000,
			ACH_Type__c = '1',
			Tax_ID__c='758741745',
			MC_Principal_1_First_Name__c = 'principalFirstName',
			MC_Principal_1_Last_Name__c = 'principalLastName',
			MC_Principal_1_SSN__c = '963852147',
			MC_Principal_1_DOB__c = Date.Today().addYears(-35),
			MC_Principal_1_Street__c = '50 Castilian Dr',
			MC_Principal_1_City__c = 'Goleta',
			MC_Principal_1_State__c = 'CA',
			MC_Principal_1_Zip__c = '93117',
			recordTypeId = VantivTestUtils.getRecordTypeIdFromSObjectAndName('ValuePlus__c', 'MyCase Payments'),
			Vantiv_Onboarding_Status__c = 'Manual Review', 
			Vantiv_Legal_Entity_Id__c = '8291697191215225623',
			Vantiv_Enrolled_Date__c = Date.Today().addDays(-2)
		);
		insert vp1;
		
		Account account2 = new Account();
		//As of 9-15-14, the only required fields for account are:
		// RecordType (Customer Internal Property Management Secure Docs)
		// Name
		account2.Name = 'Testy Account # ' + VantivTestUtils.genRandomNumber(10);
		account2.Phone = '555 555 5555';
		account2.Ownership_Type__c='Partnership';
		account2.Website = 'https://www.appfolio.com';
		account2.BillingStreet = '50 Castilian Dr';
		account2.BillingCity = 'Los Angeles';
		account2.BillingState = 'CA';
		account2.BillingPostalCode = '90039';
		account2.BillingCountry = 'USA';
		account2.Year_Established__c = '2021';
		// account2.RecordTypeId = VantivTestUtils.getRecordTypeIdFromSObjectAndName('Account', 'MyCase Account');
		insert account2;
		
		ValuePlus__c vp2 = new ValuePlus__c(
			Account__c = account2.Id,
			Phone_Verified__c = 'yes',
			Annual_CreditCard_Volume__c = 20000,
			//Has_Accepted_CreditCards__c = true,
			CreditCard_Single_Trans_Amount__c = 10000,
			ACH_Type__c = '1',
			Tax_ID__c='498454585',
			MC_Principal_1_First_Name__c = 'principalFirstName2',
			MC_Principal_1_Last_Name__c = 'principalLastName2',
			MC_Principal_1_SSN__c = '963852147',
			MC_Principal_1_DOB__c = Date.Today().addYears(-25),
			MC_Principal_1_Street__c = '90 Castilian Dr',
			MC_Principal_1_City__c = 'Goleta',
			MC_Principal_1_State__c = 'CA',
			MC_Principal_1_Zip__c = '93117',
			recordTypeId = VantivTestUtils.getRecordTypeIdFromSObjectAndName('ValuePlus__c', 'MyCase Payments'),
			Vantiv_Onboarding_Status__c = 'Manual Review',
			Vantiv_Legal_Entity_Id__c = '82916971912152256',
			Vantiv_Enrolled_Date__c = Date.Today().addDays(-2)
		);
		insert vp2;
		
		
		VantivTestUtils.genTestSettings(true);
		//VantivTestUtils.genCreateLegalEntity();
		VantivTestUtils.genRootElement();
		//VantivTestUtils.genVantivEntityType();
		
		System.debug(vp1);
		System.debug(vp2);
		
		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new VantivMockResponse(VantivTestUtils.legalEntitySuccessResponse, 200));
		VantivLegalEntityStatusBatch req = new VantivLegalEntityStatusBatch();
		req.start(null);
		req.execute(null,[Select Id, recordType.Name from ValuePlus__c where Vantiv_Onboarding_Status__c like '%Manual Review%' and Vantiv_Enrolled_Date__c < TODAY and Vantiv_Legal_Entity_Id__c != null]);
		req.finish(null);
		//Database.executeBatch(new VantivLegalEntityStatusBatch());
		//System.assertEquals('Approved', vp1.Vantiv_Onboarding_Status__c);
		//System.assertEquals('Approved', vp2.Vantiv_Onboarding_Status__c);
		Test.stopTest();
    }
    
    static testMethod void testException() {
        Account account1 = VantivTestUtils.genAccount(true, 'MyCase Account');
        ValuePlus__c vp1 = new ValuePlus__c(
			Account__c = account1.Id,
			Phone_Verified__c = 'yes',
			Annual_CreditCard_Volume__c = 20000,
			//Has_Accepted_CreditCards__c = true,
			CreditCard_Single_Trans_Amount__c = 10000,
			ACH_Type__c = '1',
			//Tax_ID__c='758741745',
			MC_Principal_1_First_Name__c = 'principalFirstName',
			MC_Principal_1_Last_Name__c = 'principalLastName',
			MC_Principal_1_SSN__c = '963852147',
			MC_Principal_1_DOB__c = Date.Today().addYears(-35),
			MC_Principal_1_Street__c = '50 Castilian Dr',
			MC_Principal_1_City__c = 'Goleta',
			MC_Principal_1_State__c = 'CA',
			MC_Principal_1_Zip__c = '93117',
			recordTypeId = VantivTestUtils.getRecordTypeIdFromSObjectAndName('ValuePlus__c', 'MyCase Payments'),
			Vantiv_Onboarding_Status__c = 'Manual Review', 
			Vantiv_Legal_Entity_Id__c = '8291697191215225623',
			Vantiv_Enrolled_Date__c = Date.Today().addDays(-2)
		);
		insert vp1;
		
		Account account2 = new Account();
		//As of 9-15-14, the only required fields for account are:
		// RecordType (Customer Internal Property Management Secure Docs)
		// Name
		account2.Name = 'McTesterson Account # ' + VantivTestUtils.genRandomNumber(10);
		account2.Phone = '555 867 5309';
		account2.Ownership_Type__c='Partnership';
		account2.Website = 'https://www.appfolio.com';
		account2.BillingStreet = '50 Castilian Dr';
		account2.BillingCity = 'Goleta';
		account2.BillingState = 'CA';
		account2.BillingPostalCode = '93117';
		account2.BillingCountry = 'USA';
		account2.Year_Established__c = '2000';
		// account2.RecordTypeId = VantivTestUtils.getRecordTypeIdFromSObjectAndName('Account', 'MyCase Account');
		insert account2;
		
		ValuePlus__c vp2 = new ValuePlus__c(
			Account__c = account2.Id,
			Phone_Verified__c = 'yes',
			Annual_CreditCard_Volume__c = 20000,
			//Has_Accepted_CreditCards__c = true,
			CreditCard_Single_Trans_Amount__c = 10000,
			ACH_Type__c = '1',
			Tax_ID__c='498454585',
			MC_Principal_1_First_Name__c = 'principalFirstName2',
			MC_Principal_1_Last_Name__c = 'principalLastName2',
			MC_Principal_1_SSN__c = '963852147',
			MC_Principal_1_DOB__c = Date.Today().addYears(-25),
			MC_Principal_1_Street__c = '90 Castilian Dr',
			MC_Principal_1_City__c = 'Goleta',
			MC_Principal_1_State__c = 'CA',
			MC_Principal_1_Zip__c = '93117',
			recordTypeId = VantivTestUtils.getRecordTypeIdFromSObjectAndName('ValuePlus__c', 'MyCase Payments'),
			Vantiv_Onboarding_Status__c = 'Manual Review',
			Vantiv_Legal_Entity_Id__c = '82916971912152256',
			Vantiv_Enrolled_Date__c = Date.Today().addDays(-2)
		);
		insert vp2;
		
		
		VantivTestUtils.genTestSettings(true);
		//VantivTestUtils.genCreateLegalEntity();
		VantivTestUtils.genRootElement();
		//VantivTestUtils.genVantivEntityType();
		
		System.debug(vp1);
		System.debug(vp2);
		
		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new VantivMockResponse(VantivTestUtils.legalEntityFailedResponse, 200));
		VantivLegalEntityStatusBatch req = new VantivLegalEntityStatusBatch();
		req.start(null);
		req.execute(null,[Select Id, recordType.Name from ValuePlus__c where Vantiv_Onboarding_Status__c like '%Manual Review%' and Vantiv_Enrolled_Date__c < TODAY and Vantiv_Legal_Entity_Id__c != null]);
		req.finish(null);
		//Database.executeBatch(new VantivLegalEntityStatusBatch());
		//System.assertEquals('Approved', vp1.Vantiv_Onboarding_Status__c);
		//System.assertEquals('Approved', vp2.Vantiv_Onboarding_Status__c);
		Test.stopTest();
    }
}