unpackaged/main/default/objects/Account/fields/Payments_Enterprise_Account__c.field-meta.xml
<CustomField>
    <fullName>Payments_Enterprise_Account__c</fullName>
    <label>Payments Enterprise Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Partnerships__c/Partnerships__c.object-meta.xml
<CustomObject>
    <label>Partnership</label>
    <nameField>
        <label>Partnership</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnerships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Partnerships__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partnerships</relationshipLabel>
    <relationshipName>Partnerships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Referral__c/Referral__c.object-meta.xml
<CustomObject>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF- {0}</displayFormat>
        <label>Referral name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Referral__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to the partner account</description>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referrals (Partner Account)</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Referral__c/fields/Partnership__c.field-meta.xml
<CustomField>
    <fullName>Partnership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partnership</label>
    <referenceTo>Partnerships__c</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Partners</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Referral__c/fields/Payments_Enterprise_Account__c.field-meta.xml
<CustomField>
    <fullName>Payments_Enterprise_Account__c</fullName>
    <label>Payments Enterprise Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>True</fullName>
            </value>
            <value>
                <fullName>False</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/UpdateReferralsTest.cls
@isTest
public class UpdateReferralsTest {

    @isTest
    static void testUpdateReferralsTrigger() {
        // Create test data
        Account testAccount = new Account(Name = 'Test Account', Payments_Enterprise_Account__c = 'Yes');
        insert testAccount;
        Partnerships__c testPartnership = new Partnerships__c(Name='Test Partnership', Partner_Account__c = testAccount.id);
        insert testPartnership;
        Referral__c referral = new Referral__c(Payments_Enterprise_Account__c = 'No', Partnership__c = testPartnership.id);
        insert referral;

        // Perform an update to trigger the trigger
        testAccount.Payments_Enterprise_Account__c = 'No';
        update testAccount;

        // Verify the results
        // Query the updated account to verify that the trigger executed the expected logic
        Account updatedAccount = [SELECT Id, Payments_Enterprise_Account__c FROM Account WHERE Id = :testAccount.Id];
        
        // Assert that the Payments_Enterprise_Account__c field has been updated
        System.assertEquals('No', updatedAccount.Payments_Enterprise_Account__c);
        
        // Optionally, you can add more assertions or query related records to ensure the desired behavior.
    }
}