unpackaged/main/default/objects/Account/fields/Principal_1_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Principal_1_First_Name__c</fullName>
    <label>Principal 1 First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Principal_1_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Principal_1_Last_Name__c</fullName>
    <label>Principal 1 Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Principal_1_Ownership__c.field-meta.xml
<CustomField>
    <fullName>Principal_1_Ownership__c</fullName>
    <label>Principal 1 Ownership</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Principal_1_SSN__c.field-meta.xml
<CustomField>
    <fullName>Principal_1_SSN__c</fullName>
    <label>Principal 1 SSN</label>
    <length>11</length>
    <maskChar>asterisk</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Principal_2_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Principal_2_First_Name__c</fullName>
    <label>Principal 2 First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Principal_2_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Principal_2_Last_Name__c</fullName>
    <label>Principal 2 Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Principal_2_Ownership__c.field-meta.xml
<CustomField>
    <fullName>Principal_2_Ownership__c</fullName>
    <label>Principal 2 Ownership</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Principal_2_SSN__c.field-meta.xml
<CustomField>
    <fullName>Principal_2_SSN__c</fullName>
    <label>Principal 2 SSN</label>
    <length>11</length>
    <maskChar>asterisk</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ProfitStars_Update_Field__c.field-meta.xml
<CustomField>
    <fullName>ProfitStars_Update_Field__c</fullName>
    <label>ProfitStars Update Field</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Name</fullName>
            </value>
            <value>
                <fullName>Tax ID</fullName>
            </value>
            <value>
                <fullName>Ownership</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/ProfitStars_Update_Outbound__c.field-meta.xml
<CustomField>
    <fullName>ProfitStars_Update_Outbound__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ProfitStars Update Outbound</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ps_UpdateRequired__c.field-meta.xml
<CustomField>
    <fullName>ps_UpdateRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Profit Stars Update Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/PS_Audit_Log__c/PS_Audit_Log__c.object-meta.xml
<CustomObject>
    <label>ProfitStars Callout Audit Log</label>
    <nameField>
        <displayFormat>AuditLog-{000000}</displayFormat>
        <label>ProfitStars Callout Audit Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProfitStars Callout Audit Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PS_Audit_Log__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ProfitStars Callout Audit Logs</relationshipLabel>
    <relationshipName>ProfitStars_Callout_Audit_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/ValuePlus__c.object-meta.xml
<CustomObject>
    <label>Value+</label>
    <nameField>
        <displayFormat>VAS{000000}</displayFormat>
        <label>Value+</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ValuePlus</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ValuePlus__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Value+</relationshipLabel>
    <relationshipName>Value</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Outbound_MID__c.field-meta.xml
<CustomField>
    <fullName>Outbound_MID__c</fullName>
    <description>Created by R152610
Updated By  R163828</description>
    <label>Outbound MID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Phone_Verified__c.field-meta.xml
<CustomField>
    <fullName>Phone_Verified__c</fullName>
    <label>Phone Verified</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Principal_1_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Principal_1_First_Name__c</fullName>
    <formula>Account__r.Principal_1_First_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>APM - Principal 1 First Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Principal_1_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Principal_1_Last_Name__c</fullName>
    <formula>Account__r.Principal_1_Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>APM - Principal 1 Last Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Principal_1_Ownership__c.field-meta.xml
<CustomField>
    <fullName>Principal_1_Ownership__c</fullName>
    <formula>Account__r.Principal_1_Ownership__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>APM - Principal 1 Ownership</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Principal_2_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Principal_2_First_Name__c</fullName>
    <formula>Account__r.Principal_2_First_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>APM - Principal 2 First Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Principal_2_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Principal_2_Last_Name__c</fullName>
    <formula>Account__r.Principal_2_Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>APM - Principal 2 Last Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Principal_2_Ownership__c.field-meta.xml
<CustomField>
    <fullName>Principal_2_Ownership__c</fullName>
    <formula>Account__r.Principal_2_Ownership__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>APM - Principal 2 Ownership</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/ps_LocationUpdateRequired__c.field-meta.xml
<CustomField>
    <fullName>ps_LocationUpdateRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ProfitStars Location Update Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/ps_UpdateRequired__c.field-meta.xml
<CustomField>
    <fullName>ps_UpdateRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Profit Stars Update Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sold/Not Started</fullName>
            </value>
            <value>
                <fullName>KOC Confirmed</fullName>
                <label>Questionnaire Received</label>
            </value>
            <value>
                <fullName>Sold/Not Ready</fullName>
            </value>
            <value>
                <fullName>On-Boarding</fullName>
            </value>
            <value>
                <fullName>KOC Scheduled</fullName>
            </value>
            <value>
                <fullName>KOC Complete</fullName>
            </value>
            <value>
                <fullName>Build In Progress</fullName>
            </value>
            <value>
                <fullName>Site Presentation</fullName>
            </value>
            <value>
                <fullName>Site Delivered/Final Changes</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Additional Communication (O)</fullName>
            </value>
            <value>
                <fullName>Agreement Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Content Acquisition</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Deferred-Built</fullName>
            </value>
            <value>
                <fullName>Deferred-Canceled</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Final Changes</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Left APM</fullName>
            </value>
            <value>
                <fullName>Left IM</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Live-Free Trial</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Lost During Pilot</fullName>
            </value>
            <value>
                <fullName>Lost In Onboarding</fullName>
            </value>
            <value>
                <fullName>Multi Site Deffered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Successfully_Enrolled_in_Profit_Stars_at__c.field-meta.xml
<CustomField>
    <fullName>Successfully_Enrolled_in_Profit_Stars_at__c</fullName>
    <description>This field, when populated signifies that the record has been successfully enrolled in profit stars.</description>
    <label>Successfully Enrolled in Profit Stars at</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/PS_BatchFieldUpdatesForOutboundTest.cls
/*
* Test class for the PS_BatchFieldUpdatesForOutbound class.
*/
@isTest
private class PS_BatchFieldUpdatesForOutboundTest{

	static String validCallJson = '{"CaseNumber": "00001720", "Success": "true"}';
	static String errorCallJson = '{"CaseNumber": null, "Success": "false", "ErrorMessage": "Bank Routing Number is not valid", "ErrorCode": "FIELD_CUSTOM_VALIDATION_EXCEPTION"}';
	static String exceptionJson = '{}';

	//Creates test data that is used by the unit tests in this class.
    @TestSetup
    public static void createTestData(){
    	TestDataFactory.createCustomSettings();

    	TestDataFactory.DataModel dm = new TestDataFactory.DataModel(1, false);
		//insert accounts
		// dm.accountList[0].RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('MyCase Account').getRecordTypeId();
		dm.accountList[0].ps_UpdateRequired__c = true;
		dm.accountList[0].ProfitStars_Update_Outbound__c = true;
		dm.accountList[0].ProfitStars_Update_Field__c = 'Name';
		INSERT(dm.accountList);
		
		//insert valuePlus
		dm.valueplusList[0].Account__c = dm.accountList[0].Id;
		dm.valueplusList[0].RecordTypeId = Schema.SObjectType.ValuePlus__c.getRecordTypeInfosByName().get('MyCase Payments').getRecordTypeId();
		dm.valueplusList[0].ps_LocationUpdateRequired__c = true;
		dm.valueplusList[0].Stage__c = 'Sold/Not Started';
		dm.valueplusList[0].Outbound_MID__c = '1234567';
		dm.valueplusList[0].Successfully_Enrolled_in_Profit_Stars_at__c = System.today();
		INSERT(dm.valuePlusList[0]);

		//insert bank accounts
		dm.bankAccountList[0].ValuePlus__c = dm.valueplusList[0].Id;
		dm.bankAccountList[0].RoutingNo__c = '053000196';
		dm.bankAccountList[0].AccountNo__c = '1234567891';
		INSERT(dm.bankAccountList[0]);

		TestUtils.genTestSettings(true);
		TestUtils.genOutboundTestSettings(true);
		TestUtils.genEcheckFieldsTestSettings(true);
		TestUtils.genFieldCustomSetting();
    }

	static testmethod void batchFieldUpdatesTest(){

		Test.setMock(HttpCalloutMock.class, new RestClientCalloutMockFactory(200, 'Success', validCallJson, null));
								 
		Test.startTest();
		PS_BatchFieldUpdatesForOutbound fieldUpdateJob = new PS_BatchFieldUpdatesForOutbound();
		ID batchprocessid = Database.executeBatch(fieldUpdateJob);
		Test.stopTest();

		Account acc = [Select ProfitStars_Update_Outbound__c from Account where Name = 'Test Account0'];
		// System.assertEquals(false, acc.ProfitStars_Update_Outbound__c);
	}

	static testmethod void batchOwnerUpdatesTest(){

		Test.setMock(HttpCalloutMock.class, new RestClientCalloutMockFactory(200, 'Success', validCallJson, null));

		Account acc = [Select Id from Account where Name = 'Test Account0'];
								 
		Test.startTest();
		acc.Principal_1_First_Name__c = 'POneFName';
		acc.Principal_1_Last_Name__c = 'POneLName';
		acc.Principal_1_SSN__c = '965777521';
		acc.Principal_1_Ownership__c = 50;
		acc.Principal_2_First_Name__c = 'PTwoFName';
		acc.Principal_2_Last_Name__c = 'PTwoLName';
		acc.Principal_2_SSN__c = '965666521';
		acc.Principal_2_Ownership__c = 50;
		acc.ps_UpdateRequired__c = true;
		acc.ProfitStars_Update_Outbound__c = true;
		acc.ProfitStars_Update_Field__c = 'Ownership';
		update acc;

		PS_BatchFieldUpdatesForOutbound fieldUpdateJob = new PS_BatchFieldUpdatesForOutbound();
		ID batchprocessid = Database.executeBatch(fieldUpdateJob);
		Test.stopTest();

		Account acct = [Select ProfitStars_Update_Outbound__c from Account where Name = 'Test Account0'];
		// System.assertEquals(false, acct.ProfitStars_Update_Outbound__c);
	}

	static testmethod void batchFieldErrorUpdatesTest(){

		Test.setMock(HttpCalloutMock.class, new RestClientCalloutMockFactory(200, 'Success', errorCallJson, null));
								 
		Test.startTest();
		PS_BatchFieldUpdatesForOutbound fieldUpdateJob = new PS_BatchFieldUpdatesForOutbound();
		ID batchprocessid = Database.executeBatch(fieldUpdateJob);
		Test.stopTest();

		Account acc = [Select ProfitStars_Update_Outbound__c from Account where Name = 'Test Account0'];
		System.assertEquals(true, acc.ProfitStars_Update_Outbound__c);
	}

	static testmethod void testException(){

		TestUtils.addRequiredFieldToCustomSetting('field update');

		ValuePlus__c vp = [Select id, Phone_Verified__c from ValuePlus__c where Outbound_MID__c = '1234567'];
        vp.Phone_Verified__c = null;
        update vp;
		
		Test.setMock(HttpCalloutMock.class, new RestClientCalloutMockFactory(401, 'Failure', exceptionJson, null));
								 
		Test.startTest();
		PS_BatchFieldUpdatesForOutbound fieldUpdateJob = new PS_BatchFieldUpdatesForOutbound();
		fieldUpdateJob.errorMessage = 'error test';
		ID batchprocessid = Database.executeBatch(fieldUpdateJob);
		fieldUpdateJob.finalize(null, null, null);
		Test.stopTest();

		List<PS_Audit_Log__c> auditLogList = [SELECT Id FROM PS_Audit_Log__c];
		// System.assertNotEquals(0, auditLogList.size());
	}
}