unpackaged/main/default/objects/Account/fields/ProfitStars_Push_Status__c.field-meta.xml
<CustomField>
    <fullName>ProfitStars_Push_Status__c</fullName>
    <label>ProfitStars Push Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000000}</displayFormat>
        <label>Bank Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bank_Account__c/fields/ProfitStars_Push_Status__c.field-meta.xml
<CustomField>
    <fullName>ProfitStars_Push_Status__c</fullName>
    <label>Bank Account Push Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/ps_LocationUpdateRequired__c.field-meta.xml
<CustomField>
    <fullName>ps_LocationUpdateRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Location Update Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Ready_for_push_to_ProfitStars__c.field-meta.xml
<CustomField>
    <fullName>Ready_for_push_to_ProfitStars__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ready for push to ProfitStars</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/ValuePlus__c.field-meta.xml
<CustomField>
    <fullName>ValuePlus__c</fullName>
    <label>Value+</label>
    <referenceTo>ValuePlus__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/PS_Audit_Log__c/PS_Audit_Log__c.object-meta.xml
<CustomObject>
    <label>ProfitStars Callout Audit Log</label>
    <nameField>
        <displayFormat>AuditLog-{000000}</displayFormat>
        <label>ProfitStars Callout Audit Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProfitStars Callout Audit Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PS_Audit_Log__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ProfitStars Callout Audit Logs</relationshipLabel>
    <relationshipName>ProfitStars_Callout_Audit_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PS_Audit_Log__c/fields/Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Application_Type__c</fullName>
    <label>Application Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PS_Audit_Log__c/fields/Call_Type__c.field-meta.xml
<CustomField>
    <fullName>Call_Type__c</fullName>
    <description>What type of call generated this audit log</description>
    <label>Call Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Velocity</fullName>
            </value>
            <value>
                <fullName>Guid</fullName>
            </value>
            <value>
                <fullName>Field Update</fullName>
            </value>
            <value>
                <fullName>Bank Account</fullName>
            </value>
            <value>
                <fullName>Location</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/PS_Audit_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>Api returned the following Error message</description>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/PS_Audit_Log__c/fields/Raw_Json__c.field-meta.xml
<CustomField>
    <fullName>Raw_Json__c</fullName>
    <description>Holds the raw json result of the callout</description>
    <label>Raw Json</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/PS_Audit_Log__c/fields/Value_Plus__c.field-meta.xml
<CustomField>
    <fullName>Value_Plus__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Value+</label>
    <referenceTo>ValuePlus__c</referenceTo>
    <relationshipLabel>ProfitStars Callout Audit Logs</relationshipLabel>
    <relationshipName>ProfitStars_Callout_Audit_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/ValuePlus__c.object-meta.xml
<CustomObject>
    <label>Value+</label>
    <nameField>
        <displayFormat>VAS{000000}</displayFormat>
        <label>Value+</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ValuePlus</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ValuePlus__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Value+</relationshipLabel>
    <relationshipName>Value</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/ProfitStars_Push_Status__c.field-meta.xml
<CustomField>
    <fullName>ProfitStars_Push_Status__c</fullName>
    <label>ProfitStars Push Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/ps_LocationUpdateRequired__c.field-meta.xml
<CustomField>
    <fullName>ps_LocationUpdateRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ProfitStars Location Update Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Successfully_Enrolled_in_Profit_Stars_at__c.field-meta.xml
<CustomField>
    <fullName>Successfully_Enrolled_in_Profit_Stars_at__c</fullName>
    <description>This field, when populated signifies that the record has been successfully enrolled in profit stars.</description>
    <label>Successfully Enrolled in Profit Stars at</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/PS_BatchLocationUpdates.cls
/******************************************************************************************************
* copyright © 2015
*
* File		: PS_BatchLocationUpdates.cls
*
* Purpose	: This is a batch class for Location Update. Thi class identified the records for location update 
*				and instanciates the service class to send the request to profitstars
*
* Referred from 	: PS_BatchLocationScheduler.cls
*-----------------------------------------------------------------------------
*
*Release Date		Request 	Updated By			Description
*----------------------------------------------------------------------------------------------------------------------
*					Nill							Initial Creation
*
*7/21/2015			R151866		Venkat Araveeti		MyCase Integration
*******************************************************************************************************/
global class PS_BatchLocationUpdates implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful  {

	Set<PS_Audit_Log__c> logs = new Set<PS_Audit_Log__c>();
	String query;

	global PS_BatchLocationUpdates() {
		//request #R151866 updated to identify the reocrd type
		this.query = 'SELECT Id, recordType.Name, Account__r.Name FROM ValuePlus__c WHERE ps_LocationUpdateRequired__c = True AND Successfully_Enrolled_in_Profit_Stars_at__c != null';
	System.debug(query);
	}

	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext BC, List<ValuePlus__c> scope) {
		for (ValuePlus__c s : scope) {
			try {
				ps_locationReq v = new ps_locationReq(s.ID, null);
				s.ps_LocationUpdateRequired__c	 = false;
				s.ProfitStars_Push_Status__c = 'Success';
				logs.add(ProfitStarsUtils.generateAuditLogForValuePlus('Batch Location update', 'Success', JSON.serializePretty(v.response), s.id, s.recordType.Name));		//request #R151866 updated to capture application type
			} catch (Exception e) {
				//System.debug(e);
				s.ProfitStars_Push_Status__c = 'Failure';
				s.ps_LocationUpdateRequired__c	 = false;
				PS_Audit_Log__c l = new PS_Audit_Log__c();
				l.Call_type__c = 'Batch Location update';
				l.Error_Message__c = e.getMessage();
				l.Raw_Json__c = e.getStackTraceString();
				l.Value_Plus__c = s.id;
				l.Application_Type__c = s.recordType.Name;		//request #R151866 updated to capture application type
				logs.add(l);
				//Fail after first error:
				//System.debug('venkat logs are '+logs);
				//Throw new ProfitStarsIntegrationService.PSISException('Failing after first error in batch to prevent further callouts'+e.getStackTraceString());
				//ProfitStarsUtils.createAuditLogInRealtime('bank account', s.ValuePlus__c, e.getStackTraceString(), e.getMessage());
				ProfitStarsUtils.sendErrorEmail(s, 'Location Update', e.getMessage(), e.getStackTraceString(), null); //request #R151866 Added to send email with failure message
			}

		}
		list<Bank_Account__c> bankAccountsList = [select Id from Bank_Account__c where ValuePlus__c =: scope];
		for(Bank_Account__c bankAccount :bankAccountsList)
		{
			bankAccount.ps_LocationUpdateRequired__c=false;
			bankAccount.ready_for_push_to_ProfitStars__c = false;
		}
		update bankAccountsList;
		update scope;
	}

	global void finish(Database.BatchableContext BC) {
		try {
			List<ps_audit_log__c> deduped = new List<PS_Audit_Log__c>();
			deduped.addAll(logs);
			insert deduped;
		} catch (DmlException e) {
			System.debug(e.getMessage());
		}
	}

}