unpackaged/main/default/objects/Account/fields/ps_UpdateRequired__c.field-meta.xml
<CustomField>
    <fullName>ps_UpdateRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Profit Stars Update Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>zz Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Pre-Migration</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Purchased</fullName>
            </value>
            <value>
                <fullName>Lost Trial</fullName>
            </value>
            <value>
                <fullName>Purchased - Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000000}</displayFormat>
        <label>Bank Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bank_Account__c/fields/Account_Label__c.field-meta.xml
<CustomField>
    <fullName>Account_Label__c</fullName>
    <label>Account Label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/LID__c.field-meta.xml
<CustomField>
    <fullName>LID__c</fullName>
    <label>LID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Outbound_LID__c.field-meta.xml
<CustomField>
    <fullName>Outbound_LID__c</fullName>
    <description>Created by R163828</description>
    <label>Outbound LID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Outbound_Location_Update_Status__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Location_Update_Status__c</fullName>
    <label>Outbound Location Update Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready To Update</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/ps_BankAccountUpdateRequired__c.field-meta.xml
<CustomField>
    <fullName>ps_BankAccountUpdateRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bank Account Update Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/ps_LocationUpdateRequired__c.field-meta.xml
<CustomField>
    <fullName>ps_LocationUpdateRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Location Update Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Ready_for_push_to_ProfitStars__c.field-meta.xml
<CustomField>
    <fullName>Ready_for_push_to_ProfitStars__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ready for push to ProfitStars</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/ValuePlus__c.field-meta.xml
<CustomField>
    <fullName>ValuePlus__c</fullName>
    <label>Value+</label>
    <referenceTo>ValuePlus__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/PS_Audit_Log__c/PS_Audit_Log__c.object-meta.xml
<CustomObject>
    <label>ProfitStars Callout Audit Log</label>
    <nameField>
        <displayFormat>AuditLog-{000000}</displayFormat>
        <label>ProfitStars Callout Audit Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProfitStars Callout Audit Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PS_Audit_Log__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ProfitStars Callout Audit Logs</relationshipLabel>
    <relationshipName>ProfitStars_Callout_Audit_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/ValuePlus__c.object-meta.xml
<CustomObject>
    <label>Value+</label>
    <nameField>
        <displayFormat>VAS{000000}</displayFormat>
        <label>Value+</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ValuePlus</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ValuePlus__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Value+</relationshipLabel>
    <relationshipName>Value</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Outbound_MID__c.field-meta.xml
<CustomField>
    <fullName>Outbound_MID__c</fullName>
    <description>Created by R152610
Updated By  R163828</description>
    <label>Outbound MID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/ps_LocationUpdateRequired__c.field-meta.xml
<CustomField>
    <fullName>ps_LocationUpdateRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ProfitStars Location Update Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/ps_UpdateRequired__c.field-meta.xml
<CustomField>
    <fullName>ps_UpdateRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Profit Stars Update Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Successfully_Enrolled_Outbound_at__c.field-meta.xml
<CustomField>
    <fullName>Successfully_Enrolled_Outbound_at__c</fullName>
    <label>Successfully Enrolled Outbound at</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/PS_OutboundBankAccountUpdates.cls
/*
* Test class: PS_OutboundBankAccountUpdatesTest
*/
public class PS_OutboundBankAccountUpdates implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts{
	
	Set<PS_Audit_Log__c> logs = new Set<PS_Audit_Log__c>();
	String query;
	List<Bank_Account__c> bankAccountsToUpdate = new List<Bank_Account__c>();
	List<Bank_Account__c> failedUpdates = new List<Bank_Account__c>();
	Map<Id, Bank_Account__c> updatedBankAccounts = new Map<Id, Bank_Account__c>();
	
	public Database.QueryLocator start(Database.BatchableContext bc){
		return Database.getQueryLocator([Select ID, ps_LocationUpdateRequired__c, ps_UpdateRequired__c, recordType.Name, Account__r.Name, 
											(SELECT id, Account_Label__c, ps_BankAccountUpdateRequired__c, ps_LocationUpdateRequired__c, LID__c, Ready_for_push_to_ProfitStars__c 
												FROM Bank_Accounts__r where Outbound_Location_Update_Status__c='Ready To Update' and Outbound_LID__c != null) 
											FROM ValuePlus__c WHERE Id IN 
												(SELECT ValuePlus__c FROM Bank_Account__c 
													WHERE Status__c = 'Active' AND Outbound_Location_Update_Status__c='Ready To Update' and Outbound_LID__c != null) 
											AND Successfully_Enrolled_Outbound_at__c != null and Outbound_MID__c != null]);
	}
	
	public void execute(Database.BatchableContext bc, List<ValuePlus__c> scope){
		String action;
		//Savepoint sp = Database.setSavePoint();
		Bank_Account__c[] bankAccounts;
		for (ValuePlus__c s : scope) {
			bankAccounts = s.getSObjects('Bank_Accounts__r');
			log.log('Iterating with Object id: ', s.id, 'Bank Accounts = ' + bankAccounts);
			Boolean allPassed = true;
			String failedBankLabels;
			try {
				action = 'Bank Account Update for Outbound';
				ps_BankAccountReq bankResp = new ps_BankAccountReq(s.id, 'echeck');
				//this.logs.add(ProfitStarsUtils.generateAuditLogForValuePlus('Bank Account Update for Outbound', 'Success', JSON.serializePretty(bank.response) , s.id, s.recordType.Name));		
				//bankAccountsToUpdate.addAll(bankAccounts);
				if(bankResp.response != null && bankResp.response.results != null && !bankResp.response.results.isEmpty()){
					for(Bank_Account__c ba : bankAccounts){
						if(bankResp.response.results.keySet().contains(ba.Id)){
							ps_MaintRequestResults resp = bankResp.response.results.get(ba.Id);

							if(resp != null){
								if(resp.success != null && resp.success.toLowerCase() == 'true'){
									this.logs.add(ProfitStarsUtils.generateAuditLogForBankAccount(action, 'Success', JSON.serializePretty(resp), ba.Id, s.recordType.Name));		//request #R151866 updated to capture application type
									bankAccountsToUpdate.add(ba);
								}else if(resp.errorMessage != null){
									allPassed = false;
									failedBankLabels = failedBankLabels == null ? ba.Account_Label__c : failedBankLabels + ', ' + ba.Account_Label__c;
									this.logs.add(ProfitStarsUtils.generateAuditLogForBankAccount(action, 'Failure', JSON.serializePretty(resp), ba.Id, s.recordType.Name));		//request #R151866 updated to capture application type
									failedUpdates.add(ba);
								}
							}
						}
					}

					if(!allPassed){
						String errorDetails = 'The following bank account records are not successfully updated in ProfitStars: ' + failedBankLabels;
						errorDetails += '\nPlease refer to the audit log(s) on the individual bank accounts for specific error details.';
						this.logs.add(ProfitStarsUtils.generateAuditLogForValuePlus(action, 'Failure', errorDetails, s.id, s.recordType.Name));
					}else{
						this.logs.add(ProfitStarsUtils.generateAuditLogForValuePlus(action, 'Success', JSON.serializePretty(bankResp.response), s.id, s.recordType.Name));
					}
				}
			} catch (ProfitStarsRequestValidation.ProfitStarsValidationException e) {
				failedUpdates.addAll(bankAccounts);
				this.logs.add(ProfitStarsUtils.generateAuditLogForValuePlus('Pre-call Validation', e.getMessage(), e.getStackTraceString(), s.id, s.recordType.Name));		
				ProfitStarsUtils.sendErrorEmail(s, 'Bank Account Update for Outbound', e.getMessage(), e.getStackTraceString(), 'echeck'); 
			} catch (Exception e) {
				failedUpdates.addAll(bankAccounts);
				this.logs.add(ProfitStarsUtils.generateAuditLogForValuePlus(action, e.getMessage(), e.getStackTraceString(), s.id, s.recordType.Name));		
				ProfitStarsUtils.sendErrorEmail(s, 'Bank Account Update for Outbound', e.getMessage(), e.getStackTraceString(), 'echeck');
				SystemExceptionLogger.fireSystemExceptionLogEvent(e,'PS_OutboundBankAccountUpdates','execute', SystemExceptionLogger.EXCEPTION_LEVEL_CRITICAL, e.getMessage(), 'PS_OutboundBankAccountUpdates: Bank Account Update for Outbound', null, false); 
			}
		}

		try{
			update scope;
		}catch (Exception e) {
			SystemExceptionLogger.fireSystemExceptionLogEvent(e,'PS_OutboundBankAccountUpdates','execute', SystemExceptionLogger.EXCEPTION_LEVEL_CRITICAL, e.getMessage(), 'PS_OutboundBankAccountUpdates: V+ Updates', null, false); 
		}
	}
	
	public void finish(Database.BatchableContext bc){
		
		try {
			for (Bank_Account__c ba : bankAccountsToUpdate) {
				ba.Outbound_Location_Update_Status__c = 'Approved';
				updatedBankAccounts.put(ba.Id, ba);
			}
			for (Bank_Account__c b : failedUpdates) {
				b.Outbound_Location_Update_Status__c = 'Failed';
				updatedBankAccounts.put(b.Id, b);			
			}
			List<ps_audit_log__c> deduped = new List<PS_Audit_Log__c>();
			deduped.addAll(logs);
			log.error('logs to be written', deduped, 'End logs to be written ' + logs);
			insert deduped;
			//update bankAccountsToUpdate;
			//update failedUpdates;
			update updatedBankAccounts.values();
		} catch (DmlException e) {
			System.debug(e.getMessage());
			SystemExceptionLogger.fireSystemExceptionLogEvent(e,'PS_OutboundBankAccountUpdates','finish', SystemExceptionLogger.EXCEPTION_LEVEL_CRITICAL, e.getMessage(), 'PS_OutboundBankAccountUpdates: Bank Updates', null, false); 
		}
	}
}