unpackaged/main/default/objects/Account/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <description>For capturing and tracking accounts that aren&#39;t a customer, partner or competitor</description>
    <label>Other</label>
</RecordType>

unpackaged/main/default/objects/AutomationErrorLog__c/AutomationErrorLog__c.object-meta.xml
<CustomObject>
    <label>Automation Error Log</label>
    <nameField>
        <displayFormat>AELOG-{0000}</displayFormat>
        <label>Automation Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Automation Error Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AutomationErrorLog__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Automation Error Logs</relationshipLabel>
    <relationshipName>Automation_Error_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AutomationErrorLog__c/fields/Source_Application__c.field-meta.xml
<CustomField>
    <fullName>Source_Application__c</fullName>
    <label>Source Application</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GIdentify</fullName>
            </value>
            <value>
                <fullName>GVerify</fullName>
            </value>
            <value>
                <fullName>GAuthenticate</fullName>
            </value>
            <value>
                <fullName>PayNearMe</fullName>
            </value>
            <value>
                <fullName>TinCheck</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/AutomationErrorLog__c/fields/SystemExceptionLog__c.field-meta.xml
<CustomField>
    <fullName>SystemExceptionLog__c</fullName>
    <label>System Exception Log</label>
    <referenceTo>System_Exception_Log__c</referenceTo>
    <relationshipLabel>Automation Error Logs</relationshipLabel>
    <relationshipName>Automation_Error_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/AutomationErrorLog__c/fields/ValuePlus__c.field-meta.xml
<CustomField>
    <fullName>ValuePlus__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Value+</label>
    <referenceTo>ValuePlus__c</referenceTo>
    <relationshipLabel>Automation Error Logs</relationshipLabel>
    <relationshipName>Automation_Error_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000000}</displayFormat>
        <label>Bank Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bank_Account__c/fields/ValuePlus__c.field-meta.xml
<CustomField>
    <fullName>ValuePlus__c</fullName>
    <label>Value+</label>
    <referenceTo>ValuePlus__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/System_Exception_Log__c/System_Exception_Log__c.object-meta.xml
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <label>System Exception Log</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/System_Exception_Log__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>This field describes the name of the object that was being referenced when the exception occurred.</description>
    <label>Object Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/System_Exception_Log__c/fields/Object_Reference__c.field-meta.xml
<CustomField>
    <fullName>Object_Reference__c</fullName>
    <description>This field contains the Id of the object that was referenced when the error occurred,</description>
    <label>Object Reference</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/System_Exception_Log__c/fields/Source_Application__c.field-meta.xml
<CustomField>
    <fullName>Source_Application__c</fullName>
    <description>This field describes the SFDC or external application where the exception occurred</description>
    <label>Source Application</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/ValuePlus__c.object-meta.xml
<CustomObject>
    <label>Value+</label>
    <nameField>
        <displayFormat>VAS{000000}</displayFormat>
        <label>Value+</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ValuePlus</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/classes/SystemExceptionLogTriggerHandler.cls
public with sharing class SystemExceptionLogTriggerHandler extends TriggerHandler {

	//Class level variables
	private Map<Id, System_Exception_Log__c> newSystemExceptionLogMap;
	private Map<Id, System_Exception_Log__c> oldSystemExceptionLogMap;
	private List<System_Exception_Log__c> toUpdateLocation = new List<System_Exception_Log__c>();
	private List<System_Exception_Log__c> toUpdateBank = new List<System_Exception_Log__c>();

	public static boolean runBeforeUpdate = true;
	public static boolean runAfterUpdate = true;

	public static boolean runBeforeInsert = true;
	public static boolean runAfterInsert = true;	

	//Constructor
	public SystemExceptionLogTriggerHandler() {
		this.newSystemExceptionLogMap = (Map<Id, System_Exception_Log__c>) Trigger.newMap;
		this.oldSystemExceptionLogMap = (Map<Id, System_Exception_Log__c>) Trigger.oldMap;
	}

	public static boolean runBeforeUpdateOnce () {	
		if (runBeforeUpdate) {
			runBeforeUpdate=false;
			return true;
		} else {
			return runBeforeUpdate;
		}
	}

	public static boolean runAfterUpdateOnce () {
		if (runAfterUpdate) {
			runAfterUpdate=false;
			return true;
		} else {
			return runAfterUpdate;
		}
	}
	public static boolean runBeforeInsertOnce () {
		if (runBeforeInsert) {
			runBeforeInsert=false;
			return true;
		} else {
			return runBeforeInsert;
		}
	}

	public static boolean runAfterInsertOnce () {
		if (runAfterInsert) {
			runAfterInsert=false;
			return true;
		} else {
			return runAfterInsert;
		}
	}


	//This is the context method executed when the trigger fires in an AfterUpdate context.
	//it should contain nothing but calls to other methods. logicless!
	public override void afterUpdate() {
		TriggerHandler.bypass('SystemExceptionLogTriggerHandler');
		TriggerHandler.clearBypass('SystemExceptionLogTriggerHandler');
	}

	public override void afterInsert() {
		TriggerHandler.bypass('SystemExceptionLogTriggerHandler');
		List<AutomationErrorLog__c> sysErrors = new List<AutomationErrorLog__c>();
		for (SObject record : Trigger.new) {
			System_Exception_Log__c log = (System_Exception_Log__c) record;
			if (!String.isEmpty(log.Object_Name__c)) {
				if (log.Object_Name__c.equals ('ValuePlus')) {
					sysErrors.add(new AutomationErrorLog__c(ValuePlus__c=Id.valueOf(log.Object_Reference__c), SystemExceptionLog__c=log.Id, Source_Application__c=log.Source_Application__c));
				} else if (log.Object_Name__c.equals ('BankAccount')) {
					sysErrors.add(new AutomationErrorLog__c(Bank_Account__c=Id.valueOf(log.Object_Reference__c), SystemExceptionLog__c=log.Id, Source_Application__c=log.Source_Application__c));
				}	
			}
		}
		insert sysErrors;
		TriggerHandler.clearBypass('SystemExceptionLogTriggerHandler');
	}

	public override void beforeInsert() {
		// This will prevent the trigger from creating the a Bank Account if there are some Bank accounts with the same Account Labels.
		// Find a map of the value plus records which are having a bank account with Account Label as this 
	}

	public override void beforeUpdate() {
	}



	

	/**
	 * didChange returns a boolean indicating of the old and
	 * new versions of a given field are different
	 * @param  String          field				Field name to retrieve from sObject record for comparison
	 * @param  Bank_Account__c old          Old version of the bank account record to be tested.
	 * @param  Bank_Account__c knew         New version of the bank account record to be tested.
	 * @return Boolean                 			true if the old version and the new version of the field are different.
	 */
	private boolean didChange(String field, Bank_Account__c old, Bank_Account__c knew) {
		return (old.get(field) != knew.get(field)) ? true : false;
	}


}