unpackaged/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Used to capture and track partners; may be used for the partners that are purchasing services or software as well</description>
    <label>Partner</label>
</RecordType>

unpackaged/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000000}</displayFormat>
        <label>Bank Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bank_Account__c/fields/Account_Label__c.field-meta.xml
<CustomField>
    <fullName>Account_Label__c</fullName>
    <label>Account Label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/AccountNo__c.field-meta.xml
<CustomField>
    <fullName>AccountNo__c</fullName>
    <label>Account #</label>
    <length>17</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/LID__c.field-meta.xml
<CustomField>
    <fullName>LID__c</fullName>
    <label>LID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Location_Add_Status__c.field-meta.xml
<CustomField>
    <fullName>Location_Add_Status__c</fullName>
    <inlineHelpText>Submitted - ProfitStars is processing the request
Approved - ProfitStars approved the request and provided LID
Completed - LID updated to APM</inlineHelpText>
    <label>Location Add Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Outbound_LID__c.field-meta.xml
<CustomField>
    <fullName>Outbound_LID__c</fullName>
    <description>Created by R163828</description>
    <label>Outbound LID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Outbound_Location_Add_Status__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Location_Add_Status__c</fullName>
    <label>Outbound Location Add Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready To Transmit</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/RoutingNo__c.field-meta.xml
<CustomField>
    <fullName>RoutingNo__c</fullName>
    <label>Routing #</label>
    <length>9</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/ValuePlus__c.field-meta.xml
<CustomField>
    <fullName>ValuePlus__c</fullName>
    <label>Value+</label>
    <referenceTo>ValuePlus__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/PS_Audit_Log__c/PS_Audit_Log__c.object-meta.xml
<CustomObject>
    <label>ProfitStars Callout Audit Log</label>
    <nameField>
        <displayFormat>AuditLog-{000000}</displayFormat>
        <label>ProfitStars Callout Audit Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProfitStars Callout Audit Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PS_Audit_Log__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ProfitStars Callout Audit Logs</relationshipLabel>
    <relationshipName>ProfitStars_Callout_Audit_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/System_Exception_Log__c/System_Exception_Log__c.object-meta.xml
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <label>System Exception Log</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ValuePlus__c/ValuePlus__c.object-meta.xml
<CustomObject>
    <label>Value+</label>
    <nameField>
        <displayFormat>VAS{000000}</displayFormat>
        <label>Value+</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ValuePlus</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ValuePlus__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Value+</relationshipLabel>
    <relationshipName>Value</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Outbound_MID__c.field-meta.xml
<CustomField>
    <fullName>Outbound_MID__c</fullName>
    <description>Created by R152610
Updated By  R163828</description>
    <label>Outbound MID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/ProfitStars_Merchant_ID__c.field-meta.xml
<CustomField>
    <fullName>ProfitStars_Merchant_ID__c</fullName>
    <label>ProfitStars Merchant ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sold/Not Started</fullName>
            </value>
            <value>
                <fullName>KOC Confirmed</fullName>
                <label>Questionnaire Received</label>
            </value>
            <value>
                <fullName>Sold/Not Ready</fullName>
            </value>
            <value>
                <fullName>On-Boarding</fullName>
            </value>
            <value>
                <fullName>KOC Scheduled</fullName>
            </value>
            <value>
                <fullName>KOC Complete</fullName>
            </value>
            <value>
                <fullName>Build In Progress</fullName>
            </value>
            <value>
                <fullName>Site Presentation</fullName>
            </value>
            <value>
                <fullName>Site Delivered/Final Changes</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Additional Communication (O)</fullName>
            </value>
            <value>
                <fullName>Agreement Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Content Acquisition</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Deferred-Built</fullName>
            </value>
            <value>
                <fullName>Deferred-Canceled</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Final Changes</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Left APM</fullName>
            </value>
            <value>
                <fullName>Left IM</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Live-Free Trial</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Lost During Pilot</fullName>
            </value>
            <value>
                <fullName>Lost In Onboarding</fullName>
            </value>
            <value>
                <fullName>Multi Site Deffered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/PS_UpdateLIDsOnBankAccountsTest.cls
/*
* Test class for the PS_UpdateLIDsOnBankAccounts class.
*/
@isTest
private class PS_UpdateLIDsOnBankAccountsTest{

	static String successInboundLIDResp = '{"HTTPStatusCode":"200","GetLocationByLocationName":{"GetLocationByLocationNameResult":{"AccountNumberLast4":"1960","AccountType":"Checking","CustServProviderId":"268009","CustomerLocationNumber":"true","EntityId":"589801","LocationEnabled":true,"LocationId":"4139121","LocationName":"Test Bank Account0","MerchantName":"Test Account0-a1l4D00000076pPQAQ","RoutingNumber":"053000196"}}}';
	static String successOutboundLIDResp = '{"HTTPStatusCode":"200","GetLocationByLocationName":{"GetLocationByLocationNameResult":{"AccountNumberLast4":"1960","AccountType":"Checking","CustServProviderId":"258030","CustomerLocationNumber":"true","EntityId":"588601","LocationEnabled":true,"LocationId":"4139122","LocationName":"Test Bank Account0","MerchantName":"Test Account0-a1l4D00000076pPQAQ","RoutingNumber":"053000196"}}}';
	static String exceptionResp = '{"HTTPStatusCode":null,"GetLocationByLocationName":{"GetLocationByLocationNameResult":{"AccountNumberLast4":"1960","AccountType":"Checking","CustServProviderId":"268009","CustomerLocationNumber":"true","EntityId":"589801","LocationEnabled":true,"LocationId":true,"LocationName":"Test Bank Account0","MerchantName":"Test Account0-a1l4D00000076pPQAQ","RoutingNumber":"053000196"}}}';
	static String errorResp = '{"ErrorMessage": "This Merchant (Entity Id) is not associated with this Partner","ErrorCode": "401"}';

    //Creates test data that is used by the unit tests in this class.
    @TestSetup
    public static void createTestData(){
        TestDataFactory.createCustomSettings();

        TestDataFactory.DataModel dm = new TestDataFactory.DataModel(1, false);
		//insert accounts
		// dm.accountList[0].RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('MyCase Account').getRecordTypeId();
		INSERT(dm.accountList);
		
		//insert valuePlus
		dm.valueplusList[0].Account__c = dm.accountList[0].Id;
		dm.valueplusList[0].RecordTypeId = Schema.SObjectType.ValuePlus__c.getRecordTypeInfosByName().get('MyCase Payments').getRecordTypeId();
		dm.valueplusList[0].Stage__c = 'Sold/Not Started';
		dm.valueplusList[0].ProfitStars_Merchant_ID__c = '589801';
		//dm.valueplusList[0].Outbound_MID__c = '588601';
		INSERT(dm.valuePlusList[0]);

		//insert bank accounts
		dm.bankAccountList[0].ValuePlus__c = dm.valueplusList[0].Id;
		dm.bankAccountList[0].RoutingNo__c = '053000196';
		dm.bankAccountList[0].AccountNo__c = '0530001960';
		dm.bankAccountList[0].Location_Add_Status__c = 'Submitted';
		//dm.bankAccountList[0].Outbound_Location_Add_Status__c = 'Submitted';
		INSERT(dm.bankAccountList[0]);

		TestUtils.genTestSettings(true);
		TestUtils.genOutboundTestSettings(true);
		TestUtils.genEcheckFieldsTestSettings(true);
    }
    
    public static testMethod void testInboundLIDUpdate(){
        Test.setMock(HttpCalloutMock.class, new RestClientCalloutMockFactory(200, 'Success', successInboundLIDResp, null));
								 
		Test.startTest();
		PS_UpdateLIDsOnBankAccounts updateLIDJob = new PS_UpdateLIDsOnBankAccounts();
		ID batchprocessid = Database.executeBatch(updateLIDJob);
		Test.stopTest();

		Bank_Account__c ba = [Select id, LID__c, Location_Add_Status__c from Bank_Account__c where Account_Label__c = 'Test Bank Account0'];
		System.assertEquals('4139121', ba.LID__c);
		System.assertEquals('Approved', ba.Location_Add_Status__c);
    }

    public static testMethod void testOutboundLIDUpdate(){
        Test.setMock(HttpCalloutMock.class, new RestClientCalloutMockFactory(200, 'Success', successOutboundLIDResp, null));

        ValuePlus__c vp = [Select id, ProfitStars_Merchant_ID__c, Outbound_MID__c from ValuePlus__c where ProfitStars_Merchant_ID__c = '589801'];
        vp.ProfitStars_Merchant_ID__c = null;
        vp.Outbound_MID__c = '588601';
        update vp;

        Bank_Account__c bankAcc = [Select id, Outbound_Location_Add_Status__c, Location_Add_Status__c from Bank_Account__c where Account_Label__c = 'Test Bank Account0'];
        bankAcc.Outbound_Location_Add_Status__c = 'Submitted';
        update bankAcc;
								 
		Test.startTest();
		PS_UpdateLIDsOnBankAccounts updateLIDJob = new PS_UpdateLIDsOnBankAccounts();
		ID batchprocessid = Database.executeBatch(updateLIDJob);
		Test.stopTest();

		Bank_Account__c ba = [Select id, Outbound_LID__c, Outbound_Location_Add_Status__c from Bank_Account__c where Account_Label__c = 'Test Bank Account0'];
		System.assertEquals('4139122', ba.Outbound_LID__c);
		System.assertEquals('Approved', ba.Outbound_Location_Add_Status__c);
    }

    public static testMethod void testInboundErrorResponse(){
        Test.setMock(HttpCalloutMock.class, new RestClientCalloutMockFactory(401, 'Error', errorResp, null));
								 
		Test.startTest();
		PS_UpdateLIDsOnBankAccounts updateLIDJob = new PS_UpdateLIDsOnBankAccounts();
		ID batchprocessid = Database.executeBatch(updateLIDJob);
		Test.stopTest();

		List<PS_Audit_Log__c> auditLogList = [SELECT Id FROM PS_Audit_Log__c];
		System.assertNotEquals(0, auditLogList.size());
    }

    public static testMethod void testOutboundErrorResponse(){
        Test.setMock(HttpCalloutMock.class, new RestClientCalloutMockFactory(401, 'Error', errorResp, null));
								 
		ValuePlus__c vp = [Select id, ProfitStars_Merchant_ID__c, Outbound_MID__c from ValuePlus__c where ProfitStars_Merchant_ID__c = '589801'];
        vp.ProfitStars_Merchant_ID__c = null;
        vp.Outbound_MID__c = '588601';
        update vp;

        Bank_Account__c bankAcc = [Select id, Outbound_Location_Add_Status__c, Location_Add_Status__c from Bank_Account__c where Account_Label__c = 'Test Bank Account0'];
        bankAcc.Outbound_Location_Add_Status__c = 'Submitted';
        update bankAcc;
								 
		Test.startTest();
		PS_UpdateLIDsOnBankAccounts updateLIDJob = new PS_UpdateLIDsOnBankAccounts();
		ID batchprocessid = Database.executeBatch(updateLIDJob);
		Test.stopTest();

		List<PS_Audit_Log__c> auditLogList = [SELECT Id FROM PS_Audit_Log__c];
		System.assertNotEquals(0, auditLogList.size());
    }

    public static testMethod void testException(){
        Test.setMock(HttpCalloutMock.class, new RestClientCalloutMockFactory(200, 'Success', exceptionResp, null));
								 
		Test.startTest();
		PS_UpdateLIDsOnBankAccounts updateLIDJob = new PS_UpdateLIDsOnBankAccounts();
		ID batchprocessid = Database.executeBatch(updateLIDJob);
		Test.stopTest();

		List<System_Exception_Log__c> exceptionLogList = [SELECT Id FROM System_Exception_Log__c];
		// System.assertNotEquals(0, exceptionLogList.size());
    }
}