unpackaged/main/default/objects/Add_On_Batch__c/Add_On_Batch__c.object-meta.xml
<CustomObject>
    <label>Bank Account Add-On Batch</label>
    <nameField>
        <displayFormat>AO{000000}</displayFormat>
        <label>Bank Account Add-On Batch</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Account Add-On Batches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000000}</displayFormat>
        <label>Bank Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bank_Account__c/fields/Bank_Account_Add_On_Batch__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Add_On_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account Add-On Batch</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Add_On_Batch__c.ValuePlus__c</field>
            <operation>equals</operation>
            <valueField>$Source.ValuePlus__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Add_On_Batch__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/LID__c.field-meta.xml
<CustomField>
    <fullName>LID__c</fullName>
    <label>LID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Ready_for_push_to_ProfitStars__c.field-meta.xml
<CustomField>
    <fullName>Ready_for_push_to_ProfitStars__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ready for push to ProfitStars</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/PS_BatchOutboundBankAddOnBatchSubmit.cls
global class PS_BatchOutboundBankAddOnBatchSubmit implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {

	String query = '';
	public PS_BatchOutboundBankAddOnBatchSubmit(id batchaddonid) {
		query = 'SELECT Id, Name, LID__c, Ready_for_push_to_ProfitStars__c, Bank_Account_Add_On_Batch__r.Name from Bank_Account__c where Bank_Account_Add_On_Batch__r.id = \'' + batchaddonid +'\'' +  'and Status__c = \'Active\'';
		System.debug(query);
	}

	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext BC, List<Bank_Account__c> scope) {

		for (Bank_Account__c bankAccount : scope) {
			String res = ps_eCheckButtonMethods.callLocation(bankAccount.id);
		}
	}

	global void finish(Database.BatchableContext BC) {

	}
}