unpackaged/main/default/objects/Add_On_Batch__c/Add_On_Batch__c.object-meta.xml
<CustomObject>
    <label>Bank Account Add-On Batch</label>
    <nameField>
        <displayFormat>AO{000000}</displayFormat>
        <label>Bank Account Add-On Batch</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Account Add-On Batches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Add_On_Batch__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client Requested</fullName>
            </value>
            <value>
                <fullName>Bank Auth Form Sent</fullName>
            </value>
            <value>
                <fullName>Ready for Cybersource</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>No Response</fullName>
            </value>
            <value>
                <fullName>Request Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Add_On_Batch__c/fields/ValuePlus__c.field-meta.xml
<CustomField>
    <fullName>ValuePlus__c</fullName>
    <label>Value+</label>
    <referenceTo>ValuePlus__c</referenceTo>
    <relationshipLabel>Bank Account Add-On Batches</relationshipLabel>
    <relationshipName>Bank_Account_Add_On_Batches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000000}</displayFormat>
        <label>Bank Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bank_Account__c/fields/AccountNo__c.field-meta.xml
<CustomField>
    <fullName>AccountNo__c</fullName>
    <label>Account #</label>
    <length>17</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Bank_Account_Add_On_Batch__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Add_On_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account Add-On Batch</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Add_On_Batch__c.ValuePlus__c</field>
            <operation>equals</operation>
            <valueField>$Source.ValuePlus__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Add_On_Batch__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Outbound_Location_Add_Status__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Location_Add_Status__c</fullName>
    <label>Outbound Location Add Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready To Transmit</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/ps_LocationUpdateRequired__c.field-meta.xml
<CustomField>
    <fullName>ps_LocationUpdateRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Location Update Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Ready_for_push_to_ProfitStars__c.field-meta.xml
<CustomField>
    <fullName>Ready_for_push_to_ProfitStars__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ready for push to ProfitStars</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/RoutingNo__c.field-meta.xml
<CustomField>
    <fullName>RoutingNo__c</fullName>
    <label>Routing #</label>
    <length>9</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/ValuePlus__c.field-meta.xml
<CustomField>
    <fullName>ValuePlus__c</fullName>
    <label>Value+</label>
    <referenceTo>ValuePlus__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/ValuePlus__c.object-meta.xml
<CustomObject>
    <label>Value+</label>
    <nameField>
        <displayFormat>VAS{000000}</displayFormat>
        <label>Value+</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ValuePlus</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ValuePlus__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Value+</relationshipLabel>
    <relationshipName>Value</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/ps_LocationUpdateRequired__c.field-meta.xml
<CustomField>
    <fullName>ps_LocationUpdateRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ProfitStars Location Update Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/ps_VelocityUpdateRequired__c.field-meta.xml
<CustomField>
    <fullName>ps_VelocityUpdateRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Velocity Update Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sold/Not Started</fullName>
            </value>
            <value>
                <fullName>KOC Confirmed</fullName>
                <label>Questionnaire Received</label>
            </value>
            <value>
                <fullName>Sold/Not Ready</fullName>
            </value>
            <value>
                <fullName>On-Boarding</fullName>
            </value>
            <value>
                <fullName>KOC Scheduled</fullName>
            </value>
            <value>
                <fullName>KOC Complete</fullName>
            </value>
            <value>
                <fullName>Build In Progress</fullName>
            </value>
            <value>
                <fullName>Site Presentation</fullName>
            </value>
            <value>
                <fullName>Site Delivered/Final Changes</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Additional Communication (O)</fullName>
            </value>
            <value>
                <fullName>Agreement Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Content Acquisition</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Deferred-Built</fullName>
            </value>
            <value>
                <fullName>Deferred-Canceled</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Final Changes</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Left APM</fullName>
            </value>
            <value>
                <fullName>Left IM</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Live-Free Trial</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Lost During Pilot</fullName>
            </value>
            <value>
                <fullName>Lost In Onboarding</fullName>
            </value>
            <value>
                <fullName>Multi Site Deffered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Successfully_Enrolled_in_Profit_Stars_at__c.field-meta.xml
<CustomField>
    <fullName>Successfully_Enrolled_in_Profit_Stars_at__c</fullName>
    <description>This field, when populated signifies that the record has been successfully enrolled in profit stars.</description>
    <label>Successfully Enrolled in Profit Stars at</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/PS_BatchBankAddOnBatchSubmitTest.cls
@isTest
private class PS_BatchBankAddOnBatchSubmitTest {
	static testmethod void buttonMethodsTest(){
		List<Account> a = new List<Account>();
		for (Integer i=0;i<10;i++){
			Account acct = new Account(Name = 'TestAccount' + i);
			a.add(acct);
		}
		insert a[0];
		system.debug('first account id'+a[0].Id);
		
		ValuePlus__c valuePlus = new ValuePlus__c(Account__c=a[0].Id, ps_LocationUpdateRequired__c=true,
														ps_VelocityUpdateRequired__c = True, Successfully_Enrolled_in_Profit_Stars_at__c=System.today(), recordTypeId = TestUtils.getRecordTypeIdFromSObjectAndName('ValuePlus__c', 'MyCase Payments'));
		insert valuePlus;
		
		/*Add_On_Batch__c addOnBatch = new Add_On_Batch__c(ValuePlus__c=valuePlus.Id, Stage__c='Ready for Profitstars');
		insert addOnBatch;*/
		
		Add_On_Batch__c bankAccountAddon = new Add_On_Batch__c (ValuePlus__c = valuePlus.Id);
		insert bankAccountAddon;

		Bank_Account__c bankAccount = new Bank_Account__c(ValuePlus__c=valuePlus.Id, RoutingNo__c='123456789',
										AccountNo__c='12345678912345678',Ready_for_push_to_ProfitStars__c=true,
										ps_LocationUpdateRequired__c = True, Bank_Account_Add_On_Batch__c= bankAccountAddon.id,
										Outbound_Location_Add_Status__c='Ready To Transmit');
		insert bankAccount;
		
		Test.startTest();
		String response = ps_BankAccountAddonbuttonMethods.CallBankAddonBatch(bankAccountAddon.Id);
		String response1 = ps_BankAccountAddonbuttonMethods.CallBankAddonBatchOutbound(bankAccountAddon.Id);
		Test.stopTest();
        // Set the mock callout mode
       //Test.setMock(HttpCalloutMock.class, new ProfitStarsMockResponse());
	}
}