unpackaged/main/default/objects/Case/fields/Case_Resolution__c.field-meta.xml
<CustomField>
    <fullName>Case_Resolution__c</fullName>
    <description>What form of communication primarily used to resolve the case?</description>
    <label>Case Communication</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin/Duplicate</fullName>
            </value>
            <value>
                <fullName>Call</fullName>
            </value>
            <value>
                <fullName>Copy of Report</fullName>
            </value>
            <value>
                <fullName>Data Migration Request Complete</fullName>
            </value>
            <value>
                <fullName>Documents Received</fullName>
            </value>
            <value>
                <fullName>E-Mail</fullName>
            </value>
            <value>
                <fullName>Email: Elaborate explanation</fullName>
            </value>
            <value>
                <fullName>Email: Quick confirmation</fullName>
            </value>
            <value>
                <fullName>Hang up / No Vmail</fullName>
            </value>
            <value>
                <fullName>Help Article</fullName>
            </value>
            <value>
                <fullName>Investigated with CIC</fullName>
            </value>
            <value>
                <fullName>Investigated with CIC &amp; Experian</fullName>
            </value>
            <value>
                <fullName>Investigated with CL</fullName>
            </value>
            <value>
                <fullName>Investigated with CL and Experian</fullName>
            </value>
            <value>
                <fullName>Investigated with Experian</fullName>
            </value>
            <value>
                <fullName>Investigated with RentBureau</fullName>
            </value>
            <value>
                <fullName>Issue Entered as Bug</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>No Response</fullName>
            </value>
            <value>
                <fullName>Notified CR</fullName>
            </value>
            <value>
                <fullName>Notified V+ Support</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Phone: Elaborate explanation</fullName>
            </value>
            <value>
                <fullName>Phone: Left voicemail or message for contact&#39;</fullName>
            </value>
            <value>
                <fullName>Phone: Quick confirmation</fullName>
            </value>
            <value>
                <fullName>Post/Mail</fullName>
            </value>
            <value>
                <fullName>Provided Solution from Self-Knowledge</fullName>
            </value>
            <value>
                <fullName>Provided Solution from Tech / Dev</fullName>
            </value>
            <value>
                <fullName>Provided Solution in Solution Database</fullName>
            </value>
            <value>
                <fullName>Quick Response Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/DontAssign__c.field-meta.xml
<CustomField>
    <fullName>DontAssign__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if we shouldn&#39;t assign though assignment rules</description>
    <label>DontAssign</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Escalation_Assignee__c.field-meta.xml
<CustomField>
    <fullName>Escalation_Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>R1812440;  Modified FLS for R1919025</description>
    <label>Escalation Assignee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases7</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Escalation_Status__c.field-meta.xml
<CustomField>
    <fullName>Escalation_Status__c</fullName>
    <description>R1812440; Modified FLS &amp; added new picklist values for R1919025</description>
    <label>Escalation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Escalated</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Investigating</fullName>
            </value>
            <value>
                <fullName>Delegated</fullName>
            </value>
            <value>
                <fullName>Waiting on CSM</fullName>
            </value>
            <value>
                <fullName>Confirmed Bug</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Unresponsive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Billing_MyCase.recordType-meta.xml
<RecordType>
    <fullName>Billing_MyCase</fullName>
    <active>true</active>
    <businessProcess>Billing</businessProcess>
    <label>Billing - MyCase</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/MyCase.recordType-meta.xml
<RecordType>
    <fullName>MyCase</fullName>
    <active>true</active>
    <businessProcess>MyCase</businessProcess>
    <label>MyCase</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/MyCase_Accounting.recordType-meta.xml
<RecordType>
    <fullName>MyCase_Accounting</fullName>
    <active>true</active>
    <businessProcess>MyCase Support</businessProcess>
    <label>MyCase Accounting</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/MyCase_Support.recordType-meta.xml
<RecordType>
    <fullName>MyCase_Support</fullName>
    <active>true</active>
    <businessProcess>MyCase Support</businessProcess>
    <label>MyCase Support</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/MyCase_Websites.recordType-meta.xml
<RecordType>
    <fullName>MyCase_Websites</fullName>
    <active>true</active>
    <businessProcess>MyCase Websites</businessProcess>
    <description>R176835</description>
    <label>MyCase Websites</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/Risk.recordType-meta.xml
<RecordType>
    <fullName>Risk</fullName>
    <active>true</active>
    <businessProcess>Risk</businessProcess>
    <description>Case Record Type to track risky behavior</description>
    <label>Risk</label>
</RecordType>

unpackaged/main/default/classes/MyCaseSendToButtonsController.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* This is the apex controller for the MycaseSendToButtons component
* 
* @test           MyCaseSendToButtonsControllerTest
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         
* @modifiedBy     Hunter Hamaker <hunter.hamaker@appfolio.com>
* @maintainedBy   
* @version        1.1
* @created        2020-07-01
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* v1.1            hunter.hamaker@appfolio.com
* 2020-07-01      Initial Build - R2027861  
*
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/
public class MyCaseSendToButtonsController {

    public class MyCaseSendToButtonsControllerException extends Exception {}

    @AuraEnabled
    public static Boolean routeCase(String recordId, String caseQueue) {    
        try {
            Map<String, Id> recordtypeMap = new Map<String, Id>();
            Map<String, Id> queueMap = new Map<String, Id>();

            //get all record types and put them into map
            List<RecordType> recordTypeList = [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType = 'Case'];
            for(RecordType rt  : recordTypeList){
                recordtypeMap.put(rt.DeveloperName, rt.Id);
                System.debug('recordType Dev Name: ' + rt.DeveloperName + ' Id: ' + rt.Id);
            }
            
            //get all queues and put them into map
            List<Group> queueList = [SELECT Id, DeveloperName FROM Group WHERE Type = 'Queue'];
            for(Group queue : queueList){
                queueMap.put(queue.DeveloperName, queue.Id);
                System.debug('Name: ' + queue.DeveloperName + ' id: ' + queue.Id);
            }
            
            Case c = [SELECT Id, RecordTypeId, Status, Type, Reason, Case_Sub_Reason__c, ContactId, OwnerId FROM Case WHERE Id =: recordId];
            
            Map<Id, User> userMap = new Map<Id, User>([SELECT Id, Profile.Name, UserRoleId FROM User WHERE Id =: UserInfo.getUserId() OR Id =: c.OwnerId]);

            User currentUser = userMap.get(UserInfo.getUserId());
            User currentOwner = userMap.get(c.OwnerId);

            switch on caseQueue{
                when 'ownThisCase'{
                    // R2030368 - This condition is a temporary fix to restrict CS reps from owning each others' cases. Waiting for Salesforce Support to get back with a permanent fix.
                    // if(c.OwnerId != null && currentOwner != null){
                        // throw new MyCaseSendToButtonsControllerException('You don’t have permission to take that action on this record or related records. For help, contact your Salesforce admin.');
                    // } else {
                        c.OwnerId = currentUser.Id;
                        c.Status = 'In Progress';
                        c.DontAssign__c = TRUE;
                    // }
                }
                when 'sendToCS'{
                    c.Status = 'New';
                    c.OwnerID = queueMap.get('MyCase_Team');
                    c.RecordTypeID = recordtypeMap.get('MyCase_Support');
                    c.DontAssign__c = TRUE;
                }
                when 'closeAsSpam'{
                    if(c.RecordTypeId == recordtypeMap.get('MyCase_Support') && c.Status == 'New' && c.OwnerId == queueMap.get('MyCase_Team')){
                        throw new MyCaseSendToButtonsControllerException('Please own the case first!');
                    } else {
                        c.Status = 'Closed';
                        c.Reason = 'Admin/Duplicates';
                        c.DontAssign__c = TRUE;
                    }
                }
                when 'escalate' {
                    if(c.RecordTypeId == recordtypeMap.get('MyCase_Support') && c.Status == 'New' && c.OwnerId == queueMap.get('MyCase_Team')){
                        throw new MyCaseSendToButtonsControllerException('Please own the case first!');
                    } else {
                        
                        if(c.Status != 'Escalated'){
                            c.Status = 'Escalated';
                            c.Priority = 'Escalated';
                            c.Escalation_Status__c = 'New';
	                        c.DontAssign__c = TRUE;
                        }else{
                            throw new MyCaseSendToButtonsControllerException('This case is already in Escalated status');
                        }
                    }
                }
                when 'ownEscalation' {
                    // if(currentUser.Profile.Name != 'MyCase Developer'&&currentUser.Profile.Name != 'MyCase Service'){
                    //     throw new MyCaseSendToButtonsControllerException('Only MyCase Developers Can Own Escalations');
                    // } else if(currentUser.Profile.Name == 'MyCase Developer'||currentUser.Profile.Name == 'MyCase Service')
                    // {
                        c.Escalation_Assignee__c = currentUser.Id;
                        c.Escalation_Status__c = 'Investigating';
                        c.DontAssign__c = TRUE;
                    // }
                }
                when 'sendToSalesMycase' {
                    c.Status = 'Closed';
                    c.Reason = 'Sent to Sales';
                    c.DontAssign__c = TRUE;
                }
                when 'sendToPayments' {
                    c.OwnerId = queueMap.get('MyCase_Payments');
                    c.RecordTypeId = recordtypeMap.get('MyCase');
                    c.Status = 'New';
                    c.DontAssign__c = TRUE;
                }
                when 'sendToBilling' {
					if(c.Case_Sub_Reason__c == 'Refund/Credit'){
                        throw new MyCaseSendToButtonsControllerException('Cases with Sub Reason of "Refund/Credit" need to be approved, please cancel and click "Submit for Approval.');
                    }

                    if(String.isEmpty(c.ContactId)){
                    	throw new MyCaseSendToButtonsControllerException('You must associated a contact with the case before it can be sent to Billing.');
                    }
                    c.RecordTypeId = recordtypeMap.get('Billing_MyCase');
                    c.OwnerId = queueMap.get('MyCase_Billing');
					c.Status = 'New';
                    c.DontAssign__c = TRUE;
                }
                when 'sendToWebsites' {
                    c.OwnerId = queueMap.get('MyCase_Websites');
                    c.RecordTypeId = recordtypeMap.get('MyCase_Websites');
					c.Status = 'New';
                    c.DontAssign__c = TRUE;
                }
                when 'billingCase' {
                    c.RecordTypeId = recordtypeMap.get('Billing_MyCase');
					c.Reason = 'MyCase Billing';
                }
                when 'adminDupe'{
                    c.Status = 'Closed';
                    c.Reason = 'Admin/Duplicates';
                    c.Type = 'Other';
                    c.DontAssign__c = TRUE;
                    if(c.RecordTypeId == recordtypeMap.get('Risk')){
                        c.Case_Resolution__c = 'Admin/Duplicate';
                    }
                }
                when 'sendToAccounting' {
                    system.debug('Send to Accounting Queue: ' + recordId);
                    c.Id = recordId;
                    c.RecordTypeId = recordtypeMap.get('MyCase_Support');
                    c.Status = 'New';
                    c.OwnerId = queueMap.get('MyCase_Accounting');


                }
            }
            
            Database.SaveResult sr = Database.UPDATE(c);
            if (sr.isSuccess()){
                return true;
            } else {
                return false;
            }
        } catch(Exception e) {
            //throw all other exception message
            if(!Test.isRunningTest()){
                AuraHandledException auraEx = new AuraHandledException(e.getMessage());
                auraEx.setMessage(e.getMessage());
                throw auraEx;
            } else {
                return false;
            }
        }
    }
}