unpackaged/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000000}</displayFormat>
        <label>Bank Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bank_Account__c/fields/ValuePlus__c.field-meta.xml
<CustomField>
    <fullName>ValuePlus__c</fullName>
    <label>Value+</label>
    <referenceTo>ValuePlus__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Vantiv_Bank_Account_Onboarding_Status__c.field-meta.xml
<CustomField>
    <fullName>Vantiv_Bank_Account_Onboarding_Status__c</fullName>
    <label>Vantiv Bank Account Onboarding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready To Transmit</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Manual Review</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Vantiv_Sub_Merchant_Id__c.field-meta.xml
<CustomField>
    <fullName>Vantiv_Sub_Merchant_Id__c</fullName>
    <label>Vantiv Sub Merchant Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/ValuePlus__c.object-meta.xml
<CustomObject>
    <label>Value+</label>
    <nameField>
        <displayFormat>VAS{000000}</displayFormat>
        <label>Value+</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ValuePlus</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ValuePlus__c/fields/Vantiv_Legal_Entity_Id__c.field-meta.xml
<CustomField>
    <fullName>Vantiv_Legal_Entity_Id__c</fullName>
    <label>Vantiv Legal Entity Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Vantiv_Onboarding_Status__c.field-meta.xml
<CustomField>
    <fullName>Vantiv_Onboarding_Status__c</fullName>
    <label>Vantiv Onboarding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready To Transmit</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Manual Review</fullName>
            </value>
            <value>
                <fullName>Manual Review - Duplicate</fullName>
            </value>
            <value>
                <fullName>Manual Review - Background Check Error</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Collecting Documents</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/VantivRequestValidation.cls
public with sharing class VantivRequestValidation {
	
	public class VantivRequestValidationException extends Exception{}
	
	Public Boolean hasError = false;
	Private sObject record;
	Private Map<String, sObject> requiredFields;
	Private String action;
	
	public VantivRequestValidation(sObject record, Map<String, sObject> reqFields, String action)
	{
		this.record = record;
		this.requiredFields = reqFields;
		this.action = action;
		
		if('LegalEntityCreateRequest'.equalsIgnoreCase(action) 
			|| 'LegalEntityUpdateRequest'.equalsIgnoreCase(action) 
			|| 'LegalEntityPrincipalCreateRequest'.equalsIgnoreCase (action) 
			|| 'LegalEntityPrincipal3Create'.equalsIgnoreCase (action)
			|| 'LegalEntityPrincipal4Create'.equalsIgnoreCase (action)) 
		{
			canMakeLegalEntityCall();
		}
		else if('SubMerchantCreateRequest'.equalsIgnoreCase(action) || 'SubMerchantUpdateRequest'.equalsIgnoreCase(action))
		{
			canMakeSubMerchantCall();
		}
		else
		{
			throw new VantivRequestValidationException('Unable to validate request for action '+action);
		}
	}
	
	private void canMakeLegalEntityCall()
	{
		validateRequiredFields();
		if(('Approved'.equalsIgnoreCase((String)record.get('Vantiv_Onboarding_Status__c')) && (String) record.get('Vantiv_Legal_Entity_Id__c') == null))
		{
			throw new VantivRequestValidationException('Legal entity id unavailable.');
		}
	}
	
	private void canMakeSubMerchantCall()
	{
		validateRequiredFields();
		if(VantivUtils.extractRelatedField('ValuePlus__r.Vantiv_Legal_Entity_Id__c', record) == null ||
				('Approved'.equalsIgnoreCase((String)record.get('Vantiv_Bank_Account_Onboarding_Status__c')) && (String)record.get('Vantiv_Sub_Merchant_Id__c') == null))
				{
					throw new VantivRequestValidationException('Legal Entity id and/or SubMerchant id is unavailable.');
				}
	}
	
	private void validateRequiredFields()
	{
		
		for (String fsm : this.requiredFields.keyset()) {
			Boolean skipped = false;
			sObject x = this.requiredFields.get(fsm);
			if ((Boolean) x.get('Is_Required__c')) {
				String fp = (String) x.get('Field_Path__c');
				String ce = (String) x.get('Error_Message__c');
				Boolean sub = (Boolean) x.get('Part_of_a_Subquery__c');
				String value;
				if (sub != null && sub) {
					List<Bank_Account__c> subQueryResults = (List<Bank_Account__c>) this.record.getSObjects('Bank_Accounts__r');
					for (Bank_Account__c b : subQueryResults) {
						if (subQueryResults == null) {
							throw new VantivRequestValidationException('Failed to find a valid Bank Account Record associated / linked to this Value Plus Record.');
						}
						String[] parts = fp.split('\\.', 2);
						System.debug('SubQueryResults  = ' + subQueryResults);
						value = (string) subQueryResults[0].get(parts[1]);
					}
				} else if (x.get('Hardcoded_Value__c') != null ) {
					value = (String) x.get('Hardcoded_Value__c');
				} else {
					value = VantivUtils.extractRelatedField(fp, this.record);
				}
				if (skipped == false && (value == null || String.isBlank(value))) {
					this.hasError = true;
				    throw new VantivRequestValidationException('Failed to find a value for ' + ce + ' but that field is Required. Field: '+fp);
				}
			}
		}
	
	}
	
	public static void validate(sObject record, Map<String, sObject> reqFields, String action)
	{
		VantivRequestValidation validator = new VantivRequestValidation(record, reqFields, action);
	}

}