unpackaged/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000000}</displayFormat>
        <label>Bank Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bank_Account__c/fields/Account_Label__c.field-meta.xml
<CustomField>
    <fullName>Account_Label__c</fullName>
    <label>Account Label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>This is the bank account type.  0 = Checking, 1 = Savings.  Currently only Checking is supported.</description>
    <inlineHelpText>This is the bank account type.  0 = Checking, 1 = Savings.  Currently only Checking is supported.</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <default>true</default>
                <label>0</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/AccountNo__c.field-meta.xml
<CustomField>
    <fullName>AccountNo__c</fullName>
    <label>Account #</label>
    <length>17</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/RoutingNo__c.field-meta.xml
<CustomField>
    <fullName>RoutingNo__c</fullName>
    <label>Routing #</label>
    <length>9</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/ValuePlus__c.field-meta.xml
<CustomField>
    <fullName>ValuePlus__c</fullName>
    <label>Value+</label>
    <referenceTo>ValuePlus__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/PS_Audit_Log__c/PS_Audit_Log__c.object-meta.xml
<CustomObject>
    <label>ProfitStars Callout Audit Log</label>
    <nameField>
        <displayFormat>AuditLog-{000000}</displayFormat>
        <label>ProfitStars Callout Audit Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProfitStars Callout Audit Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PS_Audit_Log__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ProfitStars Callout Audit Logs</relationshipLabel>
    <relationshipName>ProfitStars_Callout_Audit_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PS_Audit_Log__c/fields/BankAccount__c.field-meta.xml
<CustomField>
    <fullName>BankAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>ProfitStars Callout Audit Logs</relationshipLabel>
    <relationshipName>ProfitStars_Callout_Audit_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PS_Audit_Log__c/fields/Call_Type__c.field-meta.xml
<CustomField>
    <fullName>Call_Type__c</fullName>
    <description>What type of call generated this audit log</description>
    <label>Call Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Velocity</fullName>
            </value>
            <value>
                <fullName>Guid</fullName>
            </value>
            <value>
                <fullName>Field Update</fullName>
            </value>
            <value>
                <fullName>Bank Account</fullName>
            </value>
            <value>
                <fullName>Location</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/PS_Audit_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>Api returned the following Error message</description>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/ValuePlus__c.object-meta.xml
<CustomObject>
    <label>Value+</label>
    <nameField>
        <displayFormat>VAS{000000}</displayFormat>
        <label>Value+</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ValuePlus</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ValuePlus__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Value+</relationshipLabel>
    <relationshipName>Value</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/MC_Principal_1_City__c.field-meta.xml
<CustomField>
    <fullName>MC_Principal_1_City__c</fullName>
    <description>MC,IM; R151946, R2027302; Edited: Sertifi Integ, users</description>
    <label>MC/IM - Principal 1 City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/MC_Principal_1_DOB__c.field-meta.xml
<CustomField>
    <fullName>MC_Principal_1_DOB__c</fullName>
    <description>MC,IM; R151946, R2027302; Edited: Sertifi Integ, users</description>
    <label>MC/IM - Principal 1 DOB</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/MC_Principal_1_First_Name__c.field-meta.xml
<CustomField>
    <fullName>MC_Principal_1_First_Name__c</fullName>
    <description>MC,IM; R151946, R2027302; Edited: Sertifi Integ, users</description>
    <label>MC/IM - Principal 1 First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/MC_Principal_1_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>MC_Principal_1_Last_Name__c</fullName>
    <description>MC,IM; R151946, R2027302; Edited: Sertifi Integ, users</description>
    <label>MC/IM - Principal 1 Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/MC_Principal_1_Ownership__c.field-meta.xml
<CustomField>
    <fullName>MC_Principal_1_Ownership__c</fullName>
    <description>MC,IM; R151946, R2027302; Edited: Sertifi Integ, users</description>
    <label>MC/IM - Principal 1 Ownership</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/MC_Principal_1_SSN__c.field-meta.xml
<CustomField>
    <fullName>MC_Principal_1_SSN__c</fullName>
    <description>MC,IM; R151946; Edited: Sertifi Integ, users</description>
    <label>MC/IM - Principal 1 SSN</label>
    <length>11</length>
    <maskChar>asterisk</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/MC_Principal_1_State__c.field-meta.xml
<CustomField>
    <fullName>MC_Principal_1_State__c</fullName>
    <description>MC,IM; R151946, R2027302; Edited: Sertifi Integ, users</description>
    <label>MC/IM - Principal 1 State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>OK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/MC_Principal_1_Street__c.field-meta.xml
<CustomField>
    <fullName>MC_Principal_1_Street__c</fullName>
    <description>MC,IM; R151946, R2027302; Edited: Sertifi Integ, users</description>
    <label>MC/IM - Principal 1 Street</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/MC_Principal_1_Zip__c.field-meta.xml
<CustomField>
    <fullName>MC_Principal_1_Zip__c</fullName>
    <description>MC,IM; R151946, R2027302; Edited: Sertifi Integ, users</description>
    <label>MC/IM - Principal 1 Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Period_Amount__c.field-meta.xml
<CustomField>
    <fullName>Period_Amount__c</fullName>
    <defaultValue>IF($RecordType.Name = &#39;MyCase Payments&#39;, 68000, NULL)</defaultValue>
    <description>Updated per R152784</description>
    <inlineHelpText>APM Only: Auto calculates to: &#39;Total Rent Roll x 2&#39; when Record Type = APM Payments &amp; Outbound On-Boarding Status=Pending Peer Review. Auto updates only one time upon meeting criteria &amp; can be manually updated before/after auto update.</inlineHelpText>
    <label>Period Amount</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Period_Count__c.field-meta.xml
<CustomField>
    <fullName>Period_Count__c</fullName>
    <defaultValue>IF($RecordType.Name = &#39;MyCase Payments&#39;, 40, NULL)</defaultValue>
    <description>Updated per R152784</description>
    <inlineHelpText>APM Only: Auto calculates to: &#39;# of Units x 2&#39; when Record Type = APM Payments &amp; Outbound On-Boarding Status=Pending Peer Review. Auto updates only one time upon meeting criteria &amp; can be manually updated before/after auto update.</inlineHelpText>
    <label>Period Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/ProfitStars_Merchant_ID__c.field-meta.xml
<CustomField>
    <fullName>ProfitStars_Merchant_ID__c</fullName>
    <label>ProfitStars Merchant ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Single_Day_Amount__c.field-meta.xml
<CustomField>
    <fullName>Single_Day_Amount__c</fullName>
    <defaultValue>IF($RecordType.Name = &#39;MyCase Payments&#39;, 34000, NULL)</defaultValue>
    <description>Updated per R152784</description>
    <inlineHelpText>APM Only: Auto calculates to: &#39;Total Rent Roll x 2&#39; when Record Type = APM Payments &amp; Outbound On-Boarding Status=Pending Peer Review. Auto updates only one time upon meeting criteria &amp; can be manually updated before/after auto update.</inlineHelpText>
    <label>Single Day Amount</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Single_Day_Count__c.field-meta.xml
<CustomField>
    <fullName>Single_Day_Count__c</fullName>
    <defaultValue>IF($RecordType.Name = &#39;MyCase Payments&#39;, 20, NULL)</defaultValue>
    <description>Updated per R152784</description>
    <inlineHelpText>APM Only: Auto calculates to: &#39;# of Units x 2&#39; when Record Type = APM Payments &amp; Outbound On-Boarding Status=Pending Peer Review. Auto updates only one time upon meeting criteria &amp; can be manually updated before/after auto update.</inlineHelpText>
    <label>Single Day Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Single_Trans_Amount__c.field-meta.xml
<CustomField>
    <fullName>Single_Trans_Amount__c</fullName>
    <defaultValue>IF($RecordType.Name = &#39;MyCase Payments&#39;, 10000, NULL)</defaultValue>
    <description>Updated per R152784</description>
    <inlineHelpText>APM Only: Auto calculates to: &#39;Highest Rent x 2&#39; when Record Type = APM Payments &amp; Outbound On-Boarding Status=Pending Peer Review. Auto updates only one time upon meeting criteria &amp; can be manually updated before/after auto update.</inlineHelpText>
    <label>Single Trans Amount</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Year_Established__c.field-meta.xml
<CustomField>
    <fullName>Year_Established__c</fullName>
    <formula>TEXT(MC_Year_Established__c) &amp; &quot;-01-01&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year Established</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/MyCaseBankAccountButtonsControllerTest.cls
/*
* Test class for the MyCaseBankAccountButtonsController class
*/
@isTest
public class MyCaseBankAccountButtonsControllerTest {
    
    static String validMaintCallJson = '{"CaseNumber": "00001720", "Success": "true"}';
    static String validLocByLocNameCallJson = '{"HTTPStatusCode":"200","GetLocationByLocationName":{"GetLocationByLocationNameResult":{"AccountNumberLast4":"7891","AccountType":"Checking","CustServProviderId":"654321","CustomerLocationNumber":"true","EntityId":"589885","LocationEnabled":true,"LocationId":"4140829","LocationName":"Test Bank Account0","MerchantName":"Test Account0-a1l4D00000074qDQAQ","RoutingNumber":"053000196"}}}';
    
    @TestSetup
	static void createData(){
		TestDataFactory.createCustomSettings();
		TestDataFactory.DataModel dm = new TestDataFactory.DataModel(1, false);

		for(Account a : dm.accountList){
			// a.RecordTypeId = InformationStrings.accountCustomerId;
			a.Website = 'https://www.appfolio.com';
			a.BillingStreet = '50 Castilian Dr';
			a.BillingCity = 'Goleta';
			a.BillingState = 'CA';	
			a.BillingPostalCode = '93117';
			a.BillingCountry = 'USA';
			a.Year_Established__c = '2000';
		}
		INSERT(dm.accountList);

		TestDataFactory.createEntitlements(dm.accountList[0].Id, true);

		for(ValuePlus__c v : dm.valuePlusList){
			v.Account__c = dm.accountList[0].Id;
            // v.RecordTypeId = InformationStrings.vPlusMycasePaymentsId;
            v.MC_Principal_1_First_Name__c = 'MyCase';
            v.MC_Principal_1_Last_Name__c = 'EnrollTest';
            v.MC_Principal_1_Ownership__c = 100;
            v.MC_Principal_1_SSN__c = '963852147';
			v.MC_Principal_1_DOB__c = Date.Today().addYears(-35);
			v.MC_Principal_1_Street__c = '50 Castilian Dr';
			v.MC_Principal_1_City__c = 'Goleta';
			v.MC_Principal_1_State__c = 'CA';
			v.MC_Principal_1_Zip__c = '93117';
            v.Period_Amount__c = 2000; 
            v.Period_Count__c = 5;
            v.Single_Day_Amount__c = 1000; 
            v.Single_Day_Count__c = 1;
            v.Single_Trans_Amount__c = 500;
		}
		INSERT(dm.valuePlusList);

		for(Bank_Account__c ba : dm.bankAccountList){
			ba.ValuePlus__c = dm.valuePlusList[0].Id;
            ba.RoutingNo__c = '053000196';
			ba.AccountNo__c = '1234567891';
			ba.Account_Type__c = '0';
		}
		INSERT(dm.bankAccountList);
    }
    
    static testmethod void pushBankToPSTest(){
		TestUtils.genTestSettings(true);
        TestUtils.genMyCaseInboundTestSettings(true);
		TestUtils.genLocationCustomSetting();

		ValuePlus__c vp = [Select Id, ProfitStars_Merchant_ID__c from ValuePlus__c where Account__r.Name = 'Test Account0' limit 1];
		vp.ProfitStars_Merchant_ID__c = '343434';
		update vp;

		Bank_Account__c bank = [Select Id from Bank_Account__c where Account_Label__c = 'Test Bank Account0'];
								 
		Test.startTest();
		Map<String, String> responseHeaders = new Map<String, String>();
		responseHeaders.put('Content-Type', 'application/json');
		Test.setMock(HttpCalloutMock.class, new HttpMockTestTemplate(
			new List<Integer>{200, 200}, 'OK', new List<String> {validMaintCallJson, 
			validLocByLocNameCallJson}, responseHeaders));

		String result = MyCaseBankAccountButtonsController.processBankRecord(bank.Id, 'pushBankToPS');
		Test.stopTest();

		List<PS_Audit_Log__c> auditLogList = [SELECT Id, Call_Type__c, Error_Message__c FROM PS_Audit_Log__c where BankAccount__c = :bank.Id];
		System.assertNotEquals(0, auditLogList.size());
		System.assert('Batch Location Update' == auditLogList[0].Call_Type__c);
		// System.assertEquals('Success', auditLogList[0].Error_Message__c);
	}
    
    static testmethod void addBankToVantivTest(){
		VantivTestUtils.genTestSettings(true);
		VantivTestUtils.genCreateSubMerchant();
		VantivTestUtils.genRootElement();
        
        ValuePlus__c vp = [Select Id from ValuePlus__c where Account__r.Name = 'Test Account0' limit 1];
        vp.Vantiv_Enrolled_Date__c = Date.today();
        vp.Vantiv_Onboarding_Status__c = 'Approved';
        vp.Vantiv_Legal_Entity_Id__c = '82916971912152256';
        vp.Vantiv_Legal_Entity_Update_Status__c = 'Ready To Update';
        update vp;
        
        Bank_Account__c bank = [Select Id from Bank_Account__c where Account_Label__c = 'Test Bank Account0'];
		
		Test.setMock(HttpCalloutMock.class, new VantivMockResponse(VantivTestUtils.subMerchantSuccessResponse, 200));
		
		Test.startTest();
		String result = MyCaseBankAccountButtonsController.processBankRecord(bank.Id, 'addBankToVantiv');
		Test.stopTest();
        
        Map<String, Object> res = (Map<String, Object>) JSON.deserializeUntyped(result);
		System.assertEquals(true, res.get('didPass'));
	}
    
    static testmethod void updateSubMerchantSuccess(){
		VantivTestUtils.genTestSettings(true);
		VantivTestUtils.genUpdateSubMerchant();
		VantivTestUtils.genRootElement();
        
        ValuePlus__c vp = [Select Id from ValuePlus__c where Account__r.Name = 'Test Account0' limit 1];
        vp.Vantiv_Enrolled_Date__c = Date.today();
        vp.Vantiv_Onboarding_Status__c = 'Approved';
        vp.Vantiv_Legal_Entity_Id__c = '82916971912152256';
        vp.Vantiv_Legal_Entity_Update_Status__c = 'Ready To Update';
        update vp;
        
        Bank_Account__c bank = [Select Id from Bank_Account__c where Account_Label__c = 'Test Bank Account0'];
        bank.Vantiv_Sub_Merchant_Id__c = '123456789';
		bank.Vantiv_Bank_Account_Update_Status__c = 'Ready To Update';
		bank.Vantiv_Bank_Account_Onboarding_Status__c = 'Approved';
        update bank;
		
		Test.setMock(HttpCalloutMock.class, new VantivMockResponse(VantivTestUtils.subMerchantSuccessResponse, 200));
		
		Test.startTest();
		String result = MyCaseBankAccountButtonsController.processBankRecord(bank.Id, 'updateBankInVantiv');
		Test.stopTest();
        
        Map<String, Object> res = (Map<String, Object>) JSON.deserializeUntyped(result);
		System.assertEquals(true, res.get('didPass'));
	}
    
    static testmethod void testException(){
        Bank_Account__c bank = [Select Id from Bank_Account__c where Account_Label__c = 'Test Bank Account0'];
        
        Test.startTest();
		String result = MyCaseBankAccountButtonsController.processBankRecord(bank.Id, 'testException');
		Test.stopTest();
        
        System.assert(result.contains('error thrown:'));
    }
}