unpackaged/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000000}</displayFormat>
        <label>Bank Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bank_Account__c/fields/ValuePlus__c.field-meta.xml
<CustomField>
    <fullName>ValuePlus__c</fullName>
    <label>Value+</label>
    <referenceTo>ValuePlus__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Vantiv_Bank_Account_Onboarding_Status__c.field-meta.xml
<CustomField>
    <fullName>Vantiv_Bank_Account_Onboarding_Status__c</fullName>
    <label>Vantiv Bank Account Onboarding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready To Transmit</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Manual Review</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Vantiv_Bank_Account_Update_Status__c.field-meta.xml
<CustomField>
    <fullName>Vantiv_Bank_Account_Update_Status__c</fullName>
    <label>Vantiv Bank Account Update Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready To Update</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Vantiv_Merchant_Ident_String__c.field-meta.xml
<CustomField>
    <fullName>Vantiv_Merchant_Ident_String__c</fullName>
    <label>Vantiv Merchant Ident String</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Vantiv_PayPage_Id__c.field-meta.xml
<CustomField>
    <fullName>Vantiv_PayPage_Id__c</fullName>
    <label>Vantiv PayPage Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Vantiv_Sub_Merchant_Id__c.field-meta.xml
<CustomField>
    <fullName>Vantiv_Sub_Merchant_Id__c</fullName>
    <label>Vantiv Sub Merchant Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/ValuePlus__c.object-meta.xml
<CustomObject>
    <label>Value+</label>
    <nameField>
        <displayFormat>VAS{000000}</displayFormat>
        <label>Value+</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ValuePlus</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ValuePlus__c/fields/Vantiv_Enrolled_Date__c.field-meta.xml
<CustomField>
    <fullName>Vantiv_Enrolled_Date__c</fullName>
    <label>Vantiv Enrolled Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Vantiv_Legal_Entity_Id__c.field-meta.xml
<CustomField>
    <fullName>Vantiv_Legal_Entity_Id__c</fullName>
    <label>Vantiv Legal Entity Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Vantiv_Legal_Entity_Update_Status__c.field-meta.xml
<CustomField>
    <fullName>Vantiv_Legal_Entity_Update_Status__c</fullName>
    <label>Vantiv Legal Entity Update Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready To Update</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Change Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Vantiv_Onboarding_Status__c.field-meta.xml
<CustomField>
    <fullName>Vantiv_Onboarding_Status__c</fullName>
    <label>Vantiv Onboarding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready To Transmit</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Manual Review</fullName>
            </value>
            <value>
                <fullName>Manual Review - Duplicate</fullName>
            </value>
            <value>
                <fullName>Manual Review - Background Check Error</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Collecting Documents</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Vantiv_Audit_Logs__c/Vantiv_Audit_Logs__c.object-meta.xml
<CustomObject>
    <label>Vantiv Callout Audit Log</label>
    <nameField>
        <displayFormat>VAL-{000000}</displayFormat>
        <label>Vantiv Callout Audit Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vantiv Callout Audit Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vantiv_Audit_Logs__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Vantiv Callout Audit Logs</relationshipLabel>
    <relationshipName>Vantiv_Callout_Audit_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Vantiv_Audit_Logs__c/fields/ValuePlus__c.field-meta.xml
<CustomField>
    <fullName>ValuePlus__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ValuePlus</label>
    <referenceTo>ValuePlus__c</referenceTo>
    <relationshipLabel>Vantiv Callout Audit Logs</relationshipLabel>
    <relationshipName>Vantiv_Callout_Audit_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/VantivButtons.cls
global class VantivButtons 
{
    global class VantivButtonResult
    {
        public String result{get; set;}
        public Boolean didPass{get; set;}
    }
    
    webservice static String callLegalEntity(Id id)
    {
        VantivButtons.VantivButtonResult result = new VantivButtons.VantivButtonResult();
        VantivLegalEntityReq req;
        Vantiv_Audit_Logs__c log = new Vantiv_Audit_Logs__c();
        ValuePlus__c vp = new ValuePlus__c(Id=id); 
        try
        {
            req = new VantivLegalEntityReq(id);
            if(req.response.isSuccess)
            {
                result.didPass = true;
                vp.Vantiv_Legal_Entity_Id__c = req.response.legalEntityId;
                vp.Vantiv_Onboarding_Status__c = req.response.responseDescription;
                vp.Vantiv_Enrolled_Date__c = System.Now();
                if(req.response.isDuplicate)
                {
                    result.result ='Merchat was already enrolled with vantiv. Existing legal entity id '+ req.response.legalEntityId;
                }
                else
                {
                    result.result = 'Request submitted successfully. Onboarding Status: '+req.response.responseDescription;
                }
            }
            else
            {
                result.didPass = false;
                result.result = 'Create legal entity request failed with following errors ';
                for(String error : req.response.errors)
                {
                    result.result = result.result+'\n'+error;
                }
            }
            log=VantivUtils.createAuditLog(id,req.response.responseDescription, result.result, req.response.toString(), 'Create Legal Entity', getVPRecordTypeName(id), true);
            
        }
        catch(Exception e)
        {
            vp.Vantiv_Onboarding_Status__c = 'Failed';
            result.didPass = false;
            result.result = e.getMessage();
            log=VantivUtils.createAuditLog(id,'Failed', result.result, '', 'Create Legal Entity', getVPRecordTypeName(id), true);
        }
        update vp;
        insert log;
        
        return JSON.serialize(result);
    } 
    
    webservice static String callSubMerchantCreateReq(Id id)
    {
        VantivButtons.VantivButtonResult result = new VantivButtons.VantivButtonResult();
        VantivSubMerchantCreateReq req;
        Vantiv_Audit_Logs__c log = new Vantiv_Audit_Logs__c();
        Bank_Account__c ba = new Bank_Account__c(Id=id); 
        try
        {
            req = new VantivSubMerchantCreateReq(id);
            if(req.response.isSuccess)
            {
                result.didPass = true;
                /*vp.Vantiv_Legal_Entity_Id__c = req.response.legalEntityId;
                vp.Vantiv_Onboarding_Status__c = req.response.responseDescription;
                vp.Vantiv_Enrolled_Date__c = System.Now();*/
                ba.Vantiv_Sub_Merchant_Id__c = req.response.subMerchantId;
                ba.Vantiv_Merchant_Ident_String__c = req.response.merchantIdentString;
                ba.Vantiv_PayPage_Id__c = req.response.payPageId;
                if(req.response.isDuplicate)
                {
                    result.result ='Sub-Merchat was already enrolled with vantiv. Existing Sub-Merchant id '+ req.response.subMerchantId;
                    ba.Vantiv_Bank_Account_Onboarding_Status__c = 'Duplicate';
                }
                else
                {
                    result.result = 'Sub-Merchant successfully onboarded. Sub-Merchant Id '+req.response.subMerchantId;
                    ba.Vantiv_Bank_Account_Onboarding_Status__c = 'Approved';
                }
            }
            else
            {
                result.didPass = false;
                result.result = 'Create Sub-Merchant request failed with following errors ';
                ba.Vantiv_Bank_Account_Onboarding_Status__c = 'Failed';
                for(String error : req.response.errors)
                {
                    result.result = result.result+'\n'+error;
                }
            }
            log=VantivUtils.createAuditLog(id,ba.Vantiv_Bank_Account_Onboarding_Status__c, result.result, req.response.toString(), 'Create Sub-Merchant', getVPRecordTypebyBankAccount(id), false);
            
        }
        catch(Exception e)
        {
            //vp.Vantiv_Onboarding_Status__c = 'Failed';
            ba.Vantiv_Bank_Account_Onboarding_Status__c = 'Failed';
            result.didPass = false;
            result.result = e.getMessage();
            log=VantivUtils.createAuditLog(id,'Failed', result.result+e.getStackTraceString(), '', 'Create Sub-Merchant', getVPRecordTypebyBankAccount(id), false);
        }
        update ba;
        insert log;
        
        return JSON.serialize(result);
    } 
    
    webservice static String callLegalEntityUpdateReq(Id id)
    {
        VantivButtons.VantivButtonResult result = new VantivButtons.VantivButtonResult();
        VantivLegalEntityUpdateReq req;
        Vantiv_Audit_Logs__c log = new Vantiv_Audit_Logs__c();
        ValuePlus__c vp = new ValuePlus__c(Id=id); 
        try
        {
            req = new VantivLegalEntityUpdateReq(id);
            if(req.response.isSuccess)
            {
                result.didPass = true;
                vp.Vantiv_Legal_Entity_Update_Status__c = req.response.responseDescription;
                if(req.response.responseDescription != null)
                {
                    result.result = 'Merchant successfully updated. Legal entity Id '+req.response.legalEntityId;
                }
                else
                {
                    vp.Vantiv_Legal_Entity_Update_Status__c = 'Change Unknown';
                    result.result = 'No update was identified. Transaction Id '+req.response.transactionId;
                }
                
            }
            else
            {
                result.didPass = false;
                vp.Vantiv_Legal_Entity_Update_Status__c = 'Failed';
                result.result = 'Update legal entity request failed with following errors ';
                for(String error : req.response.errors)
                {
                    result.result = result.result+'\n'+error;
                }
            }
            log=VantivUtils.createAuditLog(id,vp.Vantiv_Legal_Entity_Update_Status__c, result.result, req.response.toString(), 'Update Legal Entity', getVPRecordTypeName(id), true);
            
        }
        catch(Exception e)
        {
            vp.Vantiv_Legal_Entity_Update_Status__c = 'Failed';
            result.didPass = false;
            result.result = e.getMessage();
            log=VantivUtils.createAuditLog(id,'Failed', result.result, '', 'Update Legal Entity', getVPRecordTypeName(id), true);
        }
        update vp;
        insert log;
        
        return JSON.serialize(result);
    } 
    
    webservice static String callSubMerchantUpdateReq(Id id)
    {
        VantivButtons.VantivButtonResult result = new VantivButtons.VantivButtonResult();
        VantivSubMerchantUpdateReq req;
        Vantiv_Audit_Logs__c log = new Vantiv_Audit_Logs__c();
        Bank_Account__c ba = new Bank_Account__c(Id=id); 
        try
        {
            req = new VantivSubMerchantUpdateReq(id);
            if(req.response.isSuccess)
            {
                result.didPass = true;
                ba.Vantiv_Bank_Account_Update_Status__c = 'Approved';
                result.result = 'Sub-Merchant successfully Updated. Transaction Id '+req.response.transactionId;
            }
            else
            {
                result.didPass = false;
                result.result = 'Update Sub-Merchant request failed with following errors ';
                ba.Vantiv_Bank_Account_Update_Status__c = 'Failed';
                for(String error : req.response.errors)
                {
                    result.result = result.result+'\n'+error;
                }
            }
            log=VantivUtils.createAuditLog(id,ba.Vantiv_Bank_Account_Update_Status__c, result.result, req.response.toString(), 'Update Sub-Merchant', getVPRecordTypebyBankAccount(id), false);
            
        }
        catch(Exception e)
        {
            //vp.Vantiv_Onboarding_Status__c = 'Failed';
            ba.Vantiv_Bank_Account_Update_Status__c = 'Failed';
            result.didPass = false;
            result.result = e.getMessage();
            log=VantivUtils.createAuditLog(id,'Failed', result.result+e.getStackTraceString(), '', 'Update Sub-Merchant', getVPRecordTypebyBankAccount(id), false);
        }
        update ba;
        insert log;
        
        return JSON.serialize(result);
    } 
    
    private static String getVPRecordTypeName(Id id)
    {
        ValuePlus__c vp = new ValuePlus__c();
        if(id != null)
        {
            vp = [select Id, recordType.Id, recordType.Name from ValuePlus__c where Id =: id];
            return vp.recordType.Name;
        }
        return null;
    }
    
    private static String getVPRecordTypebyBankAccount(Id id)
    {
        Bank_Account__c ba = new Bank_Account__c();
        if(id != null)
        {
            ba = [select Id, ValuePlus__r.recordTypeId, ValuePlus__r.recordType.Name from Bank_Account__c where Id =: id];
            return ba.ValuePlus__r.recordType.Name;
        }
        return null;
    }
}