unpackaged/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000000}</displayFormat>
        <label>Bank Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bank_Account__c/fields/GiactStatus__c.field-meta.xml
<CustomField>
    <fullName>GiactStatus__c</fullName>
    <label>Giact Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready to Transmit to GIACT</fullName>
            </value>
            <value>
                <fullName>Successfully Validated</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
            <value>
                <fullName>Manually Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/ValuePlus__c.field-meta.xml
<CustomField>
    <fullName>ValuePlus__c</fullName>
    <label>Value+</label>
    <referenceTo>ValuePlus__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/ValuePlus__c.object-meta.xml
<CustomObject>
    <label>Value+</label>
    <nameField>
        <displayFormat>VAS{000000}</displayFormat>
        <label>Value+</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ValuePlus</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ValuePlus__c/fields/GiactStatus__c.field-meta.xml
<CustomField>
    <fullName>GiactStatus__c</fullName>
    <label>Giact Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automated Approval</fullName>
            </value>
            <value>
                <fullName>Manually Approved</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
            <value>
                <fullName>Need Review</fullName>
                <isActive>false</isActive>
                <label>Need Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/GiactVerifyService.cls
/**********************************************************************************************************************
* copyright © 2017
* File		: GiactVerifyService.cls
* Purpose	: This class validates a set of custom Setting records. Based on the custom setting records this class
* determines, if the all the required fields are available on the SObject record. For eg. if The custom setting is
* gVerify and The SObject is Bank Account. Then it validates if all the Required fields on the Custom Setting is
* avaialble in the BankAccount Record. 
*
* @author Rohit Kumar Malik
* @version 1.0
* @since 2017-10-20
**********************************************************************************************************************/

global without sharing class GiactVerifyService {
	Static Set <Id> processedBankAccountRecords = new Set <Id> ();

	@future (callout = true)
	public static void verifyService (Id valuePlusId, Id baId) {
		// First Check if the String is empty or not. 
		if (valuePlusId==null) {
			return;
		}

		System.debug('*** Preparing to process GIdentify.');
		// Intatntiate the Class. 
		GIACTIntegrationService gis = new GIACTIntegrationService ();
		gis.pull_GiactVerifyData ('gverifyinquiry', valuePlusId, baId);
	}

	public static Boolean IsVerifyProcessingRequired (Bank_Account__c ba) {

		if (!processedBankAccountRecords.contains(ba.Id) &&
			(ba.GiactStatus__c=='Ready to Transmit to GIACT')) {
			return true;
		}

		return false;
	}

	public static void processBankAccountRecordsForGiact (List<Bank_Account__c> newList) {

		for (Bank_Account__c ba : newList) {
			System.debug ('*** Checking if the record needs to be processed with Giact');
			if (IsVerifyProcessingRequired (ba))  {
				System.debug ('*** Processing Giact - Returning True');
				// Add to the set to that it is not processed again. 
				processedBankAccountRecords.add (ba.Id);
                GiactVerifyService.verifyService(ba.ValuePlus__c, ba.id); 
			}
		}
	}
}