unpackaged/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000000}</displayFormat>
        <label>Bank Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bank_Account__c/fields/AccountNo__c.field-meta.xml
<CustomField>
    <fullName>AccountNo__c</fullName>
    <label>Account #</label>
    <length>17</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/RoutingNo__c.field-meta.xml
<CustomField>
    <fullName>RoutingNo__c</fullName>
    <label>Routing #</label>
    <length>9</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/ValuePlus__c.field-meta.xml
<CustomField>
    <fullName>ValuePlus__c</fullName>
    <label>Value+</label>
    <referenceTo>ValuePlus__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Vantiv_Bank_Account_Onboarding_Status__c.field-meta.xml
<CustomField>
    <fullName>Vantiv_Bank_Account_Onboarding_Status__c</fullName>
    <label>Vantiv Bank Account Onboarding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready To Transmit</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Manual Review</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/ValuePlus__c.object-meta.xml
<CustomObject>
    <label>Value+</label>
    <nameField>
        <displayFormat>VAS{000000}</displayFormat>
        <label>Value+</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ValuePlus</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ValuePlus__c/fields/CreditCard_Single_Trans_Amount__c.field-meta.xml
<CustomField>
    <fullName>CreditCard_Single_Trans_Amount__c</fullName>
    <defaultValue>IF($RecordType.Name = &#39;MyCase Payments&#39;, 50000, NULL)</defaultValue>
    <label>CreditCard Single Trans Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Vantiv_Onboarding_Status__c.field-meta.xml
<CustomField>
    <fullName>Vantiv_Onboarding_Status__c</fullName>
    <label>Vantiv Onboarding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready To Transmit</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Manual Review</fullName>
            </value>
            <value>
                <fullName>Manual Review - Duplicate</fullName>
            </value>
            <value>
                <fullName>Manual Review - Background Check Error</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Collecting Documents</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/VantivRequestValidationTest.cls
@isTest
private class VantivRequestValidationTest {
/* SOLUNUS MODIFICATION TO PROD: 
    static testMethod void legalEntityValidationSuccess() 
    {
    	Boolean isFailure = false;
		Account a = VantivTestUtils.genAccount(true, 'MyCase Account');
		ValuePlus__c vp = VantivTestUtils.genValuePlus(true, a.Id, null, 'MyCase Payments');
		Bank_Account__c ba = VantivTestUtils.genBankAccount(true, vp.Id);
		
		VantivTestUtils.genCreateLegalEntity();
		VantivTestUtils.genTestSettings(true);
		VantivTestUtils.genRootElement();
		VantivTestUtils.genVantivEntityType();
		
		List<sObject> cSetting = new List<sObject>();
		cSetting.add(VantivTestUtils.addFieldToCustomSetting('LegalEntityCreateRequest', 'subQuery2', 'subQuery2', 'Bank_Account__c.AccountNo__c', '', false, true, 99998));
		cSetting.add(VantivTestUtils.addFieldToCustomSetting('LegalEntityCreateRequest', 'subQuery3', 'subQuery3', 'Bank_Account__c.routingNo__c', '111000025', true, true, 99997));
		insert cSetting;
		
		Map<String, sObject> requestFields = VantivUtils.getRequestFields('LegalEntityCreateRequest');
		
		Test.startTest();
		ValuePlus__c record = VantivRequestBuilder.getRecord(requestFields, 'LegalEntityCreateRequest', vp.Id);
		try
		{
			VantivRequestValidation.validate(record,requestFields, 'LegalEntityCreateRequest' );
		}
		catch(Exception e)
		{
			isFailure = true;
		}
		System.assert(!isFailure);
		Test.stopTest();
    }
    */
    static testMethod void legalEntityValidationException1() 
    {
    	Boolean isFailure = false;
		Account a = VantivTestUtils.genAccount(true, 'MyCase Account');
		ValuePlus__c vp = VantivTestUtils.genValuePlus(true, a.Id, null, 'MyCase Payments');
		
		VantivTestUtils.genCreateLegalEntity();
		VantivTestUtils.genTestSettings(true);
		VantivTestUtils.genRootElement();
		VantivTestUtils.genVantivEntityType();
		
		Map<String, sObject> requestFields = VantivUtils.getRequestFields('LegalEntityCreateRequest');
		
		Test.startTest();
		ValuePlus__c record = VantivRequestBuilder.getRecord(requestFields, 'LegalEntityCreateRequest', vp.Id);
		try
		{
			VantivRequestValidation validator = new VantivRequestValidation(record,requestFields, 'TestAction' );
		}
		catch(Exception e)
		{
			if(e.getMessage().containsIgnoreCase('TestAction'))
			{
				isFailure = true;
			}
		}
		System.assert(isFailure);
		Test.stopTest();
    }
    /* SOLUNUS MODIFICATION TO PROD: 
    static testMethod void legalEntityValidationException2() 
    {
    	Boolean isFailure = false;
		Account a = VantivTestUtils.genAccount(true, 'MyCase Account');
		ValuePlus__c vp = VantivTestUtils.genValuePlus(true, a.Id, null, 'MyCase Payments');
		vp.Vantiv_Onboarding_Status__c = 'Approved';
		update vp;
		
		VantivTestUtils.genCreateLegalEntity();
		VantivTestUtils.genTestSettings(true);
		VantivTestUtils.genRootElement();
		VantivTestUtils.genVantivEntityType();
		
		Map<String, sObject> requestFields = VantivUtils.getRequestFields('LegalEntityCreateRequest');
		
		Test.startTest();
		ValuePlus__c record = VantivRequestBuilder.getRecord(requestFields, 'LegalEntityCreateRequest', vp.Id);
		try
		{
			VantivRequestValidation validator = new VantivRequestValidation(record,requestFields, 'LegalEntityCreateRequest' );
		}
		catch(Exception e)
		{
			if(e.getMessage().containsIgnoreCase('Legal entity id unavailable'))
			{
				isFailure = true;
			}
		}
		System.assert(isFailure);
		Test.stopTest();
    }
	*/
    
    static testMethod void subMerchantValidationSuccess()
    {
    	Boolean isFailure = false;
    	Account a = VantivTestUtils.genAccount(true, 'MyCase Account');
		ValuePlus__c vp = VantivTestUtils.genValuePlusWithLegalId(true, a.Id, null, 'MyCase Payments');
		Bank_Account__c ba = VantivTestUtils.genBankAccount(true, vp.Id);
		
		VantivTestUtils.genCreateSubMerchant();
		VantivTestUtils.genTestSettings(true);
		
		Map<String, sObject> requestFields = VantivUtils.getRequestFields('SubMerchantCreateRequest');
		
		Test.startTest();
		Bank_Account__c record = VantivRequestBuilder.getBankRecord(requestFields, 'SubMerchantCreateRequest', ba.Id);
		try
		{
			VantivRequestValidation validator = new VantivRequestValidation(record,requestFields, 'SubMerchantCreateRequest' );
		}
		catch(Exception e)
		{
			isFailure = true;
		}
		System.assert(!isFailure);
		Test.stopTest();
    }
    
    static testMethod void subMerchantValidationException1()
    {
    	Boolean isFailure = false;
    	Account a = VantivTestUtils.genAccount(true, 'MyCase Account');
		ValuePlus__c vp = VantivTestUtils.genValuePlusWithLegalId(true, a.Id, null, 'MyCase Payments');
		Bank_Account__c ba = VantivTestUtils.genBankAccount(true, vp.Id);
		ba.Vantiv_Bank_Account_Onboarding_Status__c = 'Approved';
		update ba;
		
		VantivTestUtils.genCreateSubMerchant();
		VantivTestUtils.genTestSettings(true);
		
		Map<String, sObject> requestFields = VantivUtils.getRequestFields('SubMerchantCreateRequest');
		
		Test.startTest();
		Bank_Account__c record = VantivRequestBuilder.getBankRecord(requestFields, 'SubMerchantCreateRequest', ba.Id);
		try
		{
			VantivRequestValidation validator = new VantivRequestValidation(record,requestFields, 'SubMerchantCreateRequest' );
		}
		catch(Exception e)
		{
			if(e.getMessage().containsIgnoreCase('Legal Entity id and/or SubMerchant id is unavailable'))
			{
				isFailure = true;
			}
		}
		System.assert(isFailure);
		Test.stopTest();
    }
    
    static testMethod void subMerchantValidationException2()
    {
    	Boolean isFailure = false;
    	Account a = VantivTestUtils.genAccount(true, 'MyCase Account');
		ValuePlus__c vp = VantivTestUtils.genValuePlusWithLegalId(true, a.Id, null, 'MyCase Payments');
		Bank_Account__c ba = VantivTestUtils.genBankAccount(true, vp.Id);
		vp.CreditCard_Single_Trans_Amount__c = null;
		update vp;
		
		VantivTestUtils.genCreateSubMerchant();
		VantivTestUtils.genTestSettings(true);
		
		Map<String, sObject> requestFields = VantivUtils.getRequestFields('SubMerchantCreateRequest');
		
		Test.startTest();
		Bank_Account__c record = VantivRequestBuilder.getBankRecord(requestFields, 'SubMerchantCreateRequest', ba.Id);
		try
		{
			VantivRequestValidation validator = new VantivRequestValidation(record,requestFields, 'SubMerchantCreateRequest');
		}
		catch(Exception e)
		{
			if(e.getMessage().containsIgnoreCase('Failed to find a value for'))
			{
				isFailure = true;
			}
		}
		System.assert(isFailure);
		Test.stopTest();
    }
}