unpackaged/main/default/objects/Contact/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>Stage of qualification for the contact in the sales process</description>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Stage</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User_List_Default__c/User_List_Default__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds the default user ids for applications</description>
    <label>User List - Default</label>
</CustomObject>

unpackaged/main/default/objects/User_List_Default__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <description>The user id or ids, used as the default user in application</description>
    <inlineHelpText>Enter user id, or comma separated user ids, that will be used as default for apex processes</inlineHelpText>
    <label>User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/ValuePlus__c.object-meta.xml
<CustomObject>
    <label>Value+</label>
    <nameField>
        <displayFormat>VAS{000000}</displayFormat>
        <label>Value+</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ValuePlus</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ValuePlus__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Value+</relationshipLabel>
    <relationshipName>Value</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sold/Not Started</fullName>
            </value>
            <value>
                <fullName>KOC Confirmed</fullName>
                <label>Questionnaire Received</label>
            </value>
            <value>
                <fullName>Sold/Not Ready</fullName>
            </value>
            <value>
                <fullName>On-Boarding</fullName>
            </value>
            <value>
                <fullName>KOC Scheduled</fullName>
            </value>
            <value>
                <fullName>KOC Complete</fullName>
            </value>
            <value>
                <fullName>Build In Progress</fullName>
            </value>
            <value>
                <fullName>Site Presentation</fullName>
            </value>
            <value>
                <fullName>Site Delivered/Final Changes</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Additional Communication (O)</fullName>
            </value>
            <value>
                <fullName>Agreement Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Content Acquisition</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Deferred-Built</fullName>
            </value>
            <value>
                <fullName>Deferred-Canceled</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Final Changes</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Left APM</fullName>
            </value>
            <value>
                <fullName>Left IM</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Live-Free Trial</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Lost During Pilot</fullName>
            </value>
            <value>
                <fullName>Lost In Onboarding</fullName>
            </value>
            <value>
                <fullName>Multi Site Deffered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/TIN_Match__c.field-meta.xml
<CustomField>
    <fullName>TIN_Match__c</fullName>
    <label>TIN Match</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Ready to Transmit</fullName>
            </value>
            <value>
                <fullName>Automated Approval</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
            <value>
                <fullName>Manual Approval</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Lead_Stage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Known</fullName>
    </customValue>
    <customValue>
        <fullName>New</fullName>
    </customValue>
    <customValue>
        <fullName>Working</fullName>
    </customValue>
    <customValue>
        <fullName>Engaged</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Nurture</fullName>
    </customValue>
    <customValue>
        <fullName>Disqualified</fullName>
    </customValue>
    <customValue>
        <fullName>Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Assigned</fullName>
        <isActive>false</isActive>
        <label>Assigned</label>
    </customValue>
    <customValue>
        <fullName>Sales Nurture</fullName>
        <isActive>false</isActive>
        <label>Sales Nurture</label>
    </customValue>
    <masterLabel>Lead Stage</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ValuePlusTriggerMethodHandlerTest.cls
@isTest
public class ValuePlusTriggerMethodHandlerTest {
    
    @testSetup
    static void testSetup(){
        TestDataFactory.createCustomSettings();
        List<Account> accounts = createAccount(62, true);

    }

    public static List<Opportunity> createOpportunity(List<Account> accounts, Boolean doInsert){
        List<Opportunity> opps = new List<Opportunity>();

        for(Account account : accounts){
            opps.add(new Opportunity(Name = 'opp ' + account.Name, AccountId = account.Id, StageName = 'Demo', CloseDate = Date.today().addDays(50)));
        }

        if(doInsert){
             //just create the opps, don't need to run account trigger
            TriggerHandler.runBeforeInsert = false;
            TriggerHandler.runAfterInsert = false;
            insert opps;
        }

        return opps;
    }

    public static void createOnBoardingSpecialist(){
        User_List_Default__c onBoardingSpecialist = new User_List_Default__c(name = 'ValuePlusPaymentScreeningAssignment', user_id__c = UserInfo.getUserId());
        insert onBoardingSpecialist;
    }
    public static List<Contact> createContacts(Integer num, Boolean doInsert){
        List<Contact> contacts = new List<Contact>();
        for(Integer i = 0; i < num; i++){
            contacts.add(new Contact(LastName = 'lname' + i));
        }
        if(doInsert){
            insert contacts;
        }
        return contacts;
    }

    public static List<Account> createAccount(Integer num, Boolean doInsert){
        List<Account> accounts = TestDataFactory.createAccountList(num, false);
        for(Integer i = 0; i < num; i++){
            accounts[i].name = 'VP Test # ' + i;
        }

        if(doInsert){
                    //just create the accounts, don't need to run account trigger
            insert accounts;
        }
        return accounts;
    }



    public static List<ValuePlus__c> createValuePlus(Integer num, Boolean doInsert ){
        List<Account> accounts = [SELECT id FROM Account];

        List<ValuePlus__c> vpList = new List<ValuePlus__c>();
        for(Integer i = 0; i < num; i++){
                 vpList.add(new ValuePlus__c(Account__c = accounts[i].Id, Stage__c='Ready to Transmit to Giact'));
        }

        if(doInsert){
            insert vpList;

        }

        return vpList;
    }



    static testMethod void testBeforeInsert(){
        List<ValuePlus__c> vpList = createValuePlus(55, false);

        test.startTest();
        insert vpList;
        test.stopTest();

    }


    static testMethod void testBeforeUpdate(){
        List<ValuePlus__c> vpList = createValuePlus(62, false);

        //minor stage setup for some cases
        for(Integer i = 0;  i < 10; i++){
            vpList[i].Stage__c = i < 5 ? 'Deferred' : 'Lost';
        }

        insert vpList;

        for(Integer i = 0; i < 5; i++){
            vpList[i].Stage__c = 'Sold/Not Started';
            vpList[i].TIN_Match__c ='Ready To Transmit';

        }

        test.startTest();
        update vpList;
        test.stopTest();
       
    }
    
   
  
    private static List<ValuePlus__c> createData(String type){    
        TestDataFactory.DataModel dm = new TestDataFactory.DataModel(1, false);
        
        INSERT(dm.accountList);

        for(Asset ast : dm.assetList){
            ast.AccountId = dm.accountList[0].Id;
        }
        INSERT(dm.assetList);

        INSERT(dm.valueplusList);

        return dm.valueplusList;
    }

    private static testMethod void testException1(){
        Test.startTest();
        ValuePlusTriggerMethodHandler handler = new ValuePlusTriggerMethodHandler();
     
        Test.stopTest();
    }

  
}