unpackaged/main/default/objects/GiactInquiryResponse__c/GiactInquiryResponse__c.object-meta.xml
<CustomObject>
    <label>GIACT Inquiry Response</label>
    <nameField>
        <displayFormat>GIR-{0000}</displayFormat>
        <label>GIACT Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GIACT Inquiry Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GiactInquiryResponse__c/fields/RequestText__c.field-meta.xml
<CustomField>
    <fullName>RequestText__c</fullName>
    <label>Request Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/GiactInquiryResponse__c/fields/ResponseText__c.field-meta.xml
<CustomField>
    <fullName>ResponseText__c</fullName>
    <label>Response Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/classes/PostRefreshGIACTLogBatch.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* This is the batch job for removing sensitive data on GiactInquiryResponse__c after snadbox refresh
* 
* @test           PostRefreshGIACTLogBatchTest
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         
* @version        1.0
* @created        
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* v1.0            ryan.kleinberg@appfolio.com
* 2020-01-02      Creation - R1918759 
*
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/
public class PostRefreshGIACTLogBatch implements Database.Batchable<sObject> {
    
    String query;
    
    public Database.QueryLocator start(Database.BatchableContext context) {
        query = 'SELECT Id, RequestText__c, ResponseText__c FROM GiactInquiryResponse__c';
        
        //If this is running in production, STOP. This should not run in production
        if(UserInfo.getOrganizationId() == '00D80000000cytGEAQ'){
            query += ' Limit 0';
        }
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext context, List<sObject> scope) {
        List<GiactInquiryResponse__c> logList = scope;
        List<GiactInquiryResponse__c> updateLogList = new List<GiactInquiryResponse__c>();
        
        for(GiactInquiryResponse__c log : logList){
            
            //mask sensitive info in the request and response fields
            log.RequestText__c = '';
            log.ResponseText__c = '';
			            
            updateLogList.add(log);
            
            
        }
        if (!updateLogList.isEmpty()){
            //Update the logs
            UPDATE(updateLogList);
        }
    }
    
    public void finish(Database.BatchableContext context) {
        if(!Test.isRunningTest()){
            Database.executeBatch(new PostRefreshPNMLogBatch());
        }
    }
   
    
    
}