unpackaged/main/default/objects/Automation_Log__c/Automation_Log__c.object-meta.xml
<CustomObject>
    <description>generic log used for all of our Integration responses</description>
    <label>Automation Log</label>
    <nameField>
        <displayFormat>AL-{000000000}</displayFormat>
        <label>Automation Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Automation Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Automation_Log__c/fields/RawRequest__c.field-meta.xml
<CustomField>
    <fullName>RawRequest__c</fullName>
    <label>Raw Request</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Automation_Log__c/fields/RawResponse__c.field-meta.xml
<CustomField>
    <fullName>RawResponse__c</fullName>
    <label>Raw Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/classes/PostRefreshPNMLogBatch.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* This is the batch job for removing sensitive data on PNM audit logs after snadbox refresh
* 
* @test           PostRefreshPNMLogBatchTest
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         
* @version        1.0
* @created        
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* v1.0            ryan.kleinberg@appfolio.com
* 2020-01-02      Creation - R1918759 
*
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/
public class PostRefreshPNMLogBatch implements Database.Batchable<sObject> {
    
    String query;
    
    public Database.QueryLocator start(Database.BatchableContext context) {
        query = 'SELECT Id, RawRequest__c, RawResponse__c  FROM Automation_Log__c';
        
        //If this is running in production, STOP. This should not run in production
        if(UserInfo.getOrganizationId() == '00D80000000cytGEAQ'){
            query += ' Limit 0';
        }
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext context, List<sObject> scope) {
        List<Automation_Log__c> logList = scope;
        List<Automation_Log__c> updateLogList = new List<Automation_Log__c>();
        
        for(Automation_Log__c log : logList){
            
            //mask sensitive info in the request and response
            log.RawRequest__c = '';
            log.RawResponse__c = '';
			            
            updateLogList.add(log);
            
            
        }
        if (!updateLogList.isEmpty()){
            //Update the logs
            UPDATE(updateLogList);
        }
    }
    
    public void finish(Database.BatchableContext context) {
        if(!Test.isRunningTest()){
            Database.executeBatch(new Turn_ON_ValidationRulesBatch(), 1);
        }
    }
   
    
    
}