unpackaged/main/default/objects/ValuePlus__c/ValuePlus__c.object-meta.xml
<CustomObject>
    <label>Value+</label>
    <nameField>
        <displayFormat>VAS{000000}</displayFormat>
        <label>Value+</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ValuePlus</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ValuePlus__c/fields/GIACTBusinessOwner_1_Validation__c.field-meta.xml
<CustomField>
    <fullName>GIACTBusinessOwner_1_Validation__c</fullName>
    <label>Business Owner 1 Validation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready To Transmit To GIACT</fullName>
            </value>
            <value>
                <fullName>Automated Approval</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
            <value>
                <fullName>Manual Approval</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Need Review</fullName>
                <isActive>false</isActive>
                <label>Need Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/GIACTBusinessOwner_2_Validation__c.field-meta.xml
<CustomField>
    <fullName>GIACTBusinessOwner_2_Validation__c</fullName>
    <label>Business Owner 2 Validation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready To Transmit To GIACT</fullName>
            </value>
            <value>
                <fullName>Automated Approval</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
            <value>
                <fullName>Manual Approval</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Need Review</fullName>
                <isActive>false</isActive>
                <label>Need Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/GIACTBusinessOwner_3_Validation__c.field-meta.xml
<CustomField>
    <fullName>GIACTBusinessOwner_3_Validation__c</fullName>
    <label>Business Owner 3 Validation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready To Transmit To GIACT</fullName>
            </value>
            <value>
                <fullName>Automated Approval</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
            <value>
                <fullName>Manual Approval</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Need Review</fullName>
                <isActive>false</isActive>
                <label>Need Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/GIACTBusinessOwner_4_Validation__c.field-meta.xml
<CustomField>
    <fullName>GIACTBusinessOwner_4_Validation__c</fullName>
    <label>Business Owner 4 Validation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready To Transmit To GIACT</fullName>
            </value>
            <value>
                <fullName>Automated Approval</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
            <value>
                <fullName>Manual Approval</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Need Review</fullName>
                <isActive>false</isActive>
                <label>Need Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/GIACTBusinessValidation__c.field-meta.xml
<CustomField>
    <fullName>GIACTBusinessValidation__c</fullName>
    <label>GIACT Business Validation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready To Transmit To GIACT</fullName>
            </value>
            <value>
                <fullName>Automated Approval</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
            <value>
                <fullName>Manual Approval</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Need Review</fullName>
                <isActive>false</isActive>
                <label>Need Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sold/Not Started</fullName>
            </value>
            <value>
                <fullName>KOC Confirmed</fullName>
                <label>Questionnaire Received</label>
            </value>
            <value>
                <fullName>Sold/Not Ready</fullName>
            </value>
            <value>
                <fullName>On-Boarding</fullName>
            </value>
            <value>
                <fullName>KOC Scheduled</fullName>
            </value>
            <value>
                <fullName>KOC Complete</fullName>
            </value>
            <value>
                <fullName>Build In Progress</fullName>
            </value>
            <value>
                <fullName>Site Presentation</fullName>
            </value>
            <value>
                <fullName>Site Delivered/Final Changes</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Additional Communication (O)</fullName>
            </value>
            <value>
                <fullName>Agreement Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Content Acquisition</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Deferred-Built</fullName>
            </value>
            <value>
                <fullName>Deferred-Canceled</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Final Changes</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Left APM</fullName>
            </value>
            <value>
                <fullName>Left IM</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Live-Free Trial</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Lost During Pilot</fullName>
            </value>
            <value>
                <fullName>Lost In Onboarding</fullName>
            </value>
            <value>
                <fullName>Multi Site Deffered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/TIN_Match__c.field-meta.xml
<CustomField>
    <fullName>TIN_Match__c</fullName>
    <label>TIN Match</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Ready to Transmit</fullName>
            </value>
            <value>
                <fullName>Automated Approval</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
            <value>
                <fullName>Manual Approval</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/GiactIdentifyService.cls
/*
* Test Class: GiactVerifyServiceTest
*/
global without sharing class GiactIdentifyService {
	Static Set <Id> alreadyProcessedRecords = new Set <Id> ();
	static List<ValuePlus__c> vpList;

	// This method will receive only those records which are having the Change in status from to 'Ready to Transmit to Giact'
	@future (callout = true)
	public static void identifyService (Id valuePlusId) {
		try {
			// First Check if the String is empty or not. 
			if (valuePlusId==null) {
				return;
			}

			System.debug('*** Preparing to process GIdentify.');
			// Intatntiate the Class. 
			GIACTIntegrationService gis = new GIACTIntegrationService ();
			gis.pull_GiactIdentifyData ('gidentifyinquiry', valuePlusId);
        }catch(Exception ex){
            SystemExceptionLogger.fireSystemExceptionLogEvent (ex, 'GiactIdentifyService', 'identifyService',
			 	SystemExceptionLogger.EXCEPTION_LEVEL_CRITICAL, ex.getMessage(), 'ValuePlus', valuePlusId, false);
        }
	}

	public static Boolean IsIdetifyProcessingRequired (ValuePlus__c vp) {
		// if (!alreadyProcessedRecords.contains(vp.Id) && (vp.RecordTypeId == InformationStrings.vPlusMycasePaymentsId || vp.RecordTypeId== InformationStrings.vPlusAPMPaymentsId) &&
		// if (!alreadyProcessedRecords.contains(vp.Id) && (vp.RecordTypeId == InformationStrings.vPlusMycasePaymentsId) &&
		if (!alreadyProcessedRecords.contains(vp.Id) &&
			(vp.Stage__c.equals('Sold/Not Started') || vp.Stage__c.equals('On-Boarding') || vp.Stage__c.equals('Live') || vp.Stage__c.equals('Active')) &&
			(vp.TIN_Match__c=='Ready To Transmit' || 
				vp.GIACTBusinessValidation__c =='Ready To Transmit To GIACT' ||								
				vp.GIACTBusinessOwner_1_Validation__c =='Ready To Transmit To GIACT' ||
				vp.GIACTBusinessOwner_2_Validation__c =='Ready To Transmit To GIACT' ||
				vp.GIACTBusinessOwner_3_Validation__c =='Ready To Transmit To GIACT' ||
				vp.GIACTBusinessOwner_4_Validation__c =='Ready To Transmit To GIACT'
			)) {

			return true;
		}

		return false;
	}

	public static void doCallOut(){
		try {
			if(vpList != null && !vpList.isEmpty()){
				for(ValuePlus__c vp : vpList){
					System.debug ('*** Processing Giact - Returning True');
					// Add to the set to that it is not processed again. 
					alreadyProcessedRecords.add (vp.Id);
					GiactIdentifyService.identifyService(vp.Id); 
				}
			}
        }catch(Exception ex){
            SystemExceptionLogger.fireSystemExceptionLogEvent (ex, 'GiactIdentifyService', 'doCallOut',
			 	SystemExceptionLogger.EXCEPTION_LEVEL_CRITICAL, ex.getMessage(), 'ValuePlus__c', null, false);
        }
	}

	public static void processValuePlusRecordsForGiact(ValuePlus__c newRecord){
		try {
			System.debug ('*** Checking if the record needs to be processed with Giact');
			
			if(vpList == null){
				vpList = new List<ValuePlus__c>();
			}

			if(IsIdetifyProcessingRequired(newRecord)){
				vpList.add(newRecord);
			}
        }catch(Exception ex){
            SystemExceptionLogger.fireSystemExceptionLogEvent (ex, 'GiactIdentifyService', 'filterValueAPMWebsites',
			 	SystemExceptionLogger.EXCEPTION_LEVEL_CRITICAL, ex.getMessage(), null, (newRecord != null ? newRecord.Id : null), false);
        }
	}
}