unpackaged/main/default/objects/ValuePlus__c/ValuePlus__c.object-meta.xml
<CustomObject>
    <label>Value+</label>
    <nameField>
        <displayFormat>VAS{000000}</displayFormat>
        <label>Value+</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ValuePlus</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ValuePlus__c/fields/Vantiv_Enrolled_Date__c.field-meta.xml
<CustomField>
    <fullName>Vantiv_Enrolled_Date__c</fullName>
    <label>Vantiv Enrolled Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Vantiv_Legal_Entity_Id__c.field-meta.xml
<CustomField>
    <fullName>Vantiv_Legal_Entity_Id__c</fullName>
    <label>Vantiv Legal Entity Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ValuePlus__c/fields/Vantiv_Onboarding_Status__c.field-meta.xml
<CustomField>
    <fullName>Vantiv_Onboarding_Status__c</fullName>
    <label>Vantiv Onboarding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready To Transmit</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Manual Review</fullName>
            </value>
            <value>
                <fullName>Manual Review - Duplicate</fullName>
            </value>
            <value>
                <fullName>Manual Review - Background Check Error</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Collecting Documents</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Vantiv_Audit_Logs__c/Vantiv_Audit_Logs__c.object-meta.xml
<CustomObject>
    <label>Vantiv Callout Audit Log</label>
    <nameField>
        <displayFormat>VAL-{000000}</displayFormat>
        <label>Vantiv Callout Audit Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vantiv Callout Audit Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vantiv_Audit_Logs__c/fields/ValuePlus__c.field-meta.xml
<CustomField>
    <fullName>ValuePlus__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ValuePlus</label>
    <referenceTo>ValuePlus__c</referenceTo>
    <relationshipLabel>Vantiv Callout Audit Logs</relationshipLabel>
    <relationshipName>Vantiv_Callout_Audit_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/VantivLegalEntityStatusBatch.cls
global class VantivLegalEntityStatusBatch  implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful{
	
	List<Vantiv_Audit_Logs__c> logs = new List<Vantiv_Audit_Logs__c>();
	List<ValuePlus__c> recordsToUpdate = new List<ValuePlus__c>();
	global Database.QueryLocator start(Database.BatchableContext bc)
	{
		return Database.getQueryLocator('Select Id, recordType.Name from ValuePlus__c where Vantiv_Onboarding_Status__c like \'%Manual Review%\' and Vantiv_Enrolled_Date__c < TODAY and Vantiv_Legal_Entity_Id__c != null');
	}
	
	global void execute(Database.BatchableContext bc, List<ValuePlus__c> scope)
	{
		for(ValuePlus__c vp : scope)
		{
			VantivLegalEntityRetrieveReq req;
			try
			{
				String result ;
				req = new VantivLegalEntityRetrieveReq(vp.Id);
				vp.Vantiv_Onboarding_Status__c = req.response.responseDescription;
				result = req.response.responseDescription;
				if(req.response.notes != null){ result = result + '. '+req.response.notes;}
				recordsToUpdate.add(vp);
				logs.add(VantivUtils.createAuditLog(vp.id,req.response.responseDescription, 'enrollment status :'+result, req.response.toString(), 'Retrieve Legal Entity', vp.recordType.Name, true));
			}
			catch(Exception e)
			{
				logs.add(VantivUtils.createAuditLog(vp.id,req.response.responseDescription, e.getMessage(), req.response.toString(), 'Retrieve Legal Entity', vp.recordType.Name, true));
			}
			
		}
		
	}
	global void finish(Database.BatchableContext bc)
	{
		update recordsToUpdate;
		insert logs;
	}

}