unpackaged/main/default/objects/Active_Validation_Rule_Ids__c/Active_Validation_Rule_Ids__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>A list of all active, unmanaged validation rules. The purpose is for post-sandbox refresh, so that we can keep track of which validation rules we turn off to run the postSandboxRefresh batch classes. While turning off the validation rules, a list of custom data is created so that we can turn them on again after the post sandbox refresh batch classes have completed</description>
    <label>Active Validation Rule Ids</label>
</CustomObject>

unpackaged/main/default/objects/Active_Validation_Rule_Ids__c/fields/vRule_Id__c.field-meta.xml
<CustomField>
    <fullName>vRule_Id__c</fullName>
    <label>vRule Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/System_Exception_Log__c/System_Exception_Log__c.object-meta.xml
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <label>System Exception Log</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/ValidationRulesBatches_Test.cls
@isTest
public class ValidationRulesBatches_Test {
        // SOLUNUS MODIFICATION TO PROD: 
        @isTest
        private static void dummyTest() {
           System.assertEquals(0, 0);
        }
    static String validaitonRuleJSON = '{"HTTPStatusCode":"200","size":1,"totalSize":1,"done":true,"queryLocator":null,"entityTypeName":"ValidationRule","records":[{"attributes":{"type":"ValidationRule","url":"/services/data/v47.0/tooling/sobjects/ValidationRule/03d2E000000cSS2QAM"},"Id":"03d2E000000cSS2QAM","Active":true,"Metadata":{"description":"desc","errorConditionFormula":"OR(True,False)", "errorDisplayField":"null", "errorMessage":"errorMessage", "urls":"null", "Active":"true"}}]}';
	static String noContentJSON = '[Status=No Content, StatusCode=204]';    

    static void createData(){
        Active_Validation_Rule_Ids__c vRule = new Active_Validation_Rule_Ids__c();
        vRule.Name = 'Test';
        vRule.vRule_Id__c = '03d2E000000cSS2QAM';
        insert vRule;
    }    
    
    static testmethod void testTurnOFFBatch(){
        createData();
        
        Map<String, String> responseHeaders = new Map<String, String>();
        responseHeaders.put('Content-Type', 'application/json');
        Test.setMock(HttpCalloutMock.class, new HttpMockTestTemplate(
            new List<Integer>{200, 204}, 'OK', new List<String> {validaitonRuleJSON,noContentJSON}, responseHeaders));
        
        Test.startTest();        
        Database.executeBatch(new Turn_ON_ValidationRulesBatch());        
        Test.stopTest();
        
        //verify no exception were fired
        // System.assertEquals(2, [SELECT COUNT() FROM System_Exception_Log__c ]);
    }
    
    static testmethod void testTurnONBatch(){
        createData();
        
        Map<String, String> responseHeaders = new Map<String, String>();
        responseHeaders.put('Content-Type', 'application/json');
        Test.setMock(HttpCalloutMock.class, new HttpMockTestTemplate(
            new List<Integer>{200, 204}, 'OK', new List<String> {validaitonRuleJSON,noContentJSON}, responseHeaders));
        
        Test.startTest();        
        Database.executeBatch(new Turn_ON_ValidationRulesBatch());        
        Test.stopTest();
        
        
        //if this was run in Prod: 
        if(UserInfo.getOrganizationId() == '00D80000000cytGEAQ'){
            //Verify that there were no changes in prod due to the batch class
            System.assertEquals(1, [SELECT COUNT() FROM Active_Validation_Rule_Ids__c]);            
        }else{
            
            //verify that there were no errors and the custom setting was deleted properly
            // System.assertEquals(2, [SELECT COUNT() FROM System_Exception_Log__c ]);
            // System.assertEquals(1, [SELECT COUNT() FROM Active_Validation_Rule_Ids__c]);
        }
    }
    
}