unpackaged/main/default/objects/AmazonSQS__c/AmazonSQS__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuration details for Amazon SQS Integration</description>
    <label>Amazon SQS</label>
</CustomObject>

unpackaged/main/default/objects/AmazonSQS__c/fields/Access_Key__c.field-meta.xml
<CustomField>
    <fullName>Access_Key__c</fullName>
    <description>Access Key for the AWS Instance</description>
    <label>Access Key</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AmazonSQS__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>SQS queue endpoint</description>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AmazonSQS__c/fields/Queue_Name__c.field-meta.xml
<CustomField>
    <fullName>Queue_Name__c</fullName>
    <description>This is the name of the SQS queue (should have the entire URL to avoid errors)</description>
    <label>Queue Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AmazonSQS__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region of the SQS queue</description>
    <label>Region</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AmazonSQS__c/fields/Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Secret_Key__c</fullName>
    <description>Secret key for the AWS instance</description>
    <label>Secret Key</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/AwsSQSImplementation.cls
public without sharing class AwsSQSImplementation {

    public class AwsSQSImplementationException extends Exception {}
    public static String awsQueue, awsEndpoint, AwsRegion, awsAccesskey, awsSecKey;

    public abstract class Core extends AwsBase {
        
        Core(){
            super();
            method = HttpMethod.XGET;
            payload = Blob.valueOf('');
        }

        public virtual override void init() {
            endpoint = new Url(awsEndpoint);
            accessKey = awsAccesskey;
            region = AwsRegion;
            service = 'sqs';
            host = String.join(new String[] { service, region, 'amazonaws.com' },'.');
	        setHeader('Date', requestTime.formatGmt('yyyyMMdd\'T\'HHmmss\'Z\''));
            setQueryParam('AWSAccessKeyID', accessKey);
            setQueryParam('Timestamp', requestTime.formatGMT('yyyy-MM-dd\'T\'HH:mm:ss\'Z\''));
            setQueryParam('SignatureVersion', '4');
            setQueryParam('SignatureMethod','HmacSHA256');
            setHeader('Accept','application/json');
            //Prevent leaking the secret key by only exposing the signing key
            createSigningKey(awsSecKey);
        }
    }

    public class SendMessageRequest extends Core {
        public void execute(String data) {
        	resource = awsQueue;
            setQueryParam('Action','SendMessage');
            setQueryParam('MessageBody', data);
            setQueryParam('QueueUrl', resource);
            sendRequest();
        }
    }

    public class AwsMessageWrapper {
        @AuraEnabled public String recordId {get; set;}
    	@AuraEnabled public String operation {get; set;}
    }

    public static void sendMessageToPSQueue(String message) {
        getAWSConfig();
        SendMessageRequest req = new SendMessageRequest();
        req.execute(message);
    }

    private static void getAWSConfig() {
        //Access the AWS config deatils from the custom settings data
        AmazonSQS__c queueConfig = AmazonSQS__c.getOrgDefaults();

        if(queueConfig != null){
            awsQueue = queueConfig.Queue_Name__c;
            awsEndpoint = queueConfig.Endpoint__c;
            AwsRegion = queueConfig.Region__c;
            awsAccesskey = queueConfig.Access_Key__c;
            awsSecKey = queueConfig.Secret_Key__c;
        } else{
            throw new AwsSQSImplementationException('No related AWS SQS configuration found. Please check the AmazonSQS__c custom settings data!');
        }
    }
}